### ISSUE TITLE
Support for PayPal Here card reader

### ISSUE THREAD

**Issue by samalone** [paypal/PayPal-iOS-SDK#1]
It would be nice to have support for the PayPal Here card reader in addition to the card.io camera input.

**Comment by nhouse** [comment]
Is the PayPal here SDK available yet? I can't seem to find any information on it.

I am looking into using either a Square or PayPal Here for mobile POS credit card processing. We would have around 18 POS operations around the country and would use the card reader with iPads (iOS). Ideally we would be able to use PayPal Here in conjunction with a custom iOS app we write for our checkout system, but that would be dependent upon whether there's a way for our app to interface with the card reader and PayPal for processing.

**Comment by djMax** [comment]
https://github.com/PayPal-Mobile/ios-here-sdk-dist

**Comment by djMax** [comment]
You have two choices here - first is side loader which is discussed in this thread - easy integration, EMV capable, etc. The second is the SDK which puts you in more control at the cost of having to implement the rest of the "point of sale" parts.
