### ISSUE TITLE
verify payments with MSDK v2

### ISSUE THREAD

**Issue by iosappwithpaypal** [paypal/PayPal-iOS-SDK#129]
Hi

I have a question reg usage of API.

I have integrated my app with MSDK v2 according to the guidelines in https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/single_payment.md. I created app and am using sandbox client id of app. When I do the payment on simulator, I get "PAY-6RV70583SB702805EKEYSZ6Y" as id (in completedPayment method) if i pay with my sandbox paypal email account and id as "API-PAYMENT-ID-1843" if I pay with mock credit card number. When I verify any of these ids on linux server with curl (as given in https://developer.paypal.com/webapps/developer/docs/integration/mobile/verify-mobile-payment/), I'm not getting any response. What am I doing wrong?

Thank you.

iosdev@mobappserv:~/mobserver/ewfserver$ curl https://api.sandbox.paypal.com/v1/payments/payment/API-PAYMENT-ID-1843  -H "Content-Type: application/json"  -H "Authorization: Bearer {accessToken}"
iosdev@mobappserv:~/mobserver/ewfserver$ 
iosdev@mobappserv:~/mobserver/ewfserver$ echo $?
0
iosdev@mobappserv:~/mobserver/ewfserver$ 

iosdev@mobappserv:~/mobserver/ewfserver$ curl https://api.sandbox.paypal.com/v1/payments/payment/PAY-6RV70583SB702805EKEYSZ6Y  -H "Content-Type: application/json"  -H "Authorization: Bearer {accessToken}"
iosdev@mobappserv:~/mobserver/ewfserver$ echo $?
0
iosdev@mobappserv:~/mobserver/ewfserver$

**Comment by laxmanAppminds** [comment]
Hi I am getting this issue in this server issue.
 2015-03-16 13:36:38.747 Quorier[2011:110366] PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: fe6414a9dc32c [sandbox, PayPal iOS SDK 2.8.0]

Can you please check it and let me know why this issue coming or Paypal SDK. Thanks in advance

**Comment by romk1n** [comment]
@laxmanAppminds please open a new issue. Thanks!
