### ISSUE TITLE
Payment amount truncated

### ISSUE THREAD

**Issue by shantanukhanwalkar** [paypal/PayPal-iOS-SDK#133]
Even using the latest SDK (2.0.3) the payment amount becomes truncated for amounts greater than 5 digits (including decimals). Is there a work around for this? The short description is also short enough.

![screen shot 2014-04-15 at 12 19 40 pm](https://cloud.githubusercontent.com/assets/3748257/2704318/5c8d8a18-c46a-11e3-8da9-74ff349a3c15.png)
![screen shot 2014-04-15 at 12 19 46 pm](https://cloud.githubusercontent.com/assets/3748257/2704319/5ce10fda-c46a-11e3-82d0-674cc14b687f.png)

**Comment by vicentebalderas** [comment]
Hi Shannaro, I'm having the same error, how did you fix it?

**Comment by Shannaro** [comment]
@vicentebalderas  Sorry, I no longer have the code base for the project I was working on. Go through the docs again, I think that should help you!
