### ISSUE TITLE
Sandbox account money is not deducted from personal account

### ISSUE THREAD

**Issue by vivekCZ** [paypal/PayPal-iOS-SDK#137]
In my app when I try new SDK and test app in sandbox mode  I got this response:
{
    client =     {
        environment = sandbox;
        "paypal_sdk_version" = "2.0.2";
        platform = iOS;
        "product_name" = "PayPal iOS SDK";
    };
    response =     {
        "create_time" = "2014-04-15T10:19:02Z";
        id = "PAY-6C9862538L110700WKNGQPFQ";
        intent = sale;
        state = approved;
    };
    "response_type" = payment;
}

That means my transaction done successfully. But money is not deducted from my personal account though it is added to merchant account at that time.

**Comment by maulik15** [comment]
in which account money is deducted and in which it transfer ?

**Comment by ppmtscory** [comment]
@maulik15 can you please elaborate on your question?  With the mSDK, the credentials that are being used in the App are related to the account that will be receiving the funds.  The account that you use as the 'consumer' to pay will be the account that the money comes from.  In the sandbox, you can see the movement of funds but no actual 'real' money is used.
