### ISSUE TITLE
Undefined symbols for architecture armv7s when deployment target = 6.0

### ISSUE THREAD

**Issue by pivotl** [paypal/PayPal-iOS-SDK#141]
When I set the deployment target to 6.0 and run the app in the simulator everything works as expected, but if I run the app on a device I receive this error:

Undefined symbols for architecture armv7s:
  "std::__1::__vector_base_common<true>::__throw_length_error() const", referenced from:
      std::__1::vector<cv::Vec<int, 128>, std::__1::allocator<cv::Vec<int, 128> > >::__append(unsigned long) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      std::__1::vector<cv::Vec<int, 64>, std::__1::allocator<cv::Vec<int, 64> > >::__append(unsigned long) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      std::__1::vector<cv::Vec<int, 32>, std::__1::allocator<cv::Vec<int, 32> > >::__append(unsigned long) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      std::__1::vector<cv::Vec<int, 16>, std::__1::allocator<cv::Vec<int, 16> > >::__append(unsigned long) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      std::__1::vector<cv::Vec<int, 12>, std::__1::allocator<cv::Vec<int, 12> > >::__append(unsigned long) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      std::__1::vector<cv::Vec<int, 9>, std::__1::allocator<cv::Vec<int, 9> > >::__append(unsigned long) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      std::__1::vector<cv::Vec<int, 8>, std::__1::allocator<cv::Vec<int, 8> > >::__append(unsigned long) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      ...
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::operator=(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      cv::Exception::formatMessage() in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      cv::Exception::Exception(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      cv::error(cv::Exception const&) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const_, unsigned long)", referenced from:
      _DMZ_fc25492ba21335d69fb04c299b9af1e0(_IplImage_, unsigned char) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      _DMZ_041e9ca00ee2665bef049c47c482dbd6(_DMZ_66a991225a4ebc903cc5e08878e64275_, _IplImage_, _DMZ_200145a25bf71dde0e26f96431feb196_) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      cv::fastMalloc(unsigned long) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      cv::convertAndUnrollScalar(cv::Mat const&, int, unsigned char_, unsigned long) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      cv::binary_op(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, void (\* const_)(unsigned char const_, unsigned long, unsigned char const_, unsigned long, unsigned char_, unsigned long, cv::Size_<int>, void_), bool) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      cv::arithm_op(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, int, void (__)(unsigned char const_, unsigned long, unsigned char const_, unsigned long, unsigned char_, unsigned long, cv::Size_<int>, void_), bool, void_) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      cv::compare(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, int) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      ...
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()", referenced from:
      _DMZ_fc25492ba21335d69fb04c299b9af1e0(_IplImage_, unsigned char) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      _DMZ_041e9ca00ee2665bef049c47c482dbd6(_DMZ_66a991225a4ebc903cc5e08878e64275_, _IplImage_, _DMZ_200145a25bf71dde0e26f96431feb196_) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      cv::fastMalloc(unsigned long) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      cv::convertAndUnrollScalar(cv::Mat const&, int, unsigned char_, unsigned long) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      cv::binary_op(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, void (_ const_)(unsigned char const_, unsigned long, unsigned char const_, unsigned long, unsigned char_, unsigned long, cv::Size_<int>, void_), bool) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      cv::arithm_op(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, int, void (__)(unsigned char const_, unsigned long, unsigned char const_, unsigned long, unsigned char_, unsigned long, cv::Size_<int>, void_), bool, void_) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      cv::compare(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, int) in libPayPalMobile.a(libCardIO.a-armv7s-master.o)
      ...
ld: symbol(s) not found for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I am using SDK 2.0.5. and receive no errors when the deployment target is set to 7.0.
Any help is greatly appreciated.

**Comment by y500** [comment]
saved me a lot of time
