### ISSUE TITLE
INTERNAL_SERVICE_ERROR - System error - sandbox, PayPal iOS SDK 2.1.0

### ISSUE THREAD

**Issue by Markpeter** [paypal/PayPal-iOS-SDK#150]
I tried in sandbox mode and got the below error in xcode, 

<pre>
 2014-05-21 17:34:06.082 MyApp[16982:60b] PayPal SDK: Request has failed<br> 
 with error: INTERNAL_SERVICE_ERROR - System error. Please try again <br>
 later. (500) <br>
| PayPal Debug-ID: 2071b922aee48 [sandbox, PayPal iOS SDK 2.1.0]
</pre>

This happens very rare but still needs to be considered.

**Comment by harminderjarvics** [comment]
i am having the same issue 

PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: c1892283e42e2, c1892283e42e2 [sandbox, PayPal iOS SDK 2.14.4]

please help me ASAP.
the pay pal controller shows this error..but the amount gets deducted from the balance..

**Comment by KartikSinghBhadoriya** [comment]
I am facing same issue before 2 hours it's working and now I switch live to sandbox it's give me this error

PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 39c25d213574c, 39c25d213574c [sandbox, PayPal iOS SDK 2.14.2]

Please Help me ASAP

**Comment by manuel-norsync** [comment]
I am currently having the same issue in both Android and iOs, any updates regarding this issue? 

Thanks.

**Comment by Apofeozzz** [comment]
PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: ce419dcf93d92, ce419dcf93d92 [sandbox, PayPal iOS SDK 2.14.7]
