### ISSUE TITLE
Get user information

### ISSUE THREAD

**Issue by hoang2109** [paypal/PayPal-iOS-SDK#156]
I added PayPal-iOS-SDK to my application. After setup future payment, I got an Authorization code. I want to get all user information for my app. I used REST API to grant token from authorization code and then get user information by this API:
curl -v https://api.sandbox.paypal.com/v1/identity/openidconnect/userinfo/?schema=openid \
-H "Content-Type:application/json" \
-H "Authorization: Bearer {accessToken}"

The result only contains user_id. I want to have user's profile, address, etc... How can I do that? Maybe you didn't add the scope at the authentication process, right?

Thanks.

**Comment by Miteshimmply** [comment]
I have added PayPal-iOS-SDK to my application.I want to get all user information for my app. I used REST API to grant token from authorisation code and then get user information by this API:
curl -v https://api.sandbox.paypal.com/v1/identity/openidconnect/userinfo/?schema=openid \
-H "Content-Type:application/json" \
-H "Authorization: Bearer {accessToken}"

The result only contains user_id. I want to have user's profile, address, etc... 

what will be the step to get User Info after Paypal login.
