### ISSUE TITLE
Send custom data at payments

### ISSUE THREAD

**Issue by Pseudolus** [paypal/PayPal-iOS-SDK#194]
Hi

I'm developing an app using your framework, and i've found that issue: in the PayPalPayment structure i would like to use the field CUSTOM to send custom data about the purchasing. When i identify myself with a PayPal login in the app, it works correctly, but when I use a credit cart, without previous PayPal login, the IPN receive the field cusom as empty

Is any way to send custom data to the IPN in the cases that the user don't identify himself, introducing directly a credit cart?

I've found this issue in the iOS framework; will be the same problem in Android?

**Comment by dgoldman-ebay** [comment]
@Pseudolus I was just checking on this issue. In the experiment I just ran, at least, the problem seems to have been resolved.

Please re-open this issue if you continue to run into this problem.
