### ISSUE TITLE
Cannot login to PayPal in Sandbox Environment

### ISSUE THREAD

**Issue by sbiermanlytle** [paypal/PayPal-iOS-SDK#207]
Hi I successfully integrated the SDK using PayPalEnvironmentNoNetwork, but whenever I switch to PayPalEnvironmentSandbox, I get this error when I try to login to paypal on the device:

```
PayPal SDK: Request has failed with error: invalid_user - Incorrect username/password. Please try again. (401) | PayPal Debug-ID: a6ca98fd52d2b [sandbox, PayPal iOS SDK 2.5.0] | Details: (
        {
        "error_description" = "Invalid user credentials";
    }
)
```

I use the same credentials in both cases, and they work with NoNetwork and in a web browser.

I am using a different paypal account to set up the App and generate the client_id.

Why can't I login in Sandbox mode?

**Comment by arjunhastir** [comment]
I am facing the same one 
< Paypal-Debug-Id: c110d7d6085e1

**Comment by karmadeli** [comment]
Hey, 

This fixed the "Invalid user credentials" error for me:
**Hop over to the Sandbox Account Section of your https://developer.paypal.com/developer/accounts/ page**
**click your buyer email address**
**select profile from the dropdown**
**change the password**

**try to login again, this time with the sandbox buyer email address and the new password**. hope this works for you too.
