### ISSUE TITLE
How can I use two Paypal account in one App?

### ISSUE THREAD

**Issue by mrgaolei** [paypal/PayPal-iOS-SDK#215]
I need to integration multiple paypal accounts in one single app, so that the customer can pay accordingly. how can i do this using:
- (void)initializeWithClientIdsForEnvironments:(NSDictionary *)clientIdsForEnvironments; ?

**Comment by cpino** [comment]
Same problem. I have my personal account on Paypal, and now also the company account. So I need to use the same app with the need to select which Paypal account to use.

It this supported by the app ?

**Comment by bluk** [comment]
@cpino If you're talking about using multiple accounts as the payee (e.g. the person/entity getting paid), please see https://github.com/paypal/PayPal-iOS-SDK/issues/140 and the [latest release](https://github.com/paypal/PayPal-iOS-SDK/releases) to see if using the payeeEmail fits your needs. This allows a merchant to facilitate a third party payee. If that isn't your issue, please open a new issue with more details on your use case. Thanks.
