### ISSUE TITLE
There is a problem communicating with the PayPal servers . Please try again.

### ISSUE THREAD

**Issue by comgateway** [paypal/PayPal-iOS-SDK#22]
We tested the code in Sandbox environment , it was OK.

When we switch to Live/Production environment , modifying the credentials under ZZMainViewController.h in the sample code within the PayPal-iOS-SDK.zip
live credentials obtained from https://developer.paypal.com/webapps/developer/applications/myapps
# define kPayPalClientId @"..."
# define kPayPalReceiverEmail @"..."

  self.acceptCreditCards = NO;
  self.environment = PayPalEnvironmentProduction;

We keep getting this error, in both iphone simulator and live iphone devices:

There is a problem communicating with the PayPal servers . Please try again.

We can log in to PayPal live, but when click send payment, the problem occurs. Attached are the screenshots.

![ios simulator screen shot 21 jun 2013 5 45 32 pm](https://f.cloud.github.com/assets/3280775/693085/a7e5263a-dc6f-11e2-8613-4881a33ccb7e.png)

![ios simulator screen shot 21 jun 2013 5 49 54 pm](https://f.cloud.github.com/assets/3280775/693087/dbf0310e-dc6f-11e2-87a2-9faf2c35c1ee.png)

**Comment by SwappyD** [comment]
Hello,
         I am facing same problem. I have created US based sandbox account. In sample app code have used following CLIENT_ID.

PayPalEnvironmentSandbox : @"AFcWxV21C7fd0v3bYYYRCpSSRl31AqobHyAcg9npaCbtFnE7xlWC0JwE"

Here is console log:

PayPal iOS SDK Version: PayPal iOS SDK 2.12.7
Environment: Optional("mock"). Accept credit cards? Optional(false)
Environment: Optional("sandbox"). Accept credit cards? Optional(false)
PayPal Payment Cancelled

I am running sample app project on iphone6(8.1)
This what problem is :

![screen shot 2015-11-19 at 1 01 29 pm](https://cloud.githubusercontent.com/assets/15921143/11264949/16459d32-8ebe-11e5-967e-d58b93f04768.png)

**Comment by maxydey** [comment]
Hi. getting same issue right now. Both Android and iOS SDK, sandbox. Yesterday it was working fine

`<: Request has failed with error: pp_service_error_json_parse_error - System error. Please try again later. (403) | Details: (
        {
        "ns_error" = "Error Domain=NSCocoaErrorDomain Code=3840 \"JSON text did not start with array or object and option to allow fragments not set.\" UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}";
    }
).>`

**Comment by bluk** [comment]
@maxydey Please try again now. There may have been an issue with sandbox earlier but it should work now.

Also, please open a new issue if this persists. It helps us track issues better. Thanks.
