### ISSUE TITLE
invalid bundle structure - the binary file libPaypalmobile.a is not permitted. your app may contain only one executable file

### ISSUE THREAD

**Issue by probalroy** [paypal/PayPal-iOS-SDK#233]
I am getting following error when I try to validate app or submit app in apple store. 
"invalid bundle structure - the binary file libPaypalmobile.a is not permitted. your app may contain only one executable file"
There is no error in test flight. App runs fine in i-Phone device through test flight. Executable file libPayPalMobile.a is added in build because there is paypal payment module is integrated in the app. If I remove libPayPalMobile.a, build gives error. How do I submit app by including libPayPalMobile.a within the build. Any help to resolve this error will be appreciated.

**Comment by THAANURK** [comment]
hey, I too having problem with paytm sdk !!! can you help me to sort it out, i tried all the above steps still same error

**Comment by pp-randy** [comment]
We'll work with you in your new issue https://github.com/paypal/PayPal-iOS-SDK/issues/565.
