### ISSUE TITLE
Some strange exception with PayPal 2.8.0 (makes me aware)

### ISSUE THREAD

**Issue by gelosi** [paypal/PayPal-iOS-SDK#237]
Hello again. Here we go. Another crash :+1: 
The crash happened with ios 7.1 on simulator (simulator is version 8.1 (550.3) - latest at the date I'm posting this issue)

looks like you guys don't expect something new from Apple any more:
*Wrong type object in decode knownDeviceModel*

`
(lldb) po *(id *)($esp + 4)
Wrong type object in decode knownDeviceModel

(lldb) bt
* thread #1: tid = 0x14555a, 0x034e68b9 libobjc.A.dylib`objc_exception_throw, queue = 'com.apple.main-thread', stop reason = breakpoint 2.3
  * frame #0: 0x034e68b9 libobjc.A.dylib`objc_exception_throw
    frame #1: 0x01acb3ab Foundation`_decodeObjectBinary + 4411
    frame #2: 0x01aca106 Foundation`_decodeObject + 340
    frame #3: 0x01ac9faa Foundation`-[NSKeyedUnarchiver decodeObjectForKey:] + 181
    frame #4: 0x01b3ba86 Foundation`+[NSKeyedUnarchiver unarchiveObjectWithData:] + 106
    frame #5: 0x00304fb1 MySecretApp `-[PPRiskComponent initWithAppGuid:withAPNSToken:withConfigurationURL:withSourceApp:withSourceAppVersion:withStartAsyncServiceFlag:withPairingId:withAdId:] + 1378
    frame #6: 0x0030496f MySecretApp `__154+[PPRiskComponent initWithAppGuid:withAPNSToken:withConfigurationURL:withSourceApp:withSourceAppVersion:withStartAsyncServiceFlag:withPairingId:withAdId:]_block_invoke + 150
    frame #7: 0x03ada4d0 libdispatch.dylib`_dispatch_client_callout + 14
    frame #8: 0x03ac9e12 libdispatch.dylib`dispatch_once_f + 184
    frame #9: 0x03ac9d55 libdispatch.dylib`dispatch_once + 31
    frame #10: 0x003048d4 MySecretApp `+[PPRiskComponent initWithAppGuid:withAPNSToken:withConfigurationURL:withSourceApp:withSourceAppVersion:withStartAsyncServiceFlag:withPairingId:withAdId:] + 535
    frame #11: 0x002ad5d0 MySecretApp`-[PayPalMobile init] + 287
    frame #12: 0x002ac44e MySecretApp `__30+[PayPalMobile sharedInstance]_block_invoke + 55
    frame #13: 0x03ada4d0 libdispatch.dylib`_dispatch_client_callout + 14
    frame #14: 0x03ac9e12 libdispatch.dylib`dispatch_once_f + 184
    frame #15: 0x03ac9d55 libdispatch.dylib`dispatch_once + 31
    frame #16: 0x002ac415 MySecretApp `+[PayPalMobile sharedInstance] + 69
    frame #17: 0x002ac5ea MySecretApp `+[PayPalMobile initializeWithClientIdsForEnvironments:] + 213
`

**Comment by dgoldman-ebay** [comment]
By now, either we've fixed this one, or it fixed itself, or it's so rare that nobody ever hits it (with the above single exception). Closing for now.
