### ISSUE TITLE
Getting consent for profile sharing & future payments

### ISSUE THREAD

**Issue by Rizon87** [paypal/PayPal-iOS-SDK#238]
Hi,

I'm using iOS SDK v2.8.
I'd like to request the user to approve future payments and also get his email address.

Following the instructions, I understand I need to get 2 authorization codes: 1 for profile sharing (https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/profile_sharing_mobile.md#obtain-customer-consent) and 1 for future payments (https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_mobile.md#obtain-customer-consent).

The problem with that approach is that it makes me present 2 login screens to the user in order to get the different authorization codes - one at a time.
Is that really so? There must be a better way to ask for these 2 permissions at the same time, using a single user login.

Any idea?

**Comment by augustinAJ** [comment]
Same requirement. But getting following error.

PayPal SDK: Request has failed with error: invalid_request - An error has occurred. (400) | PayPal Debug-ID: 95c2cdbb4af78, 95c2cdbb4af78 [sandbox, PayPal iOS SDK 2.14.3] | Details: (
        {
        "error_description" = "Invalid scope requested [email]";
    }
).

**Comment by bluk** [comment]
@augustinAJ Be sure that you have the `Email address` scope attribute checked in the [PayPal Developer Dashboard for your app](https://developer.paypal.com/developer/applications/). Click on your app's name and then scroll down to the `Sandbox/Production App Settings`. Click `Advanced Options` to expand the section. Then Click `Customize` for the various sections and enable the Email scope.

If this does not work, please open a new issue. Here's a screenshot of what you can select for scope attributes:

![screen shot 2016-06-28 at 9 39 41 am](https://cloud.githubusercontent.com/assets/94150/16419775/922bcf98-3d14-11e6-8269-c85440f17e28.png)

**Comment by augustinAJ** [comment]
@bluk  Thanks. I didn't noticed that. So with the same authorization_code we can use the future payments and profile sharing feature...ryt?
