### ISSUE TITLE
Live Credit card payment failed with UNKNOWN_ERROR

### ISSUE THREAD

**Issue by mpaluy** [paypal/PayPal-iOS-SDK#240]
Hi,
PayPal payment completed successfully, but credit card payment failed with following message:
    Request has failed with error: UNKNOWN_ERROR - System error (UNKNOWN_ERROR). 
    Please try again later. (400) | PayPal Debug-ID: 1fa35b61d1fe7 [live, PayPal iOS SDK 2.7.1]
 
Please, assist me.

M.

**Comment by mpaluy** [comment]
@romk1n What is the correct way to ask for billing address while paying with Credit Card? Is it possible to make it from the SDK? (I don't know the payment method selected by my users)
Thanks

**Comment by romk1n** [comment]
@mpaluy at the moment we don't have an option in ask for zip code when entering credit card details. Have you actually spoke to support? it sounds like it is an account setup problem.

**Comment by mpaluy** [comment]
@romk1n The support response was "The error was thrown because you've missed the billing address of the credit card in the request. Try to add the address, and test it again."

I'd like to clarify my flow:
1. The user selects a Pay with Card method
![paypal_ios_sdk_screenshot](https://cloud.githubusercontent.com/assets/1524137/5685279/7d9b4302-9841-11e4-9872-31d9fa505ece.png)
2. She uses card.io scanner to scan the credit card.

I would expect the Paypal SDK to request the Billing address after it. 

What is the correct way to ask for billing address?

**Comment by ppmtscory** [comment]
@mpaluy can you please submit a support ticket at www.paypal.com/mts and let me know the ticket number here?  Please include a phone number that I can reach out to you at, as I have a couple questions regarding your account settings.

**Comment by dpaluy** [comment]
@ppmtscory I have the following:
BusinessSolutions (ID: C840-L001-T12014-S111-W000000) :ppNA [Incident: 150107-000332]

Can you please contact me offline: dpaluy at gmail dot com

**Comment by ppmtscory** [comment]
@dpaluy I just responded to that ticket so I'll be closing this Github issue.  We'll continue to work through the ticket as I don't want you to have to put account info on this public Github forum. If you need me to change the email address assigned to your ticket, feel free to put that in your reply as well.
