### ISSUE TITLE
UIButtons showing trimmed text for "Cancel" and "Done"

### ISSUE THREAD

**Issue by emadrazo** [paypal/PayPal-iOS-SDK#241]
I am using 2.8.0 version of PayPal-iOS-SDK.
I am seeing button title labels trimmed as shown in images. I can only see "C" for "Cancel" and "D" for "Done".  I have checked that this behaviour is the same if I change device language to spanish "C" for "Cancelar" and "H" for "Hecho".
I am not using UIAppearance in my project.

The buttons are working as expected, and pushing on the "invisible trimmed" text work, I mean the UIButton seems to be right sized, but it does not show the complete text.

I have observed this issue on simulator and also on device.

![img_6031](https://cloud.githubusercontent.com/assets/296309/5661966/9ac03646-9732-11e4-85cd-2744c6873668.PNG)
![img_6032](https://cloud.githubusercontent.com/assets/296309/5661967/9ac42ada-9732-11e4-8112-5c8453779c02.PNG)

Whatelse could I check?

Thanks in advance.

**Comment by romk1n** [comment]
@emadrazo Please note this advice from our integration instructions:

User interface appearance and behavior is set within the library itself. For the sake of usability and user experience consistency, apps should not adjust appearance properties or attempt to modify the SDK's behavior beyond the documented methods in the provided headers.

Specifically, if you are using UIAppearance to modify the appearance of any UI elements in your app, you should reverse those changes prior to presenting our viewcontroller, and set them again after dismissing the viewcontroller.

**Comment by emadrazo** [comment]
no, I am not using any library using UIAppearance as far as I know. :( 
How can I reset UIAppearance?  I could try to do it in order to see if that is the problem..

**Comment by dgoldman-ebay** [comment]
> Maybe you could reset appearance and leave it as it was inside Paypal library in order to avoid this kind of problems, that will be very useful for us using uiappearance ;)

@emadrazo we'd love to do that! Unfortunately, there are many, many, many possible UIAppearance settings, and no way to reset all of them at once. (Also, if we reset them all, then when our library returns control to your code, they would still be reset. There's no way for us to restore your settings.)
