### ISSUE TITLE
The payment was made, but not able to sent the payment_id to my server

### ISSUE THREAD

**Issue by eridbardhaj** [paypal/PayPal-iOS-SDK#242]
I am testing my application in SandBox mode where I have integrated PayPal SDK on my iOS Application. Everything is implemented step by step like the documentation:

1. I setup and configure the payments
2. Proceed to PayPalViewController, where the Login to PayPal shows up
3. The user logins, chooses the shipping address and confirms the payment (money sent)
4. My business account confirms the payment directly without reviewing it
5. Right now the internet goes down, and I am not able to sent my *payment_id* to my server 

The following errors come up:

My server verifies payment and confirms the order only if I send to it the *payment_id* so it can check the current status of the payment. But since the user has not Internet, he paid the money with its confirmation, but I can not proceed any order if I don't confirm it.

So is there anyway here to handle this on PayPal, to refund the user automatically or to cancel this payment? If not can you at least provide me an example of a good integration of PayPal, that can find a good way to handle this case?

**Comment by romk1n** [comment]
@eridbardhaj you have a number of options:

1. you can cache the payment-id and send it to your server when connection becomes available.
2. you can go through payments (https://developer.paypal.com/docs/api/#list-payment-resources) and check those which you didn't receive notifications from (maybe using some cron job)
3. you can use [Webhooks](https://developer.paypal.com/docs/integration/direct/rest-webhooks-overview/) to get notified when transaction happens
4. lastly you can use [Auth/Capture]https://developer.paypal.com/docs/integration/direct/capture-payment/) but that would require more complex integration.

I guess from your description i would have a look at option 3.

**Comment by eridbardhaj** [comment]
@romk1n thanks for your reply and your recommended choices, but let's suppose this example. 

1. User1 wants to buy a specific product (which has a number of stock available) 
2. User1 proceeds and makes the payment and the network goes down without being able to send payment_id to server 
3. Right now User2 bought this item and confirmed it so we don't have more products in stock (I have opportunity to block the product in pending state so no one can buy this item, but I don't know how long it will take for the user to proceed this payment, or maybe this payment is not confirmed also, and I can be blocking this item without buying it)
4. The network comes up on the User1 we require to verify payment, and we validate its purchase for this product. 
5. User1's money are added to our account

What I need to do is to refund the money back to User1, but if I do this manually, it is a pain job, and not something automated. 

How to automatically refund the User1 automatically depending on his info?

**Comment by ppmtscory** [comment]
I'm inclined to agree with @romk1n in regards to the Webhooks option.  Webhooks are are server -> server communication so if the user loses internet connection on their phone, you should still receive the Webhook from PayPal's server to your server.  Once you receive the Webhook, you can determine what you'd like to do with the transaction.  I believe this is your best option at automation to cover your particular use case.

**Comment by eridbardhaj** [comment]
@romk1n  and @ppmtscory thank you both for clarifying this issue. :)
