### ISSUE TITLE
strange behavior in sandbox mode.

### ISSUE THREAD

**Issue by sazizbekyants** [paypal/PayPal-iOS-SDK#243]
I have integrated PayPal SDK on my iOS Application and try test my application in SendBox mode. When I make payment I get success result but when I login via web I can not found already made payment in transactions list i.e in “Payments received “ tab. is it correct behavior ? is it associated with sendBox mode ?
response json string. 

{"environment":"mock","product_name":"PayPal iOS SDK","paypal_sdk_version":"2.7.1","platform":"iOS"},"response_type":"payment","response":{"id":"PAY-NONETWORKPAYIDEXAMPLE123","state":"approved","create_time":"2015-01-09T21:56:22Z","intent":"sale"}}

**Comment by romk1n** [comment]
@sazizbekyants the response you have provided clearly indicates that library is in a Mock mode which is NoNetwork. Make sure you have set `PayPalEnvironmentSandbox` when calling [`preconnectWithEnvironment`](https://github.com/paypal/PayPal-iOS-SDK/blob/master/PayPalMobile/PayPalMobile.h#L54) .
