### ISSUE TITLE
PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error.

### ISSUE THREAD

**Issue by umairhhhs** [paypal/PayPal-iOS-SDK#245]
Please try again later. (500) | PayPal Debug-ID: 3ea76a5e7a6fd [live, PayPal iOS SDK 2.8.0].I had logged in this error appears when i tap on send payment.
![screen shot 2015-01-12 at 3 41 00 pm](https://cloud.githubusercontent.com/assets/3743639/5701735/7dd1434e-9a71-11e4-86fe-3367bf508420.png)

error logged :
 PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 3ea76a5e7a6fd [live, PayPal iOS SDK 2.8.0]

While everything was running fine while i was testing it in sandbox these error starts after I put the environment to live

**Comment by mattjacunski** [comment]
@umairhhhs - There is a server issue currently causing 500s to be returned in cases where the payer's account does not have a valid funding source available.  I can't say for sure if this is the case for you.  Can you try another payment and share the debug-id (and the PROXY_SERVER_INFO HTTP header on the 500 response if you can).

Sorry for the inconvenience.

**Comment by mattjacunski** [comment]
The server issue has been fixed.  A declined funding instrument will now result in the expected 400 response and appropriate error code.
