### ISSUE TITLE
PaypalPayment not processable

### ISSUE THREAD

**Issue by emadrazo** [paypal/PayPal-iOS-SDK#246]
Good morning, 
I have an issue with SDK 2.8.0
Sometimes, when we are adding a lot of items in the payment details, we obtain this error:

PayPal SDK: PayPalPayment not processable: '100.439999999999975424' contains too many fractional digits.

I have checked the prices I insert in PayPalPayment object and they are NSDecimalNumber (I create it from a double value, but I understantd this is not a problem, isnt't it?)

payment.amount = [[NSDecimalNumber alloc] initWithDouble:totalAmount];

What else could I check? 

Thanks in advance!

**Comment by emadrazo** [comment]
Sorry, I was able to resolve it myself.
It seems a problem with the double values, I have define a behavior for NSDecimalNumbers and I have applied it to all the prices:

[[[NSDecimalNumber alloc] initWithDouble:totalAmount] decimalNumberByRoundingAccordingToBehavior:_behavior];

It works.

**Comment by dgoldman-ebay** [comment]
Good work figuring it out, @emadrazo! :smile:
