### ISSUE TITLE
Crash while pushing to log in

### ISSUE THREAD

**Issue by tbxdeveloper** [paypal/PayPal-iOS-SDK#248]
Hi there!
i am suffering an estrange crash in my app.  When i execute [self presentViewController:paymentViewController animated:YES completion:nil] everything is fine if i set acceptCreditCards to YES, and paypal main screen appears. If i then tap on credit card settings again is fine, but if i tap to paypal login or if acceptCreditCards is set to NO (as paymentViewController will push automatically to loginController) an EXC_BAD_ACCESS error appears. No zombie could give me a clue and i don't get any console output.

I am developing for iOS 7. I followed every instruction for sdk installation that appears in the readme file.

Any idea of what is going on?

Thanks in advance!

**Comment by romk1n** [comment]
@tbxdeveloper can you confirm what library version are you using and device or simulator you getting crash on ?

**Comment by tbxdeveloper** [comment]
Thank you @romk1n for your answer. 

I am using Paypal library 2.8.2 and the crash happened in both iPhone 6 with iOS 8.1 and iOS Simulator with iOS 8.

What really concerns me is the fact that the Paypal paymentViewController is presented without a problem. I also changed the code that presents the controller back to the example app (that works perfectly in all devices i have tested) but i can´t track the crash.

**Comment by romk1n** [comment]
@tbxdeveloper thanks! Do you by any chance subclass `PayPalPaymentViewController` and override some of the defaults methods from `UINavigationController`?

**Comment by tbxdeveloper** [comment]
No, i didn't subclass it. I have tried to change the location in the storyboard but the same happens. PayPalPaymentViewController is presented by a common UIViewController. I am using also Parse.com library and it seems to have some conflict with the -ObjC parameter, but I managed to solve it. I also did the same in the PayPal example app and it worked perfectly so I assume that is not the problem. Any ideas?
Thank you!

**Comment by romk1n** [comment]
@tbxdeveloper without full crash log it is hard to say. what manipulations did you do with -ObjC parameter ?

**Comment by tbxdeveloper** [comment]
@romk1n Well, when you set the -ObjC parameter the part from the parse.com library related to Facebook triggers an link-o exception. The way to solve this is to import the Facebook framework directly in the project. Then a new link-o exceptions appears, as the bolts.framework seems to duplicate the Facebook library. Deleting that framework and adding the accounts and social frameworks to the project allows it to be build without problems. I did this also in the example paypal app and it works perfectly. 

The only thing different that my app has is that it load the storyboard in a different uiviewcontroller, depending on if the user is logged in or not. I don't know if this could be the reason, i will try to check.

The only log that i have is the system log after the app crash:

"com.apple.CoreSimulator.SimDevice.E658AD08-84CF-437D-A58C-9B7ACA1838BC.launchd_sim[842]: assertion failed: 14B25: launchd_sim + 138603 [AAAFA861-0E11-3137-B438-BDDAD2793F55]: 0xe"

I saw that there is a command regarding assertion in the project build settings of the example app (-DNS_BLOCK_ASSERTIONS=1) as other C flag. I put that in my project but nothing changed....

**Comment by romk1n** [comment]
@tbxdeveloper have you tried adding an exception breakpoint for all exceptions ? Ref: https://developer.apple.com/library/ios/recipes/xcode_help-breakpoint_navigator/articles/adding_an_exception_breakpoint.html

**Comment by tbxdeveloper** [comment]
@romk1n yes, of course, but it directly drops me to main.m with the exc_bad_access

**Comment by romk1n** [comment]
@tbxdeveloper you should be able to see all the threads stack traces just like here https://developer.apple.com/library/ios/recipes/xcode_help-debug_navigator/articles/about_debug_navigator.html

**Comment by tbxdeveloper** [comment]
Yes, i uploaded the screenshot here: https://www.dropbox.com/s/h03z5iff3a9pbya/Captura%20de%20pantalla%202015-01-21%20a%20las%200.46.02.png?dl=0

@romk1n thank you!

**Comment by tbxdeveloper** [comment]
And this is the screenshot for the example app with parse libraries added:
https://www.dropbox.com/s/1tug40rt60or1kc/Captura%20de%20pantalla%202015-01-21%20a%20las%200.50.41.png?dl=0

**Comment by romk1n** [comment]
@tbxdeveloper do you want to zip your project and send it to me roman AT x.com, i promise to delete it.

**Comment by romk1n** [comment]
@tbxdeveloper did you figure out a problem? i didn't get any emails from you.

**Comment by tbxdeveloper** [comment]
@romk1n Sorry! I couldn't work on this today. I will try to go after it tomorrow. If I can't isolate the problem I will send you a copy of the project, thank you very much for your proposal!! I will keep you updated :)

**Comment by tbxdeveloper** [comment]
@romk1n i´ve sent you the project. Thank you very much! If you see the reason, please let me know!

**Comment by romk1n** [comment]
@tbxdeveloper unfortunately we don't have access to dropbox at the moment, can you send it by other means (zip would be fine)

**Comment by tbxdeveloper** [comment]
@romk1n ok i´ll find other way

**Comment by romk1n** [comment]
@tbxdeveloper @dgoldman-ebay and i figured it out! The problem is the iOS-Image-Filter library you are using. It implements CIImage category over an existing UIImage property which causes a crash on iOS 8 and misbehavior on iOS 7 when UISegmentedControl is used. We have opened an [issue](https://github.com/jameswomack/iOS-Image-Filters/issues/5) with the library owner. If you require this library just comment out this [code](https://github.com/jameswomack/iOS-Image-Filters/blob/master/UIImage%2BFilter.m#L13) since we hope is it no longer necessary for iOS 7+.

**Comment by tbxdeveloper** [comment]
Wow! Thank you guys! Awesome! I didn't have a clue on this!

**Comment by dgoldman-ebay** [comment]
@tbxdeveloper There's now an updated version of the iOS-Image-Filter library that should no longer exhibit this problem. See https://github.com/jameswomack/iOS-Image-Filters/issues/5

**Comment by Thomaslegravier** [comment]
Hi !
I have the same issue than @tbxdeveloper . When i would launch login action after present paypal naviguationController, application crash. I tried to desactivate some librairies but nothing append, the crash didn't change. 
I am on iOS8 , Xcode 6.4 and Paypal sdk 2.11.4 .
I already try to create a simple paypalViewController to avoid any naviguationController subclass conflict et use him at launch of my application. The crash still the same.
The crash appear on simulator (all kind of device) and on devices.
On your advice, i tried to add and exception break point but he directly drops me to main.m with the exc_bad_access. 
You can see my log : 

2015-09-14 11:19:57.655 Sézane[4456:2293245] card.io: Camera support only available on armv7(s) architecture -- can't use camera
2015-09-14 11:20:04.458 Sézane[4456:2293245] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000110ee7c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000110767bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x0000000110dd1093 -[__NSArrayM objectAtIndex:] + 227
	3   UIKit                               0x000000010f428f50 -[UINavigationBar _setLeftViews:rightViews:] + 5395
	4   UIKit                               0x000000010f41e996 -[UINavigationBar _pushNavigationItem:transition:] + 494
	5   UIKit                               0x000000010f4d61eb __71-[UINavigationController pushViewController:transition:forceImmediate:]_block_invoke + 276
	6   UIKit                               0x000000010f4d4533 -[UINavigationController _startDeferredTransitionIfNeeded:] + 822
	7   UIKit                               0x000000010f4d4ece -[UINavigationController __viewWillLayoutSubviews] + 43
	8   UIKit                               0x000000010f61f6d5 -[UILayoutContainerView layoutSubviews] + 202
	9   UIKit                               0x000000010f3f29eb -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 536
	10  QuartzCore                          0x000000010f0a6ed2 -[CALayer layoutSublayers] + 146
	11  QuartzCore                          0x000000010f09b6e6 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 380
	12  QuartzCore                          0x000000010f09b556 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	13  QuartzCore                          0x000000010f00786e _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 242
	14  QuartzCore                          0x000000010f008a22 _ZN2CA11Transaction6commitEv + 462
	15  QuartzCore                          0x000000010f0090d3 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 89
	16  CoreFoundation                      0x0000000110e1aca7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	17  CoreFoundation                      0x0000000110e1ac00 __CFRunLoopDoObservers + 368
	18  CoreFoundation                      0x0000000110e10a33 __CFRunLoopRun + 1123
	19  CoreFoundation                      0x0000000110e10366 CFRunLoopRunSpecific + 470
	20  GraphicsServices                    0x0000000112380a3e GSEventRunModal + 161
	21  UIKit                               0x000000010f3728c0 UIApplicationMain + 1282
	22  SeÃÅzane                            0x000000010cd1db3f main + 111
	23  libdyld.dylib                       0x00000001116d4145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

The problem seems to be near "-[UINavigationBar _setLeftViews:rightViews:]" instruction. 

 Have you any idea ? 

Thanks for your help !
