### ISSUE TITLE
Donations via Paypal

### ISSUE THREAD

**Issue by shehzadq** [paypal/PayPal-iOS-SDK#249]
I want to implement donations for charity in iOS app but it get rejected from Appstore. Can you guide how can i implement donations using native control and in safari via PayPal.

**Comment by ppmtscory** [comment]
It's not a native solution, but I think your best option for utilizing both Safari and mobile would be to just use a standard [Donate button](https://developer.paypal.com/webapps/developer/docs/classic/paypal-payments-standard/integration-guide/donation_buttons/).  This would work for Safari on a computer and would also trigger a mobile optimized flow when accessed on a mobile device.
