### ISSUE TITLE
CreditCard Payment Billing Address required

### ISSUE THREAD

**Issue by dpaluy** [paypal/PayPal-iOS-SDK#252]
What is the correct way to request billing address from client?
I would expect, the SDK will has a form to enter required info, after entering card details.

**Comment by dgoldman-ebay** [comment]
@dpaluy the SDK does not include the feature of collecting a billing address. (That would actually be a complicated task, since our SDK must support so many different countries.)

What is your situation, where this would be a helpful feature?

**Comment by dpaluy** [comment]
I'd like my user to be able to pay with PayPal or with CreditCard (ExpressCheckout). The PayPal flow is simple and clear.
When I allow a user to select a CreditCard payment, she scans her credit card (card.io), but the payment fails due to missing billing address.
Asking for Billing Address before selecting the payment method is wrong (because she may select Pay with PayPal, and this data is irrelevant).
What is the correct way to request this data and submit it to PayPal?

**Comment by ppmtscory** [comment]
@dpaluy As @dgoldman-ebay stated, there is no way to add a billing address to a credit card payment from the mSDK.  We will discuss this as a feature request and take it into consideration for future releases.

**Comment by dpaluy** [comment]
@ppmtscory Thanks

**Comment by tomwhipple** [comment]
The current recommendation for credit care acceptance is to use [Braintree](https://braintreepayments.com). It is unlikely that this feature will be added to this SDK directly.
