### ISSUE TITLE
Currency code $ sign.

### ISSUE THREAD

**Issue by keenan16** [paypal/PayPal-iOS-SDK#255]
Hi, We had an issue with the currency symbol with our client. Because if you setup curreny code to HKD. The display on the Paypal payment view on Android HK$. But on iOS it is only a $ sign. So how can i do the same display on iOS. 

![10965182_873374326060722_266899142_o](https://cloud.githubusercontent.com/assets/3540660/6074110/904255a6-adf2-11e4-9bcd-b94e5adc0245.jpg)

![img_0055](https://cloud.githubusercontent.com/assets/3540660/6074176/d017488e-adf3-11e4-8e03-cdd9a2ee384c.PNG)

**Comment by dgoldman-ebay** [comment]
@keenan16 the iOS version of the SDK displays currency codes only when more than one currency is involved.

For example, if the customer has a PayPal account with a balance in HKD, and the current payment is also stated in HKD, then only `$` will appear.

On the other hand, if the customer's PayPal account also has a credit card registered, and that credit card defaults to USD, then each amount (the current HKD payment amount, the PayPal HKD balance, and the USD credit card) will include the appropriate currency code.

Our thinking is that, in the former of the above two cases, the customer would be accustomed to interpreting `$` as HKD, and so no screen space need be given over to (possibly confusing) currency codes. Especially as the customer will presumably already know the currency of the current payment prior to arriving at the above screen.

We certainly could modify this algorithm, if persuaded.

**Comment by dgoldman-ebay** [comment]
@keenan16 I hope that the above explanation made sense to you. Do you have any further feedback for us, or is the current algorithm acceptable?

**Comment by keenan16** [comment]
@dgoldman-ebay Yap, Thank you for supporting us. cheers

**Comment by dgoldman-ebay** [comment]
Thanks for the feedback, @keenan16! Let us know if anything else comes up in the future.
