### ISSUE TITLE
INTERNAL_SERVICE_ERROR when trying to make a purchase in the sandbox

### ISSUE THREAD

**Issue by datinc** [paypal/PayPal-iOS-SDK#256]
When trying to make a purchase in the sandbox I get the following error:

PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 93e5ae17ae16c [sandbox, PayPal iOS SDK 2.8.3]

**Comment by mattjacunski** [comment]
@datinc - There was a service temporarily down on sandbox.  I tested to verify that it has been restarted.

**Comment by datinc** [comment]
I am still getting the error.
PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 6bec5a700ab9d [sandbox, PayPal iOS SDK 2.8.3]

**Comment by datinc** [comment]
It ended up being that the test credit card 411111... was causing the issue.
