### ISSUE TITLE
Brazilian accounts can not pay with the IOS SDK 

### ISSUE THREAD

**Issue by tony0121** [paypal/PayPal-iOS-SDK#257]
Hi team,
Recently I use 2 brazilian sandbox accounts(1 for Biz and another for person) for testing. However, when we try to check out (in sandbox mode), we always have the following error :
"PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: 1a3143b608c96 [sandbox, PayPal iOS SDK 2.8.3]"
But other personal account (non Brazil) is OK. Is there any restriction in place preventing Brazilian accounts to make mobile payments ?

**Comment by ppmtscory** [comment]
@tony0121 I'm thinking that there was a glitch with the TAX information for the buyer account when it was created.  Can you create a new buyer account on developer.paypal.com to try again?  I just created one myself, used your client ID, and was able to successfully send you a couple payments.

**Comment by tony0121** [comment]
Is this account	(brazilianbuyer@test.com) a Brazilian account? I think this is a US account. And it is OK when using a non Brazilian account to checkout. Problem is we can not complete the payment between   a Brazilian personal account and a Brazilian business account. Can you check again? 
For person: bl-per1@ebay.com 11111111
For business: bl-biz1@ebay.com 11111111
Both are Brazilian sandbox account, you can have a try. Thanks.

**Comment by ppmtscory** [comment]
@tony0121 AH, you are right.  I must've clicked something wrong and it went to a US account.  Let me play with this a little further and I'll let you know what I find out.

**Comment by ppmtscory** [comment]
@tony0121 I was able to reproduce this and so I've filed an issue with our internal engineers to look into a fix.  I will update you here once I have any new information.

**Comment by tony0121** [comment]
Sure, I'm looking forward to hearing your good news.

**Comment by techilm** [comment]
Hello, 

Thank you for looking into this issue. We are also affected when trying (in sandbox mode) to make payments in BRL.

Both the buyer's and seller's accounts are Brazilian ones, with BRL as main currency, but the payment always fails with the same error: 
**PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: 69b0aaefce332 [sandbox, PayPal iOS SDK 2.8.3]**

As a side note, we noticed that payments work with non Brazilian buyer accounts (and their main currency is not BRL), even though the PayPal SDK mentions that BRL payments are only available between two BRL accounts...

(The debug id mentioned above is the last one we encountered).

Kind Regards.

**Comment by ppmtscory** [comment]
@techilm I am still discussing this issue with our internal teams.  To address your BRL payment question, the docs are referring to the payment currency.  BRL as a currency for a payment is an in-country currency only.  This means that if you intend to use Brazilian Real, it needs to be a BR to BR account payment. Please let me know if I misunderstood your question.

**Comment by techilm** [comment]
Sorry for the delay.

Yes, in my side note I was referring to the fact that in sandbox mode, I was able to perform a BRL payment between a non-BR account (buyer) and a BR account (seller). But it was just a side note, my main issue being failing on BR and BR in BRL.

**Comment by ppmtscory** [comment]
@tony0121 @techilm This issue should now be resolved.  I, just now, completed multiple successful payments between BR accounts using BRL currency.  I appreciate your patience while we looked into this.  This issue will now be closed.
