### ISSUE TITLE
How to use a customised View Controller like what Uber app did?

### ISSUE THREAD

**Issue by vkedwardli** [paypal/PayPal-iOS-SDK#258]

**Comment by dgoldman-ebay** [comment]
@vkedwardli could you explain specifically what customizations you are trying to implement?

**Comment by vkedwardli** [comment]
![Image of Yaktocat](http://heavyeditorial.files.wordpress.com/2014/07/how-to-use-uber-app-payment.jpg?quality=65&strip=all&w=780)

Pressing "scan your card" will fire up a PayPal branded card.io scanning interface, and all the view controllers of Uber are heavily customised like this demo video: https://www.youtube.com/watch?v=NwYMdSSojtQ

Is it provided by the PayPal-iOS-SDK? Or are they still using Braintree but since it is acquired by PayPal which makes the card.io scanner showing a PayPal logo?

sorry any confusion that may have caused...

**Comment by dgoldman-ebay** [comment]
Thanks for the explanation, @vkedwardli.

As far as the heavily customized view controllers, that's all Uber's doing. One way that you can accomplish similar customizations would be via the [`UIAppearance` protocol](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIAppearance_Protocol/index.html).

I believe that for credit card scanning, Uber is directly using our [card.io SDK](https://github.com/card-io/card.io-iOS-SDK). By default, card.io shows a `PayPal` logo on its scanning screen.
