### ISSUE TITLE
Chained Payment functionality is Available ?

### ISSUE THREAD

**Issue by rushabh0999** [paypal/PayPal-iOS-SDK#259]
Hello Team,

Can you know me Chained Payment Functionality is support in latest Paypal -iOS-SDK .?

Regards,
Rushabh

**Comment by dgoldman-ebay** [comment]
@rushabh0999 unfortunately, chained payments are not yet supported by the REST APIs on which the PayPal iOS SDK depends. We do not have an estimated date for this feature to be added.
