### ISSUE TITLE
Terminating app due to uncaught exception 'PayPalIncompleteIntegration'

### ISSUE THREAD

**Issue by NoahBarsky** [paypal/PayPal-iOS-SDK#261]
Hi, i am getting a strange error :
Terminating app due to uncaught exception 'PayPalIncompleteIntegration', reason: 'preconnectWithEnvironment was called without a preceding call to initializeWithClientIdsForEnvironments:'

can you please help

**Comment by dgoldman-ebay** [comment]
@NoahBarsky the message is actually fairly self-explanatory.

See step 1 in our [integration instructions](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/single_payment.md#sample-code).

You can also refer to our [Sample Application](https://github.com/paypal/PayPal-iOS-SDK/blob/master/SampleApp/PayPal-iOS-SDK-Sample-App/ZZAppDelegate.m) code.

**Comment by NoahBarsky** [comment]
ok thanks

**Comment by NoahBarsky** [comment]
I am programming with swift, is there a way to do this?

**Comment by dgoldman-ebay** [comment]
https://github.com/paypal/PayPal-iOS-SDK/tree/master/SampleApp-Swift
