### ISSUE TITLE
Enabling customers to delete consent for future payments

### ISSUE THREAD

**Issue by reinholdbentele** [paypal/PayPal-iOS-SDK#262]
Quote from the developers guide [Make future payments](https://developer.paypal.com/docs/integration/mobile/make-future-payment/):
> Enabling customers to delete consent
> Just as your app will get user consent for future payments, your app must enable customers to delete consent for future payments.

Is this supported by the Mobile SDK? Of course, I can remove the refresh token in my backend but the consent is still there in the customer's PayPal profile.

I could not find a way to really delete the consent in the customer's PayPal profile. Can you help me to find the right operation?

**Comment by romk1n** [comment]
> Is this supported by the Mobile SDK? Of course, I can remove the refresh token in my backend but the consent is still there in the customer's PayPal profile.

That's correct. Only customer can fully revoke the consent. Removing `refresh token` should be sufficient action for the developer.

> I could not find a way to really delete the consent in the customer's PayPal profile. Can you help me to find the right operation?

As per document you have mentioned 
> To delete consent for future payments for an app, log into https://www.paypal.com/. Under My Account, click Profile. Then click My Settings, and in the Log In with PayPal row, click Change. Remove the app from the list.

When customer clicks on `See additional terms` link on the Consent Agreement page He also given the same instructions as per screenshot.

![screen shot 2015-03-12 at 10 26 58 am](https://cloud.githubusercontent.com/assets/1556000/6623803/88c40412-c8a2-11e4-9feb-1357f359c4db.png)


Hope it helps!
