### ISSUE TITLE
"Trying to pay, but too many payment methods!"

### ISSUE THREAD

**Issue by FotoboxLab** [paypal/PayPal-iOS-SDK#263]
Hi All,

We've run into a problem over the last 18 or so hours with our production app throwing up the following error on **every** payment that is trying to be authorised. 

    PayPal SDK: Trying to pay, but too many payment methods. Should not be possible to get here!

This is also affecting the Android version of the SDK, but I can't test that to see if it is the same error or if it is just coincidence. 
iOS SDK Version being used is 2.8.0, Android version is 2.0.2 (we should update that...)
Note our app has been live for at least a year with this SDK.

We have communicated with PayPal MTS, who are investigating under reference 150313-000113.
I'm communicating this here as it seems likely to be an SDK problem which someone else may run into in future.

Thanks,
Michael

**Comment by dgoldman-ebay** [comment]
@FotoboxLab that's very concerning, indeed!

Can you reproduce this in our Sample App?

Can you provide a recipe for steps to reproduce this, starting with the presentation of the PayPal iOS SDK screen?

**Comment by FotoboxLab** [comment]
@dgoldman-ebay 

I have investigated in the Sample App, placing our live ID (this is only broken in live, sandbox works fine). 
Interestingly I'm now getting a different error at the same stage, but the ramifications are the same: we can't process any live payments.

The error appears at different points depending on payment method:
### Card Payments
This is what happens when I tap `Charge Card`:
    
    2015-03-13 20:14:02.258 PayPal-iOS-SDK-Sample-App[49231:1925754] PayPal SDK: Request has failed with error: REQUIRED_SCOPE_MISSING - System error. Please try again later. (403) | PayPal Debug-ID: 7a2c2ded11778 [live, PayPal iOS SDK 2.8.5]

I have also taken a screenshot of the visual error. Note that I changed the amounts. Obviously if this payment succeeded I didn't want a live payment of 200 USD being charged to my personal card! 
[Screenshot](https://www.dropbox.com/s/xdplsvdq1mns9se/Screenshot%202015-03-13%2020.14.13.png?dl=0)

### PayPal Payments
I log in with my PayPal details, follow the 2 factor authentication flow, but when authenticating the 6 digit 2FA code, it simply 'shakes' as if I typed it wrong. The console outputs:

    2015-03-13 20:25:22.719 PayPal-iOS-SDK-Sample-App[49273:1932192] PayPal SDK: Request has failed with error: REQUIRED_SCOPE_MISSING - System error. Please try again later. (403) | PayPal Debug-ID: 03147d6f64088 [live, PayPal iOS SDK 2.8.5]

I'm awaiting some log files from customer devices to corroborate the errors, but in testing this is the same error we are getting on a number of staff devices.

Thank you for your help.

**Comment by tarekf** [comment]
We also are facing the same issue. No payments go through on both Android and iOS and fail with a generic "System error. Please try again later" dialog.

The logs indicate the same issue:

  W/paypal.sdk(15299): ae SN:19 PayPal Debug-ID: 314e95a17ffa9 [live, 2.8.6;release]

  E/paypal.sdk(15299): request failure with http statusCode:403,exception:org.apache.http.client.HttpResponseException: Forbidden

  E/paypal.sdk(15299): request failed with server response:{"name":"REQUIRED_SCOPE_MISSING","message":"Access token does not have required scope","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#REQUIRED_SCOPE_MISSING","debug_id":"314e95a17ffa9"}

  E/paypal.sdk(15299): 

  E/paypal.sdk(15299): REQUIRED_SCOPE_MISSING

This is a very urgent issue as we are no longer able to process any PayPal payments.

**Comment by dgoldman-ebay** [comment]
Urgency noted!

Several emails and phone calls are happening within PayPal, as I type this.

We'll report back as soon as we've figured out what's going on.

**Comment by tomwhipple** [comment]
We believe that this incident has been resolved. Should it re-occur, please don't hesitate to re-open and/or call [merchant technical support](https://www.paypal.com/mts).

**Comment by tomwhipple** [comment]
Spoke too soon. :( Will update when we know more.

**Comment by tomwhipple** [comment]
We've confirmed with the authentication team that the issue has been resolved. Monitoring shows a corresponding decline in the number of 403 responses. We will continue to observe.
