### ISSUE TITLE
 How to open scan camera screen using Paypal SDK - Solved

### ISSUE THREAD

**Issue by dharmikvyas** [paypal/PayPal-iOS-SDK#264]
Hello,
I have used card io lib, that works fine. Now I need to use Paypal in my app.
SO I have to remove card io lib.
Is there any method to open camera screen to scan, like card io does, Using Paypal?

*****Edited*****
I want to scan card when User clicks button in my ViewController Screen/Custom screen.
It currently included in Paypal Screen.

Like I want to scan card, get that details into app, pay using another banking gateways (local)

**Comment by dharmikvyas** [comment]
It solved now.. Card io files was not included..

https://github.com/paypal/PayPal-iOS-SDK/tree/master/PayPalMobile

Thank you @dgoldman-ebay Sir.

**Comment by dgoldman-ebay** [comment]
Glad you worked it out, @dharmikvyas!
