### ISSUE TITLE
Trying to intgerate PayPal library into swift project

### ISSUE THREAD

**Issue by goudarziha** [paypal/PayPal-iOS-SDK#266]
Hello,

I am having a huge issue of trying to integrate the SDK into an iOS application built in swift. I tried both using Cocoapods and manually putting the libraries into the project, but I keep getting a similar error of 

ld: library not found for -lPayPalMobile
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have tried changing and fixing the library search paths to remedy this, but with no luck at all. I have only found one other person who had a similar problem and had suggested I start the project over in Obj-C. Do you have any insight as to what is going on with the project, or any other ideas I could try and fix this?

**Comment by romk1n** [comment]
@goudarziha did you have a look at our swift example first ? https://github.com/paypal/PayPal-iOS-SDK/tree/master/SampleApp-Swift

**Comment by goudarziha** [comment]
@romk1n yes I have tried to imitate this example as closely as I could in order to get the paypal SDK running. The problem I am running into is that when I push the libraries into the project, it doesn't recognize the library is in there.

**Comment by romk1n** [comment]
@goudarziha can you submit a few screenshots where the library is present in your project from the file management also your `Build Phases`

**Comment by goudarziha** [comment]
![screen shot 2015-04-13 at 3 24 05 pm](https://cloud.githubusercontent.com/assets/5420796/7123598/4669bed2-e1f1-11e4-8708-98b12a1a2a09.png)

![screen shot 2015-04-13 at 3 24 41 pm](https://cloud.githubusercontent.com/assets/5420796/7123601/4d22c85e-e1f1-11e4-855c-b46288e4e45e.png)

**Comment by romk1n** [comment]
@goudarziha i don't see `libPayPalMobile.a` in the list

**Comment by goudarziha** [comment]
@romk1n Thanks, you were absolutely right, I was missing that file in the file manager, but I have tried putting the file within that file, but it still isn't working. Would you happen to have any other ideas?

**Comment by romk1n** [comment]
@goudarziha if you now click on the `.a` file and bring the details (Utilities/Properties) tab check if `Target Membership` of your executable is actually ticked ?

**Comment by goudarziha** [comment]
@romk1n yes the target membership wasn't ticked, but I did the tick and still doesn't build.

**Comment by romk1n** [comment]
@goudarziha hmm, try really cleaning your build. Press `Product` in menu + Option Key, you should see `Clean Build Folder` rather than normal `Clean` try doing that.

**Comment by goudarziha** [comment]
@romk1n unfortunately that didn't help either, but I greatly appreciate all your help. This gives me an excuse to write in obj c anyway.

**Comment by dgoldman-ebay** [comment]
@goudarziha if you haven't yet deleted your Swift project...

If you bring up the Build Settings for the `Pods` project, you should see a target named something like `Pods-CinteTexWireless-PayPal-iOS-SDK`. In the Build Settings for that target, near the bottom there should be a `User-Defined` macro with a name like `PODS_CINTEXWIRELESS_PAYPAL_IOS_SDK_LIBRARY_SEARCH_PATHS`. That one should contain a valid path to the `PayPalMobile` directory which contains `libPayPalMobile.a`.

Is that the case? Or does `PODS_CINTEXWIRELESS_PAYPAL_IOS_SDK_LIBRARY_SEARCH_PATHS` need correcting?

**Comment by goudarziha** [comment]
@dgoldman-ebay it does contain the valid path to the libPayPalMobile.a file, unfortunately.

**Comment by dgoldman-ebay** [comment]
Alas. The mystery continues!

**Comment by anilsanto** [comment]
Has anyone found a solution for this?
I'm using 
Xcode 6.1.1
PayPal-iOS-SDK 2.9.0

"PODS_PAYPAL_IOS_SDK_LIBRARY_SEARCH_PATHS. That one should contain a valid path to the PayPalMobile"

it contains PayPalMobile but the directory in Pods->PayPal-iOS-SDK does not contain the file libPayPalMobile.a

**Comment by dgoldman-ebay** [comment]
@anilsanto have you already tried running `pod update`?

**Comment by anilsanto** [comment]
@dgoldman-ebay yes i already tried updating all the pods.

   # Uncomment this line to define a global platform for your project
   platform :ios, '6.0'

   target 'GroupBuy' do
   pod 'libPusher', '~> 1.5'
   pod 'PKRevealController'
   pod 'PayPal-iOS-SDK','2.9.0'
   end
   target 'GroupBuyTests' do
  end

These are the pods i'm using currently.

**Comment by dgoldman-ebay** [comment]
@anilsanto any luck in figuring out your CocoaPods problem yet?

If nothing else has worked, you'd be welcome to send me a copy of your project (with complete confidentiality, of course) and I'd be happy to take a look.

**Comment by anirudhsmarttechnica** [comment]
any one can help for integrate paypal to ios app
