### ISSUE TITLE
CardIO 64-bit architecture issues

### ISSUE THREAD

**Issue by pierceboggan** [paypal/PayPal-iOS-SDK#267]
Hi,

I'm attempting to use the PayPal iOS SDK. I've created a [Xamarin bindings project](https://developer.xamarin.com/guides/ios/advanced_topics/binding_objective-c/) that works great for the ArmV7, ArmV7s, and i386 architectures. However, when I attempt to build for Arm64, I'm running into issues that seem to originate with the libCardIO.a file. Is there any way you could update libPayPalMobile.a to include an updated libCardIO.a file with support for 64-bit architectures?

Thanks!

Build Log:
		Undefined symbols for architecture arm64:
		  "_glUniform1i", referenced from:
		      ___53-[CardIOGPUGaussianBlurFilter processUIImage:toSize:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glCreateProgram", referenced from:
		      +[CardIOGPURenderer prepareProgram:vertexShader:fragmentShader:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glLinkProgram", referenced from:
		      +[CardIOGPURenderer prepareProgram:vertexShader:fragmentShader:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_SecTrustEvaluate", referenced from:
		      +[PPURLProtocol doSSLPinning:] in libPayPalMobile.a(PPURLProtocol.o)
		  "_glValidateProgram", referenced from:
		      +[CardIOGPURenderer prepareProgram:vertexShader:fragmentShader:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glGetProgramiv", referenced from:
		      +[CardIOGPURenderer prepareProgram:vertexShader:fragmentShader:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glGetProgramInfoLog", referenced from:
		      +[CardIOGPURenderer prepareProgram:vertexShader:fragmentShader:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glCreateShader", referenced from:
		      +[CardIOGPURenderer compileShader:type:source:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glShaderSource", referenced from:
		      +[CardIOGPURenderer compileShader:type:source:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glCompileShader", referenced from:
		      +[CardIOGPURenderer compileShader:type:source:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glGetShaderiv", referenced from:
		      +[CardIOGPURenderer compileShader:type:source:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_SecTrustGetCertificateAtIndex", referenced from:
		      +[PPURLProtocol doSSLPinning:] in libPayPalMobile.a(PPURLProtocol.o)
		  "_glAttachShader", referenced from:
		      +[CardIOGPURenderer prepareProgram:vertexShader:fragmentShader:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glGetShaderInfoLog", referenced from:
		      +[CardIOGPURenderer compileShader:type:source:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glGetError", referenced from:
		      ___37-[CardIOGPURenderer captureIplImage:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glReadPixels", referenced from:
		      ___42-[CardIOGPURenderer captureUIImageOfSize:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		      ___37-[CardIOGPURenderer captureIplImage:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glTexImage2D", referenced from:
		      ___44-[CardIOGPURenderer setInputTextureUIImage:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		      ___45-[CardIOGPURenderer setInputTextureIplImage:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_SecCertificateCopyData", referenced from:
		      +[PPURLProtocol doSSLPinning:] in libPayPalMobile.a(PPURLProtocol.o)
		  "_glVertexAttribPointer", referenced from:
		      ___34-[CardIOGPURenderer renderToSize:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glEnable", referenced from:
		      ___34-[CardIOGPURenderer prepareForUse]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glTexParameteri", referenced from:
		      ___35-[CardIOGPURenderer prepareTexture]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_kSecAttrAccessible", referenced from:
		      +[PPSimpleKeychain setData:forKey:] in libPayPalMobile.a(PPSimpleKeychain.o)
		  "_glRenderbufferStorage", referenced from:
		      ___28-[CardIOGPURenderer setupGL]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glClearColor", referenced from:
		      ___34-[CardIOGPURenderer prepareForUse]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_kSecClass", referenced from:
		      -[PPRiskDeviceData getKeychainQuery] in libPayPalMobile.a(PPRiskDeviceData.o)
		      +[PPSimpleKeychain setData:forKey:] in libPayPalMobile.a(PPSimpleKeychain.o)
		      +[PPSimpleKeychain dataForKey:] in libPayPalMobile.a(PPSimpleKeychain.o)
		  "_glGetAttribLocation", referenced from:
		      ___73-[CardIOGPURenderer compileProgramWithVertexShaderSrc:fragmentShaderSrc:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glUseProgram", referenced from:
		      ___73-[CardIOGPURenderer compileProgramWithVertexShaderSrc:fragmentShaderSrc:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_CVPixelBufferUnlockBaseAddress", referenced from:
		      -[CardIOVideoFrame process] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glGenFramebuffers", referenced from:
		      ___28-[CardIOGPURenderer setupGL]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glActiveTexture", referenced from:
		      ___34-[CardIOGPURenderer renderToSize:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_kSecAttrService", referenced from:
		      -[PPRiskDeviceData getKeychainQuery] in libPayPalMobile.a(PPRiskDeviceData.o)
		      +[PPSimpleKeychain setData:forKey:] in libPayPalMobile.a(PPSimpleKeychain.o)
		      +[PPSimpleKeychain dataForKey:] in libPayPalMobile.a(PPSimpleKeychain.o)
		  "_glEnableVertexAttribArray", referenced from:
		      ___73-[CardIOGPURenderer compileProgramWithVertexShaderSrc:fragmentShaderSrc:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_kSecAttrAccessibleWhenUnlockedThisDeviceOnly", referenced from:
		      +[PPSimpleKeychain setData:forKey:] in libPayPalMobile.a(PPSimpleKeychain.o)
		  "_glBindTexture", referenced from:
		      ___35-[CardIOGPURenderer prepareTexture]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		      ___34-[CardIOGPURenderer renderToSize:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glBindFramebuffer", referenced from:
		      ___28-[CardIOGPURenderer setupGL]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glGenRenderbuffers", referenced from:
		      ___28-[CardIOGPURenderer setupGL]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glBindRenderbuffer", referenced from:
		      ___28-[CardIOGPURenderer setupGL]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glFramebufferRenderbuffer", referenced from:
		      ___28-[CardIOGPURenderer setupGL]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glBufferData", referenced from:
		      ___28-[CardIOGPURenderer setupGL]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glUniformMatrix4fv", referenced from:
		      ___41-[CardIOGPUTransformFilter initWithSize:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		      ___46-[CardIOGPUTransformFilter setPerspectiveMat:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		      ___44-[CardIOGPUGaussianBlurFilter initWithSize:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glFlush", referenced from:
		      -[CardIOGPURenderer withContextDo:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		      ___42-[CardIOGPURenderer captureUIImageOfSize:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		      ___37-[CardIOGPURenderer captureIplImage:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glViewport", referenced from:
		      ___34-[CardIOGPURenderer renderToSize:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_kCVPixelBufferPixelFormatTypeKey", referenced from:
		      -[CardIOVideoStream addInputAndOutput] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_SecTrustGetCertificateCount", referenced from:
		      +[PPURLProtocol doSSLPinning:] in libPayPalMobile.a(PPURLProtocol.o)
		  "_CVPixelBufferGetBaseAddressOfPlane", referenced from:
		      +[CardIOIplImage imageFromYCbCrBuffer:plane:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_kSecAttrSynchronizable", referenced from:
		      -[PPRiskDeviceData getCloudIdentifier] in libPayPalMobile.a(PPRiskDeviceData.o)
		  "_CVPixelBufferGetBytesPerRowOfPlane", referenced from:
		      +[CardIOIplImage imageFromYCbCrBuffer:plane:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_CVPixelBufferLockBaseAddress", referenced from:
		      -[CardIOVideoFrame process] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_SecItemUpdate", referenced from:
		      +[PPSimpleKeychain setData:forKey:] in libPayPalMobile.a(PPSimpleKeychain.o)
		  "_glGetUniformLocation", referenced from:
		      ___73-[CardIOGPURenderer compileProgramWithVertexShaderSrc:fragmentShaderSrc:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		      ___34-[CardIOGPURenderer uniformIndex:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_CVPixelBufferGetWidthOfPlane", referenced from:
		      +[CardIOIplImage imageFromYCbCrBuffer:plane:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_kSecMatchLimit", referenced from:
		      -[PPRiskDeviceData getCloudIdentifier] in libPayPalMobile.a(PPRiskDeviceData.o)
		  "_CVPixelBufferGetHeightOfPlane", referenced from:
		      +[CardIOIplImage imageFromYCbCrBuffer:plane:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_kSecReturnData", referenced from:
		      -[PPRiskDeviceData getCloudIdentifier] in libPayPalMobile.a(PPRiskDeviceData.o)
		      +[PPSimpleKeychain dataForKey:] in libPayPalMobile.a(PPSimpleKeychain.o)
		  "_glDrawElements", referenced from:
		      ___34-[CardIOGPURenderer renderToSize:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_OBJC_CLASS_$_EAGLContext", referenced from:
		      objc-class-ref in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glGenTextures", referenced from:
		      ___28-[CardIOGPURenderer setupGL]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_kSecMatchLimitOne", referenced from:
		      -[PPRiskDeviceData getCloudIdentifier] in libPayPalMobile.a(PPRiskDeviceData.o)
		  "_glGenBuffers", referenced from:
		      ___28-[CardIOGPURenderer setupGL]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_kSecAttrSynchronizableAny", referenced from:
		      -[PPRiskDeviceData getCloudIdentifier] in libPayPalMobile.a(PPRiskDeviceData.o)
		  "_SecItemCopyMatching", referenced from:
		      -[PPRiskDeviceData getCloudIdentifier] in libPayPalMobile.a(PPRiskDeviceData.o)
		      +[PPSimpleKeychain setData:forKey:] in libPayPalMobile.a(PPSimpleKeychain.o)
		      +[PPSimpleKeychain dataForKey:] in libPayPalMobile.a(PPSimpleKeychain.o)
		  "_OBJC_CLASS_$_PayPalFields", referenced from:
		      objc-class-ref in registrar.arm64.o
		  "_SecItemDelete", referenced from:
		      -[PPRiskDeviceData getCloudIdentifier] in libPayPalMobile.a(PPRiskDeviceData.o)
		      +[PPSimpleKeychain setData:forKey:] in libPayPalMobile.a(PPSimpleKeychain.o)
		  "_SecItemAdd", referenced from:
		      -[PPRiskDeviceData getCloudIdentifier] in libPayPalMobile.a(PPRiskDeviceData.o)
		      +[PPSimpleKeychain setData:forKey:] in libPayPalMobile.a(PPSimpleKeychain.o)
		  "_kSecValueData", referenced from:
		      -[PPRiskDeviceData getCloudIdentifier] in libPayPalMobile.a(PPRiskDeviceData.o)
		      +[PPSimpleKeychain setData:forKey:] in libPayPalMobile.a(PPSimpleKeychain.o)
		  "_kSecAttrAccount", referenced from:
		      -[PPRiskDeviceData getKeychainQuery] in libPayPalMobile.a(PPRiskDeviceData.o)
		      +[PPSimpleKeychain setData:forKey:] in libPayPalMobile.a(PPSimpleKeychain.o)
		      +[PPSimpleKeychain dataForKey:] in libPayPalMobile.a(PPSimpleKeychain.o)
		  "_glFinish", referenced from:
		      ___27-[CardIOGPURenderer finish]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glClear", referenced from:
		      ___34-[CardIOGPURenderer prepareForUse]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_glBindBuffer", referenced from:
		      ___28-[CardIOGPURenderer setupGL]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		  "_kSecClassGenericPassword", referenced from:
		      -[PPRiskDeviceData getKeychainQuery] in libPayPalMobile.a(PPRiskDeviceData.o)
		      +[PPSimpleKeychain setData:forKey:] in libPayPalMobile.a(PPSimpleKeychain.o)
		      +[PPSimpleKeychain dataForKey:] in libPayPalMobile.a(PPSimpleKeychain.o)
		  "_glUniform1f", referenced from:
		      ___34-[CardIOGPURenderer renderToSize:]_block_invoke in libPayPalMobile.a(libCardIO.a-arm64-master.o)
		ld: symbol(s) not found for architecture arm64
		clang: error: linker command failed with exit code 1 (use -v to see invocation)
		
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glUniform1i. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glCreateProgram. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glLinkProgram. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _SecTrustEvaluate. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glValidateProgram. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glGetProgramiv. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glGetProgramInfoLog. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glCreateShader. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glShaderSource. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glCompileShader. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glGetShaderiv. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _SecTrustGetCertificateAtIndex. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glAttachShader. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glGetShaderInfoLog. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glGetError. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glReadPixels. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glTexImage2D. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _SecCertificateCopyData. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glVertexAttribPointer. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glEnable. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glTexParameteri. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _kSecAttrAccessible. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glRenderbufferStorage. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glClearColor. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _kSecClass. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glGetAttribLocation. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glUseProgram. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _CVPixelBufferUnlockBaseAddress. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glGenFramebuffers. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glActiveTexture. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _kSecAttrService. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glEnableVertexAttribArray. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _kSecAttrAccessibleWhenUnlockedThisDeviceOnly. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glBindTexture. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glBindFramebuffer. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glGenRenderbuffers. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glBindRenderbuffer. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glFramebufferRenderbuffer. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glBufferData. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glUniformMatrix4fv. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glFlush. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glViewport. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _kCVPixelBufferPixelFormatTypeKey. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _SecTrustGetCertificateCount. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _CVPixelBufferGetBaseAddressOfPlane. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _kSecAttrSynchronizable. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _CVPixelBufferGetBytesPerRowOfPlane. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _CVPixelBufferLockBaseAddress. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _SecItemUpdate. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glGetUniformLocation. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _CVPixelBufferGetWidthOfPlane. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _kSecMatchLimit. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _CVPixelBufferGetHeightOfPlane. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _kSecReturnData. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glDrawElements. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5211: Native linking failed, undefined Objective-C class: _OBJC_CLASS_$_EAGLContext. If '_OBJC_CLASS_$_EAGLContext' is a protocol from a third-party binding, please check that it has the [Protocol] attribute in its api definition file, otherwise verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glGenTextures. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _kSecMatchLimitOne. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glGenBuffers. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _kSecAttrSynchronizableAny. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _SecItemCopyMatching. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5211: Native linking failed, undefined Objective-C class: _OBJC_CLASS_$_PayPalFields. If '_OBJC_CLASS_$_PayPalFields' is a protocol from a third-party binding, please check that it has the [Protocol] attribute in its api definition file, otherwise verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _SecItemDelete. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _SecItemAdd. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _kSecValueData. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _kSecAttrAccount. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glFinish. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glClear. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glBindBuffer. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _kSecClassGenericPassword. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glUniform1f. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCHTASK: error MT5202: Native linking failed. Please review the build log.
	Task "MTouchTask" execution -- FAILED
	Done building target "_CompileToNative" in project "/Users/pierceboggan/Desktop/GitHub/WillysCycles/App/App.iOS/App.iOS.csproj".-- FAILED
	
Done building project "/Users/pierceboggan/Desktop/GitHub/WillysCycles/App/App.iOS/App.iOS.csproj".-- FAILED

Build FAILED.

Warnings:

/Users/pierceboggan/Desktop/GitHub/WillysCycles/App/App.iOS/App.iOS.csproj (Build) ->
/Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

	View Controllers/SearchViewController.cs(115,40): warning CS1998: Async block lacks `await' operator and will run synchronously
	Views/PhotoGalleryView.cs(16,15): warning CS0169: The private field `App.iOS.PhotoGalleryView.imageViewFour' is never used

Errors:

/Users/pierceboggan/Desktop/GitHub/WillysCycles/App/App.iOS/App.iOS.csproj (Build) ->
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets (_CompileToNative target) ->

	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glUniform1i. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glCreateProgram. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glLinkProgram. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _SecTrustEvaluate. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glValidateProgram. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glGetProgramiv. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glGetProgramInfoLog. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glCreateShader. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glShaderSource. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glCompileShader. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glGetShaderiv. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _SecTrustGetCertificateAtIndex. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glAttachShader. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glGetShaderInfoLog. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glGetError. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glReadPixels. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glTexImage2D. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _SecCertificateCopyData. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glVertexAttribPointer. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glEnable. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glTexParameteri. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _kSecAttrAccessible. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
	MTOUCHTASK: error MT5210: Native linking failed, undefined symbol: _glRenderbufferStorage. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.

**Comment by dgoldman-ebay** [comment]
@pierceboggan the `libCardIO.a` included within `libPayPalMobile.a` has included 64-bit support for quite some time now.

The first thing you should check is whether you have followed all of [these instructions](https://github.com/paypal/PayPal-iOS-SDK#if-you-dont-use-cocoapods-then), especially:

> In your project's **Build Settings** (in the `TARGETS` section, not the `PROJECTS` section):
- add `-lc++ -ObjC` to `Other Linker Flags`
- enable `Enable Modules (C and Objective-C)`
- enable `Link Frameworks Automatically`

If you have indeed enabled modules and automatic framework linking, and are still seeing these errors, then apparently you will need to manually add some additional libraries to your project. A complete list of the necessary frameworks is [here](https://github.com/card-io/card.io-iOS-SDK#if-you-dont-use-cocoapods-then).

**Comment by pierceboggan** [comment]
I added the necessary CardIO frameworks in, and it worked like a charm. Thanks!

**Comment by ferrakkem** [comment]
@dgoldman-ebay  you save my huge time ... thanks a lot ...For your this  comments

enable Enable Modules (C and Objective-C)
enable Link Frameworks Automatically
