### ISSUE TITLE
Can my application be rejected if I use this library?

### ISSUE THREAD

**Issue by jmartos89** [paypal/PayPal-iOS-SDK#268]
I will integrate this library so that users can add virtual money to your wallet in my application, this money will be able to switch between users or take them to a bank account.

This integration of the library supports Revision Guides App Store?

I've been reading several reviews and was not very clear at all.

Thank you very much.

**Comment by dgoldman-ebay** [comment]
@jmartos89 there are many, many apps in the App Store that use this library, without any complaint from Apple.

However, when reviewing your app, Apple will look at the entire app and what it does. We cannot advise you regarding Apple's review process.
