### ISSUE TITLE
Duplicate symbols with Version 2.10.0 and Xcode 6.2

### ISSUE THREAD

**Issue by dgoldman-ebay** [paypal/PayPal-iOS-SDK#269]
Version 2.10.0 of the PayPal iOS SDK was built with Xcode 6.3.

In our experiments, we have found that attempting to build our Sample App with Xcode 6.2 now produces strange linker errors (duplicate symbols, for several compiler-generated symbols), but only for the arm64 architecture.

If you run into this problem, then either:

* Upgrade to Xcode 6.3, or
* Stick with [version 2.9.0](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.9.0) for now.

Either way, please post your observations here. Perhaps we can figure out some additional details which would be helpful for Apple.

**Comment by dgoldman-ebay** [comment]
[Version 2.10.1](https://github.com/paypal/PayPal-iOS-SDK/releases) has now been released. We have built 2.10.1 using Xcode 6.2 to prevent the linker errors.

We are working with Apple to attempt to resolve this issue going forward.

**Comment by Goles** [comment]
@dgoldman-ebay Did you guys open a radar about this?
