### ISSUE TITLE
47 duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by subhashsanghani** [paypal/PayPal-iOS-SDK#270]
<addr>
Ld /Users/subhashsanghani/Library/Developer/Xcode/DerivedData/mathqu-bngippdesbyrpgbiiyvzucitryyg/Build/Intermediates/mathqu.build/Debug-iphoneos/mathqu.build/Objects-normal/arm64/mathqu normal arm64
    cd "/Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu"
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.2.sdk -L/Users/subhashsanghani/Library/Developer/Xcode/DerivedData/mathqu-bngippdesbyrpgbiiyvzucitryyg/Build/Products/Debug-iphoneos -L/Users/subhashsanghani/Desktop/vijay\ Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile -F/Users/subhashsanghani/Library/Developer/Xcode/DerivedData/mathqu-bngippdesbyrpgbiiyvzucitryyg/Build/Products/Debug-iphoneos -filelist /Users/subhashsanghani/Library/Developer/Xcode/DerivedData/mathqu-bngippdesbyrpgbiiyvzucitryyg/Build/Intermediates/mathqu.build/Debug-iphoneos/mathqu.build/Objects-normal/arm64/mathqu.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -lc++ -ObjC -fobjc-link-runtime -miphoneos-version-min=6.0 -lPayPalMobile -framework CoreLocation -framework Security -framework CoreVideo -framework CoreMedia -lxml2 -framework AVFoundation -framework MobileCoreServices -framework OpenGLES -framework AudioToolbox -lsqlite3 -licucore -framework CoreGraphics -framework Foundation -framework UIKit -framework ImageIO -framework SystemConfiguration -framework MessageUI -framework QuartzCore -framework MapKit -framework CoreFoundation -framework CFNetwork -Xlinker -dependency_info -Xlinker /Users/subhashsanghani/Library/Developer/Xcode/DerivedData/mathqu-bngippdesbyrpgbiiyvzucitryyg/Build/Intermediates/mathqu.build/Debug-iphoneos/mathqu.build/Objects-normal/arm64/mathqu_dependency_info.dat -o /Users/subhashsanghani/Library/Developer/Xcode/DerivedData/mathqu-bngippdesbyrpgbiiyvzucitryyg/Build/Intermediates/mathqu.build/Debug-iphoneos/mathqu.build/Objects-normal/arm64/mathqu

duplicate symbol l034 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PayPalPaymentViewController.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPPaymentMethodCell.o)
duplicate symbol l035 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PayPalPaymentViewController.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPPaymentMethodCell.o)
duplicate symbol l036 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FAViewController.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPPaymentMethodCell.o)
duplicate symbol l037 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FAViewController.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPPaymentMethodCell.o)
duplicate symbol l026 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPZebraUI.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPDeviceCheckViewController.o)
duplicate symbol l027 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPZebraUI.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPDeviceCheckViewController.o)
duplicate symbol l028 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPZebraUI.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPDeviceCheckViewController.o)
duplicate symbol l033 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPPaymentMethodCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPZebraUI.o)
duplicate symbol l034 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PayPalPaymentViewController.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPZebraUI.o)
duplicate symbol l035 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PayPalPaymentViewController.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPZebraUI.o)
duplicate symbol l036 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FAViewController.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPZebraUI.o)
duplicate symbol l034 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PayPalPaymentViewController.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPServiceRequest.o)
duplicate symbol l026 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPZebraUI.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPSelectPayMethodViewControllerIOS6.o)
duplicate symbol l027 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPZebraUI.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPSelectPayMethodViewControllerIOS6.o)
duplicate symbol l028 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPZebraUI.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPSelectPayMethodViewControllerIOS6.o)
duplicate symbol l029 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPZebraUI.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPSelectPayMethodViewControllerIOS6.o)
duplicate symbol l030 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPZebraUI.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPSelectPayMethodViewControllerIOS6.o)
duplicate symbol l031 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPZebraUI.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPSelectPayMethodViewControllerIOS6.o)
duplicate symbol l023 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPBaseViewController.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PayPalProfileSharingViewController.o)
duplicate symbol l016 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPPaymentAttributeSelectionCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FASMSTableViewCell.o)
duplicate symbol l017 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPPaymentAttributeSelectionCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FASMSTableViewCell.o)
duplicate symbol l099 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPAuthConsentViewController.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPZebraAnalyticsTracker.o)
duplicate symbol l016 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPPaymentAttributeSelectionCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FASecurityCodeTableViewCell.o)
duplicate symbol l017 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPPaymentAttributeSelectionCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FASecurityCodeTableViewCell.o)
duplicate symbol l018 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FASMSTableViewCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FASecurityCodeTableViewCell.o)
duplicate symbol l019 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FASMSTableViewCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FASecurityCodeTableViewCell.o)
duplicate symbol l020 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPAnalyticsTracker.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FASecurityCodeTableViewCell.o)
duplicate symbol l018 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FASMSTableViewCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPSelectPayMethodViewControllerIOS7.o)
duplicate symbol l019 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FASMSTableViewCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPSelectPayMethodViewControllerIOS7.o)
duplicate symbol l020 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPAnalyticsTracker.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPSelectPayMethodViewControllerIOS7.o)
duplicate symbol l010 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPCreditCardMethodCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FAHeaderTableViewCell.o)
duplicate symbol l011 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPCreditCardMethodCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FAHeaderTableViewCell.o)
duplicate symbol l022 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PayPalProfileSharingViewController.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PayPalFuturePaymentViewController.o)
duplicate symbol l035 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PayPalPaymentViewController.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(FPTIData.o)
duplicate symbol l036 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FAViewController.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(FPTIData.o)
duplicate symbol l033 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPPaymentMethodCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPMultipleFieldTableViewCell.o)
duplicate symbol l003 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPTableViewCellDefaults.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPViewShake.o)
duplicate symbol l004 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPTableViewCellDefaults.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPViewShake.o)
duplicate symbol l005 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPTableViewCellDefaults.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPViewShake.o)
duplicate symbol l030 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPZebraUI.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPHTML.o)
duplicate symbol l013 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FAHeaderTableViewCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPModalActivityIndicator.o)
duplicate symbol l014 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FASMSTableViewCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPModalActivityIndicator.o)
duplicate symbol l015 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FASMSTableViewCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPModalActivityIndicator.o)
duplicate symbol l016 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPPaymentAttributeSelectionCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPModalActivityIndicator.o)
duplicate symbol l017 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPPaymentAttributeSelectionCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPModalActivityIndicator.o)
duplicate symbol l018 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FASMSTableViewCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPModalActivityIndicator.o)
duplicate symbol l019 in:
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PP2FASMSTableViewCell.o)
    /Users/subhashsanghani/Desktop/vijay Work-New/MathQu/mathqu/mathqu/CommonFramwork/PayPalMobile/libPayPalMobile.a(PPModalActivityIndicator.o)
ld: 47 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
</addr>

(null): 47 duplicate symbols for architecture arm64

Its works fine when i run it with simulator... but when i am trying to build archive then i got this kind of errors......

Can you please help me i ready your issue https://github.com/paypal/PayPal-iOS-SDK/issues/76  but nothing solution

**Comment by romk1n** [comment]
Please check #269

**Comment by subhashsanghani** [comment]
Thanks you are a great.. solved it

**Comment by bingFly** [comment]
How do you solved it？I meet it too, but I don't know how to solve it. I make a staitc lib, add my project, then it appear.

**Comment by romk1n** [comment]
@bingFly use Xcode 6.3+

**Comment by marchbold** [comment]
Hi, I'm using Xcode 6.4 and still am experiencing this error?
I'm attempting to use the libPayPalMobile in a static library I'm creating.

**Comment by intelliot** [comment]
@marchbold Which version of the PayPal iOS SDK are you using? If you're not using the latest (2.11.1, released 2 days ago as of this writing), please give it a try. If the error persists, please open a `New issue` here on GitHub. Thanks!

**Comment by marchbold** [comment]
@intelliot Thanks I will try the latest version.

**Comment by marchbold** [comment]
@intelliot Unfortunately no difference, have logged a new issue
