### ISSUE TITLE
API suggestion

### ISSUE THREAD

**Issue by MacTrophy** [paypal/PayPal-iOS-SDK#271]
I suggest an enhancement to the PayPalPaymentDelegate methods. The success method specifies the PayPalPayment 
- (void)payPalPaymentViewController:(PayPalPaymentViewController *)paymentViewController
                 didCompletePayment:(PayPalPayment *)completedPayment;
but the cancel method doesn't
- (void)payPalPaymentDidCancel:(PayPalPaymentViewController *)paymentViewController;

It would help managing the cancellations if the payment that's cancelled would be sent back, or at least the "invoiceNumber". Something like this
- (void)payPalPaymentViewController:(PayPalPaymentViewController *)paymentViewController
                 didCancelPayment:(PayPalPayment *)completedPayment;

Thanks

**Comment by dgoldman-ebay** [comment]
@MacTrophy thanks for the suggestion!

Could you explain a bit more why this change would be helpful to you? After all, the `PayPalPayment` in this case is something that your app created and passed to the SDK, `invoiceNumber` and all.

In the case of a successfully completed payment, the SDK adds additional confirmation information to the `PayPalPayment` object. But for a canceled payment, it's the same object that your app sent into the SDK.

**Comment by MacTrophy** [comment]
In my case I must admit it would help because my application isn't the one with the best structure around (was my first iOS app) and in this application I loose the context of the PayPalPayment after triggering it. I will manage to store my PayPalPayment object or the value of invoiceNumber and to re-use it but my implementation would have been way easier with the object simply sent back to me.

I didn't mention this before since I am not over with my integration of the SDK, what I will say might not apply; Even if I wouldn't have caused myself this problem, I would still have liked to have this method (or another one) called in the event of errors, with more details stored in the PayPalPayment object. I could have stored this data on my servers and use it to troubleshoot potential problems, ie a wrong configuration when calling the SDK or any other case the user might report to me.

I will still manage to implement the SDK.

Not too sure I am explaining myself properly, please forgive if it's fuzzy, I'm not fully bilingual.

**Comment by dgoldman-ebay** [comment]
Thanks @MacTrophy, you have explained your concerns well.

> I would still have liked to have this method (or another one) called in the event of errors, with more details stored in the PayPalPayment object.

Actually, given the way that the PayPal iOS SDK works, no such details are possible.

If the user encounters an error while within the SDK -- e.g., bad login credentials, bad PayPal account setup, etc. -- then the SDK will display that error and the user will remain in the SDK. Control will return from the SDK to your app in only two cases: (1) successful completion of a payment, or (2) the user cancels the flow. So there will never be any error details to report back to your app.
