### ISSUE TITLE
Sign-up link cut off when presenting PayPalPaymentViewController modally on iPad

### ISSUE THREAD

**Issue by gingermcninja** [paypal/PayPal-iOS-SDK#272]
I'm presenting a PayPalPaymentViewController modally on an iPad in landscape mode and for some reason the Sign Up link is being cut off to the right - see the attached screen grab.

![paypal_bug](https://cloud.githubusercontent.com/assets/4534957/7296053/0b290286-e9b4-11e4-883c-7013ff8ae9bb.png)

**Comment by dgoldman-ebay** [comment]
Thanks, @gingermcninja! We'll get this fixed.

**Comment by dgoldman-ebay** [comment]
Fixed (last week) in [Version 2.10.2](https://github.com/paypal/PayPal-iOS-SDK/releases)

**Comment by ladylo50bear** [comment]
Stop this website
