### ISSUE TITLE
Corresponding to a complete example, server processing code examples where I can get get?

### ISSUE THREAD

**Issue by antypang** [paypal/PayPal-iOS-SDK#273]
IOS PayPal SDK of cool, very helpful to improve usability,  but the corresponding complete example, server processing code examples where I can get get?

**Comment by romk1n** [comment]
@antypang depending on the language of you choice you can see server sdks sources code and examples [here](https://developer.paypal.com/webapps/developer/docs/api/)

**Comment by antypang** [comment]
@romk1n , thank you for your response.
