### ISSUE TITLE
CVV' Language Display 

### ISSUE THREAD

**Issue by gtomatohk** [paypal/PayPal-iOS-SDK#278]
Hi,

We are developing an app that integrates the PayPal mobile SDK as our payment module, It came to our attention that the 'CVV' field on the credit card information page does not support Chinese translation while the other fields do. (please see attached)
![img_0339](https://cloud.githubusercontent.com/assets/12457287/7649325/738ee64e-fb1e-11e4-87de-1d8fa9b82b7a.PNG)
Since our app targets the greater China region, where majority of the users might not be familiar with the term 'CVV', we would like to suggest that the mobile SDK could update, or provide an option to update the field for a more user friendly experience.

Please let me know your feedback.

**Comment by dgoldman-ebay** [comment]
@gtomatohk thanks for your input! We will ask our Chinese translators to take another look at "CVV".

**Comment by gtomatohk** [comment]
Thanks for the response, will look forward to updates.

**Comment by dgoldman-ebay** [comment]
@gtomatohk do you have a specific suggestion for the Chinese text you would like to see for the CVV field? Ideally we would have translations for both Simplified Chinese for China, and Traditional Chinese for Hong Kong.

Our own Chinese translator feels that `CVV` is a term used by some banks in China in their own software, and that there is no Chinese word or phrase that would be any more clear for customers.

**Comment by gtomatohk** [comment]
@dgoldman-ebay we looked at other financial services and even PayPal TW's site and found that they use the following text for CVV.

Simplified Chinese: 信用卡安全码
Traditional Chinese: 信用卡安全碼

Thank you and your translator in advance.

**Comment by dgoldman-ebay** [comment]
Fixed in [version 2.11.0](https://github.com/paypal/PayPal-iOS-SDK/releases)
