### ISSUE TITLE
How to verify the legitimacy of this SDK?

### ISSUE THREAD

**Issue by pipacs** [paypal/PayPal-iOS-SDK#279]
How can users verify if an app is using this legit SDK, as opposed to a visually identical, but malicious lookalike?

**Comment by romk1n** [comment]
@pipacs apart from PayPal branding like logo i don't think there is a way to verify. Is there a specific reason you asking ? Have you seen any malicious look alike apps?

**Comment by pipacs** [comment]
Thank you for the answer. Just channeling the question, and no, I haven't seen any malicious lookalikes.
