### ISSUE TITLE
Screenshot in README is broken

### ISSUE THREAD

**Issue by johngraham262** [paypal/PayPal-iOS-SDK#280]
[README](https://github.com/paypal/PayPal-iOS-SDK/blob/master/README.md) has broken images.

**Comment by dgoldman-ebay** [comment]
Looks fine to me, @johngraham262 

You mean this one: https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/sdk-screens.png ?

**Comment by johngraham262** [comment]
Yes, that first image in the README.

![image](https://cloud.githubusercontent.com/assets/961905/7738729/b13029c6-ff25-11e4-9903-1aad91064aa4.png)

**Comment by dgoldman-ebay** [comment]
@johngraham262 that image (URL in my previous comment) shows up just fine for me, on two different computers, in three different browsers.

If you can find any hints as to why your results are different, let us know!

We definitely appreciate your help.

**Comment by johngraham262** [comment]
Interesting... so I was on the internal "Ebay Corp" network and the image didn't load. (Full disclosure, I work at Venmo under Paypal, so we're under the "Ebay Corp" network) When I switched to guest network, the image loads perfectly.

**Comment by dgoldman-ebay** [comment]
Ah! This morning I saw a few other people on the internal eBay Corp network complaining about their browser complaining that one of github's certificates was self-signed. Maybe that's another symptom of the same problem.

**Comment by johngraham262** [comment]
Whoa, that might be it. Thanks for the quick response!
