### ISSUE TITLE
Cannot create new app rest api

### ISSUE THREAD

**Issue by 52616e646f6d4279746573** [paypal/PayPal-iOS-SDK#282]
Hi, 

Not sure if you can help me here. I have created a paypal developer account. When I go to "my apps" then click on "create app", it prompts me to enter an app name and select "Sandbox developer account". But  "Sandbox developer account" is greyed out. So I went to Sandbox--> Accounts and created a new business and personal account. But the field is still greyed out. 

Also when I click on "profile" for any of the accounts it says "We experienced some issues on our end while creating this Sandbox account. Please delete it and try again." So I deleted and tried to create new accounts. Still the same. Getting pretty frustrated with this, any tips how I can fix this.

Thanks,
RB 

PS. Even my default accounts that were created say "We experienced some issues on our end while creating this Sandbox account. Please delete it and try again." But I cannot delete them??

**Comment by tomwhipple** [comment]
Unfortunately this isn't something that the SDK engineering team can help with. The [merchant technical support](https://www.paypal.com/mts) team has access to accounts and can be more helpful.
