### ISSUE TITLE
OSX porting

### ISSUE THREAD

**Issue by peterpaulis** [paypal/PayPal-iOS-SDK#285]
is it possible to port to OSX?

**Comment by mickeyreiss** [comment]
Hi @peterpaulis,

I work on the [Braintree SDK](https://github.com/braintree/braintree_ios). This is an interesting request. I'm curious to hear more.

Can you describe the application and the PayPal features you're looking for a bit more?

Although the SDK(s) doesn't currently support OS X, I wonder if a webview based solution might be an acceptable compromise.

**Comment by peterpaulis** [comment]
Hi, its easy, see fontstand.com :)

**Comment by tomwhipple** [comment]
OSX would be an entirely different product... At this point I don't think there is enough demand to warrant the extra overhead. 

As Mickey suggests, maybe try a web integration? Or some combination of that and [REST API](https://developer.paypal.com/webapps/developer/docs/api/) integration from your backend?
