### ISSUE TITLE
Paypal integration with parse 

### ISSUE THREAD

**Issue by parmindersinghgill** [paypal/PayPal-iOS-SDK#292]
i am integrating paypal with parse , paypal needs -ObjC in other linker flags which cause issue in build , i also added facebook SDK for parse & used -load_all for paypal but still i am unable to build to project .

is there any way so i can integrate paypal without using -ObjC or is there any way so i can integrate both of them without issues ?

Thanks in advance

**Comment by tomwhipple** [comment]
Can you share the build error you're getting?

**Comment by parmindersinghgill** [comment]
i resolved by it using pods .
one more thing i want to know is the paypal gives there own view for filling shipping address ? or i have to make it.

**Comment by tomwhipple** [comment]
There is not a view for filling in shipping address, though we do allow the user to choose one that's already been set up within PayPal, if they are paying with PayPal.

If you want a predefined entry view, you might check out [Braintree](https://braintreepayments.com).
