### ISSUE TITLE
Making Future payment go through server side

### ISSUE THREAD

**Issue by holgersindbaek** [paypal/PayPal-iOS-SDK#294]
I'm using the Ruby SDK in my Rails API to get the refresh token and eventually to make the payment go through. I'm having some issues with this and wanted to know if anyone had some experience using the Paypal iOS SDK as the client side library and the Paypal Ruby SDK as the server side library.

I'm describing my issue here: https://github.com/paypal/PayPal-Ruby-SDK/issues/137

@braebot Maybe you know the answer to this one as well?!

**Comment by juwlee** [comment]
Closing as it is being tracked with the Ruby SDK issue.
