### ISSUE TITLE
PayPal-iOS-SDK framework doesn't work when install via CocoaPods 0.38

### ISSUE THREAD

**Issue by kesar** [paypal/PayPal-iOS-SDK#302]
podfile

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'PayPal-iOS-SDK'
```

**Comment by romk1n** [comment]
@kesar possibly the same issue as https://github.com/paypal/PayPal-iOS-SDK/issues/275#issuecomment-98803448 ?

**Comment by kesar** [comment]
It's possible but that issue was about CocoaPods 0.37. It would be awesome to find a better solution than to add libPayPalMobile.a to main project.

**Comment by tomwhipple** [comment]
What kind of errors do you see? More details would be helpful...

**Comment by cris7ian** [comment]
Hi, same error here. I add the Pod but my code won't find the PayPalMobile class or anything. One clue, PayPal is not showing in the Pods list.

![screenruler-668997b2-98f6-4ace-a483-addacc385eb6](https://cloud.githubusercontent.com/assets/2112370/9389294/91d50334-476a-11e5-9433-f2e3b5db0521.png)

I'm using Cocoapods 0.38.2.

**Comment by bluk** [comment]
[Release 2.12.4](https://github.com/paypal/PayPal-iOS-SDK/releases) has changed to use `vendored_libraries` in the pod spec which may help with this issue. Can anyone with this issue before try again? Thanks.

**Comment by bluk** [comment]
Haven't heard back from anyone recently on this so I will close this issue. Please leave a comment or open a new issue. Thanks.
