### ISSUE TITLE
Why is Direct Credit Card Payment available to some countries only?

### ISSUE THREAD

**Issue by milsirhc** [paypal/PayPal-iOS-SDK#303]
We thinking to use the iOS SDK, however it doesn't seems to allow direct credit card payment in Australia.

Will this ever be available to Australia or do we need to use Express Checkout instead?

**Comment by tomwhipple** [comment]
The preferred method for general purpose payment acceptance is [Braintree v.zero](https://www.braintreepayments.com/v.zero), which includes support for both PayPal and credit cards in Australia.
