### ISSUE TITLE
SDK leaves app in completely unusable state requiring force quit

### ISSUE THREAD

**Issue by paulsamuels** [paypal/PayPal-iOS-SDK#306]
Using the sample app (or any live app containing the SDK):

If the app is backgrounded for any reason (phonecall, home button, notification centre.....) whilst dismissing the PayPal SDK the app is left in a completely broken state, which requires a force quit to get out of.

**Steps**
* Enter PayPal
* Click cancel
* Press the home button
* Relaunch the app

**Result**
Unusable app

---

It appears that the SDK is inserting an image view into the view hierarchy without checking to ensure that it's the view hierarchy owned by the SDK.

![paypal-breaks-app](https://cloud.githubusercontent.com/assets/527091/9086434/6430b2c4-3b7c-11e5-98c9-9e6391cd79d2.gif)

**Comment by tomwhipple** [comment]
@paulsamuels What iOS version are you running?

**Comment by paulsamuels** [comment]
I've tried on 8.4 and 9

**Comment by tomwhipple** [comment]
Ok, I've got a fix for this. We'll get it in to the next release.
