### ISSUE TITLE
Negative Testing for iOS Question

### ISSUE THREAD

**Issue by RowanPD** [paypal/PayPal-iOS-SDK#311]
I'm trying to perform negative testing but the transaction always posts successfully. I"m in Sandbox Mode (as evidenced by the transaction response) and I have Negative Testing switched on in the Sandbox Merchant. I'm following instructions from the PayPal site about setting the error by setting the amount to "error / 100", i.e. generate error 10755 by posting for $107.55, but the transaction posts successfully and the merchant gets a notification of a sale.

I must be missing some setup step or another. Is this supported and do you have any suggestions (or a nice sample/link) of how this works in iOS?

If it is supported (and especially if it's not), it would be great to update the 2 sentence testing section in the SDK description/blurb to give pointers to how this works. :-)

**Comment by tomwhipple** [comment]
Unfortunately negative testing isn't really well supported by the REST API upon which the SDK is built.
