### ISSUE TITLE
User to user direct payment implementation in iOS app

### ISSUE THREAD

**Issue by amirpervaiz086** [paypal/PayPal-iOS-SDK#312]
Hi guys,
  In one of our app, we need to send direct payment from one user to another bypassing the merchant account. The app is to give reward to others for their services. Can anyone please let me know how it can be achieved using PayPal iOS SDK? Seems like its form of adaptive payments where user can send directly to multiple recipient. 

I would really appreciate PayPal iOS engineers to give us clear instructions on this issue.

**Comment by sealemar** [comment]
Looks like related to #9

**Comment by amirpervaiz086** [comment]
yeah but wondering there are lots of taxi apps who does sending money from user to user. how it can be achieved any insights on this?

**Comment by avidas** [comment]
Closing in favor of keeping the discussion on #9 . At this point, this is unfortunately not possible with this sdk.

**Comment by sealemar** [comment]
@amirpervaiz086, look at [PayPal MPL](https://developer.paypal.com/docs/classic/mobile/gs_MPL/), or other payment providers, ex. Stripe

**Comment by amirpervaiz086** [comment]
Thanx man. let me check PayPal MRL. Btw, 'Stripe Connect' is good option but I found its limited to some countries. I need to use it in Singapore but Stripe does not expand there yet.

**Comment by monkey199210** [comment]
I agree.
