### ISSUE TITLE
confict with CardIo plugin and Paypal payment plugin

### ISSUE THREAD

**Issue by zefrench** [paypal/PayPal-iOS-SDK#318]
I'm using scan card (cardIO) plugin on my app and I have some call to the scan within my index.js in order to scan card that will not be used with a paypal account and it works like a charm.

BUT
I need to install the paypal plugin but as paypal plugin comes now with carIo library I get duplicate error : duplicate symbol _CardIOCurrentScanningOrientatio when I run the cordova build ios and.. the build failed.

I tried to remove the cardIO plugin but I get error on my app : Can't find variable: CardIO

Is it a way to use the both plugin ?

If you have any idea, tell me..

**Comment by tomwhipple** [comment]
This issue is being addressed as https://github.com/paypal/PayPal-Cordova-Plugin/issues/103
