### ISSUE TITLE
Need support for shipping_address

### ISSUE THREAD

**Issue by lenkawell** [paypal/PayPal-iOS-SDK#32]
We've been using Mobile Express Payments for our app and we'd like to move to the new iOS SDK but it doesn't yet support a few payment properties that our accountants need: subtotal, tax and shipping. 

I see in the REST API that these properties are available under the payment details element, so it seems like the server support is available. Maybe they could be added as PayPalPayment object properties in addition to currencyCode, amount and shortDescription? 

Do you have plans to add these properties any time soon? Thanks.

**Comment by cph2117** [comment]
@dgoldman-ebay currently implementing the iOS SDK with payPalShippingAddressOption property set to PayPalShippingAddressOptionPayPal, but it returns null in Sandbox and NoNetwork mode.  Will it return an address when Live, or is there a bigger issue at hand?  So, to clarify the PayPalPayment objects shippingAddress property returns null in the delegate callback.  Thanks for your help!

**Comment by ort11** [comment]
HI, trying to use shipping address with the latest iOS sdk with no luck.  Even though a shipping address is specified, the transaction has the default address from the payment account.   How to get the provided shipping address on the transaction from the iOS SDK?

Also:

Is there any way to have the Paypal UI allow the user to choose the shipping address?

**Comment by romk1n** [comment]
@ort11 have you enabled shipping option in configuration ? check here for the options https://github.com/paypal/PayPal-iOS-SDK/blob/master/PayPalMobile/PayPalConfiguration.h#L61

**Comment by ort11** [comment]
Thanks a ton, this was it.  Did not see it...
