### ISSUE TITLE
Recipient Field Disappeared 

### ISSUE THREAD

**Issue by thesaad** [paypal/PayPal-iOS-SDK#321]
Is Recipient Field Disappeared in 2.11.4 SDK? How to manage that now?

**Comment by tomwhipple** [comment]
Are you referring to the recipient shipping field? https://github.com/paypal/PayPal-iOS-SDK/blob/6da680505fd8110a12d027b379f128a960ce349e/PayPalMobile/PayPalPayment.h#L105

**Comment by bluk** [comment]
@thesaad We haven't heard a response for 2 weeks, so I am going to close the issue. If this is still an issue, please re-open. Thanks!
