### ISSUE TITLE
Layout issue with long text

### ISSUE THREAD

**Issue by plu** [paypal/PayPal-iOS-SDK#322]
See screenshot

![simulator screen shot 10 sep 2015 08 51 27](https://cloud.githubusercontent.com/assets/31597/9781915/486e6a66-5799-11e5-9f04-8bca8883a711.png)

**Comment by avidas** [comment]
Hey we are able to reproduce this issue for iOS 9.0 and above, we will get back to you with a response soon.

**Comment by plu** [comment]
Cool, thank you :)

**Comment by avidas** [comment]
Fixed with 2.12.3 release!

**Comment by plu** [comment]
Thank you! :)
