### ISSUE TITLE
Can give custom UI of Payment screen

### ISSUE THREAD

**Issue by sadiqshaikh** [paypal/PayPal-iOS-SDK#323]
is shows the default PayPalPaymentViewController whose code is hidden. can we show our own screen in place of PayPalPaymentViewController or override it just to change the UI of the screen to match the app theme

**Comment by tomwhipple** [comment]
Unfortunately UI customization is not supported.

**Comment by sadiqshaikh** [comment]
Thanks, Okay but we can change the navigation colour i think!!!
