### ISSUE TITLE
install 2.12 version from cocoapods

### ISSUE THREAD

**Issue by ramoreno** [paypal/PayPal-iOS-SDK#326]
Hello,
I´m trying to update the sdk library from cocoapods, but when I run the "update command" version 2.11.4 is installed.

¿It is possible to install 2.12 version with cocoapods?

Thanks in advance

**Comment by tomwhipple** [comment]
We will be pushing the latest out to cocoapods very shortly.

**Comment by bluk** [comment]
@ramoreno `2.12.1` has been pushed to CocoaPods. Thanks for your patience.
