### ISSUE TITLE
受iOS9 语言资源识别不一样的影响，在简体中文系统下未能正确识别的，默认显示英文界面，导致支付失败。

### ISSUE THREAD

**Issue by Lorin331** [paypal/PayPal-iOS-SDK#328]
受iOS9 语言资源识别不一样的影响，在简体中文系统下未能正确识别的，默认显示英文界面，导致支付失败。
提示：
We're Sorry
System error.Please try again later.

实际上已经支付成功了，没有任何回调。

**Comment by Lorin331** [comment]
系统切换为英文系统，支付正常。

**Comment by tomwhipple** [comment]
I'm sorry but I'm afraid we can only take bug reports in English here... 

For other languages, please contact your local PayPal support for help bridging the language gap.
