### ISSUE TITLE
[PPLinkableTextField setKeyboardType:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by kuldeep13990** [paypal/PayPal-iOS-SDK#333]
IOS 9.0
When i present PayPalPaymentViewController , my project just crash with following error. 

[PPLinkableTextField setKeyboardType:]: unrecognized selector sent to instance

any solution 

Thanks in advance

**Comment by bluk** [comment]
Can you give what version of the SDK you're using?

```
  NSLog(@"%@", [PayPalMobile libraryVersion]);
```

Also do you have any categories/extensions or any other code that is calling `setKeyboardType`? `PPLinkableTextField` extends `UITextField` so the keyboardType property should exist on instances, but it seems `setKeyboardType` is being called as a class method.

**Comment by orlandomatei** [comment]
Hmm, it seems that I am using an older version: PayPal iOS SDK 2.11.0
*** Terminating app due to uncaught exception 'NSRangeException', reason: '-[NSTaggedPointerString getCharacters:range:]: Range {0, 7} out of bounds; string length 4

I just downloaded the files from github (2.11.5) and replaced PayPalMobile folder in my project. Is there anything else I should do to properly upgrade?

As for setKeyboardType - I am not using this anywhere in my project.

Thank you!

**Comment by orlandomatei** [comment]
Ok - it was entirely my fault. I had another copy of libPayPalMobile.a (older version) in the root folder of the project which I didn't know about - I thought XCode was looking only in PayPalMobile folder. Now it is the correct version and it is working properly.

Sorry for the mix-up and thank you very much for helping me find the problem.

**Comment by bluk** [comment]
@orlandomatei I'm glad version 2.11.5 works for you. I assume that you're replying for issue #310 with the crashing locale and not for the `setKeyboardType` #333 issue (which is where your latest comments are going).

@kuldeep13990 Can you try the latest version to see if that works? Thanks!

**Comment by orlandomatei** [comment]
Sorry about posting in the wrong section, yes I am replying for issue #310. Thanks.

**Comment by kuldeep13990** [comment]
@bluk PayPal LibraryVersion is 2.11.5

**Comment by kuldeep13990** [comment]
I download PayPal-iOS-SDK 2.12.2 and try to integrate but still i got the same error : [PPLinkableTextField setKeyboardType:]: unrecognized selector sent to instance.

PayPal-iOS-SDK can only implement with StoryBoard Project? or it can also be in implement in XIB Project..

Any Solution Please.

thanks in advance.

**Comment by bluk** [comment]
I think Apple strongly recommends using Storyboard Projects. Can you try the Objective-C sample application included with the SDK and see if it works for you?

**Comment by kuldeep13990** [comment]
I used Latest PayPal SDK, Here is My Code..

@interface PayPalVerificationViewController ()

@property (nonatomic, strong, readwrite) PayPalConfiguration *payPalConfiguration;

@end

@implementation PayPalVerificationViewController


- (void)viewDidLoad
{
    [super viewDidLoad];
    
    _payPalConfiguration = [[PayPalConfiguration alloc] init];
    
    _payPalConfiguration.acceptCreditCards = NO;
    
    _payPalConfiguration.payPalShippingAddressOption = PayPalShippingAddressOptionPayPal;
    
}

- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
}

- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    self.title = @"PayPal Verification";
    
    [PayPalMobile preconnectWithEnvironment:PayPalEnvironmentSandbox];
}

- (IBAction)verifyPayPalBtnClick:(id)sender
{
    PayPalPayment *payment = [[PayPalPayment alloc] init];
    
    payment.amount = [[NSDecimalNumber alloc] initWithString:@"39.95"];
    payment.currencyCode = @"USD";
    payment.shortDescription = @"Awesome saws";

    payment.intent = PayPalPaymentIntentAuthorize;

    if (!payment.processable)
    {
        
    }
    
    PayPalPaymentViewController *paymentViewController;
    paymentViewController = [[PayPalPaymentViewController alloc] initWithPayment:payment
                                                                   configuration:self.payPalConfiguration
                                                                        delegate:self];
    
    [self presentViewController:paymentViewController animated:YES completion:nil];
}

#pragma mark - PayPalPaymentDelegate methods

- (void)payPalPaymentViewController:(PayPalPaymentViewController *)paymentViewController
                 didCompletePayment:(PayPalPayment *)completedPayment
{
    [self verifyCompletedPayment:completedPayment];
    [self dismissViewControllerAnimated:YES completion:nil];
}

- (void)payPalPaymentDidCancel:(PayPalPaymentViewController *)paymentViewController {
    [self dismissViewControllerAnimated:YES completion:nil];
}

- (void)verifyCompletedPayment:(PayPalPayment *)completedPayment {
    
    NSData *confirmation = [NSJSONSerialization dataWithJSONObject:completedPayment.confirmation
                                                           options:0
                                                             error:nil];
}



When paypal View appear , i am getting same error [PPLinkableTextField setKeyboardType:]: unrecognized selector sent to instance

Any solution Please

Thanks.

**Comment by bluk** [comment]
@kuldeep13990 Were you able to try out the sample app and see if that works? Please reopen if you still have an issue.
