### ISSUE TITLE
Paypal SDK

### ISSUE THREAD

**Issue by Ha33y** [paypal/PayPal-iOS-SDK#334]
I'm facing problem while integrating Paypal for live payments in ios app.It works for Sanbox mode.My credentials(ClientId also valid).

I'm using below code in AppDelegate method,
[PayPalMobile initializeWithClientIdsForEnvironments:@{PayPalEnvironmentProduction : @"YOUR_CLIENT_ID_FOR_PRODUCTION",
//                                                           PayPalEnvironmentSandbox : @"YOUR_CLIENT_ID_FOR_SANDBOX"}];

 
In Actual payment page i'm using below code in ViewDidLoad() method,

_payPalConfig = [[PayPalConfiguration alloc] init];
   // _payPalConfig.
  _payPalConfig.acceptCreditCards = YES;
  //_payPalConfig.merchantName = @"Awesome Shirts, Inc.";
    _payPalConfig.merchantName = @"";
 //   _payPalConfig.
  _payPalConfig.merchantPrivacyPolicyURL = [NSURL URLWithString:@"https://www.paypal.com/webapps/mpp/ua/privacy-full"];
  _payPalConfig.merchantUserAgreementURL = [NSURL URLWithString:@"https://www.paypal.com/webapps/mpp/ua/useragreement-full"];
  _payPalConfig.defaultUserEmail = @"Mykarwash@gmail.com";//appDelegate.customername;
 
  
  [PayPalMobile preconnectWithEnvironment:PayPalEnvironmentProduction];
 _payPalConfig.languageOrLocale = [NSLocale preferredLanguages][0];
 _payPalConfig.payPalShippingAddressOption = PayPalShippingAddressOptionNone;
     if(appDelegate.environment.length==0)
    {
        
        self.environment = PayPalEnvironmentProduction;//kPayPalEnvironment1;///////////////////////////////////////////////////
        
        NSLog(@"In ViewDid Load, Value of self.environment: %@",self.environment);
        appDelegate.environment = PayPalEnvironmentProduction;//self.environment;        
    }

 - (void)viewWillAppear:(BOOL)animated {
  [super viewWillAppear:YES];
  // Preconnect to PayPal early
[self setPayPalEnvironment:appDelegate.environment];
}

- (void)setPayPalEnvironment:(NSString *)environment
{
 appDelegate.environment = environment;
 //[PayPalMobile preconnectWithEnvironment:appDelegate.environment];

 }

Every time,after setPayPalEnvironment: method,i got below message.

PayPal SDK: Request has failed with error: invalid_client - System error (invalid_client). Please try again later. (401) | PayPal Debug-ID: 78c4f815f1538 [live, PayPal iOS SDK 2.9.0] | Details: (
        {
        "error_description" = "Client Authentication failed";
    }
).

Please help me.

**Comment by Ha33y** [comment]
My complete code is,




#import <UIKit/UIKit.h>

@interface AppDelegate : UIResponder <UIApplicationDelegate>
{
    NSString *usertype;
    UIStoryboard *storyboard;
    NSString *environment;
}
@property (nonatomic, retain) NSString *environment;
@property (assign) int acceptcard;
@property (strong, nonatomic) UIWindow *window;
@property (nonatomic, strong) NSString *usertype;
@property (nonatomic, strong)  NSUserDefaults * defaultLogin;
@property(nonatomic, strong, readwrite) NSString *resultText;
@property (nonatomic, strong) NSString *statusStr;

- (BOOL)acceptCreditCards;
- (void)setAcceptCreditCards:(BOOL)processCreditCards;
- (void)setPayPalEnvironment:(NSString *)environment;

@end


//
//  AppDelegate.m

#import "AppDelegate.h"
#import "PayPalMobile.h"

@interface AppDelegate ()

@end

@implementation AppDelegate
@synthesize window,statusStr;
@synthesize usertype,acceptcard,environment,resultText;

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    
    statusStr = [[NSString alloc]init];
    
#pragma mark warning "Enter your credentials"
    
    
//    [PayPalMobile initializeWithClientIdsForEnvironments:@{PayPalEnvironmentProduction : @"YOUR_CLIENT_ID_FOR_PRODUCTION",
//                                                           PayPalEnvironmentSandbox : @"YOUR_CLIENT_ID_FOR_SANDBOX"}];
//    
    
   /*
    self.defaultLogin= [NSUserDefaults standardUserDefaults];
    
    UIImage *navBackgroundImage = [UIImage imageNamed:@"header"];
    [[UINavigationBar appearance] setBackgroundImage:navBackgroundImage forBarMetrics:UIBarMetricsDefault];
    
    [[UINavigationBar appearance] setTitleTextAttributes:
     [NSDictionary dictionaryWithObjectsAndKeys:
      [UIColor whiteColor],
      NSForegroundColorAttributeName,
      [UIColor whiteColor],
      NSForegroundColorAttributeName,
      [NSValue valueWithUIOffset:UIOffsetMake(0, -1)],
      NSForegroundColorAttributeName,
      [UIFont fontWithName:@"Arial-Bold" size:0.1],
      NSFontAttributeName,
      nil]];
   
    [[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleLightContent];
    */
    
   // NSString *stringValue = [[NSUserDefaults standardUserDefaults] valueForKey:@"isLogin"];
    
//    if([stringValue isEqualToString:@"Yes"] || [stringValue isEqualToString:@"TRUE"])
//    {
//        UserHomeViewController *home=[storyboard instantiateViewControllerWithIdentifier:@"UserHomeViewController"];
//        UINavigationController * navController = [[UINavigationController alloc]initWithRootViewController:home];
//        self.window.rootViewController=navController;
//    }
//    else
//    {
    
    
   // SettingsViewController *settingsViewObj = [storyboard instantiateViewControllerWithIdentifier:@"SettingsView"];
   // [self.navigationController pushViewController:settingsViewObj animated:YES];
    
    
    
        self.window = [[UIWindow alloc] initWithFrame:UIScreen.mainScreen.bounds];
        storyboard =  [UIStoryboard storyboardWithName:@"Main" bundle:nil];
        ViewController *obj_ViewController=[storyboard instantiateViewControllerWithIdentifier:@"ViewController"];
        UINavigationController * navController = [[UINavigationController alloc]initWithRootViewController:obj_ViewController];
        self.window.rootViewController=navController;
    
    [self.window makeKeyAndVisible];
    
    
    
//    
//    UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"MainStoryboard" bundle:nil];
//    
//    UIViewController *viewController = // determine the initial view controller here and instantiate it with [storyboard instantiateViewControllerWithIdentifier:<storyboard id>];
//    
//    self.window.rootViewController = viewController;
//    [self.window makeKeyAndVisible];
//    
//    
    
    
    
  //  }
    
    return YES;
}





- (void)applicationWillResignActive:(UIApplication *)application {
    //Sent when  the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
    // Use this method to pause ongoing tasks, disable timers, and throttle down OpenGL ES frame rates. Games should use this method to pause the game.
}

- (void)applicationDidEnterBackground:(UIApplication *)application {
    // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
    // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
}

- (void)applicationWillEnterForeground:(UIApplication *)application {
    // Called as part of the transition from the background to the inactive state; here you can undo many of the changes made on entering the background.
}

- (void)applicationDidBecomeActive:(UIApplication *)application {
    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
}

- (void)applicationWillTerminate:(UIApplication *)application {
    // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
}

@end



////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


//
//  ZZMainViewController.h
//  PayPal-iOS-SDK-Sample-App
//
//  Copyright (c) 2014, PayPal
//  All rights reserved.
//


#import "ZZFlipsideViewController.h"
#import "PayPalMobile.h"
#import "AppDelegate.h"

@interface ZZMainViewController : UIViewController <PayPalPaymentDelegate, PayPalFuturePaymentDelegate, PayPalProfileSharingDelegate, ZZFlipsideViewControllerDelegate, UIPopoverControllerDelegate,MBProgressHUDDelegate>
{
    MBProgressHUD *HUD;
    NSString *payment_Status,*payment_Id;
    NSString *itemName,*paymentString;
    
    NSString *service,*product;
    NSDecimalNumber *total;
    NSDecimalNumber *subtotal;
    NSDecimalNumber *shipping;
    NSDecimalNumber *tax;
    NSString *curr_coupon;
    NSString *garagetkt_Str;
    
    UIDatePicker *myDate_TimePicker;
    
    NSString *curr_TimeStr;
    
    PayPalPaymentDetails *paymentDetails;
    
    PayPalMobile *paypalmobileObj;
    
}

@property (nonatomic, strong) IBOutlet UIButton *paymentBtn;
@property(nonatomic, strong) NSString *itemCost;
@property(nonatomic, strong, readwrite) NSString *environment,*environment1;
@property(nonatomic, assign, readwrite) BOOL acceptCreditCards;
@property(nonatomic, strong, readwrite) NSString *resultText;
@property (nonatomic, strong) PayPalItem *item,*Finalitem;

@end







//
//  ZZMainViewController.m
//  PayPal-iOS-SDK-Sample-App
//
//  Copyright (c) 2014, PayPal
//  All rights reserved.
//

#import "ZZMainViewController.h"
#import <QuartzCore/QuartzCore.h>
#import "ZZFlipsideViewController.h"

// Set the environment:
// - For live charges, use PayPalEnvironmentProduction (default).
// - To use the PayPal sandbox, use PayPalEnvironmentSandbox.
// - For testing, use PayPalEnvironmentNoNetwork.
//#define kPayPalEnvironment1 PayPalEnvironmentNoNetwork

#define kPayPalEnvironment1 PayPalEnvironmentProduction//Edited 10Sep 2015 6PM.........

//PayPalEnvironmentNoNetwork
@interface ZZMainViewController ()

@property(nonatomic, strong, readwrite) IBOutlet UIButton *payNowButton;
@property(nonatomic, strong, readwrite) IBOutlet UIButton *payFutureButton;
@property(nonatomic, strong, readwrite) IBOutlet UIView *successView;
@property(nonatomic, strong, readwrite) PayPalConfiguration *payPalConfig;

@end

@implementation ZZMainViewController


@synthesize paymentBtn;

AppDelegate *appDelegate;

- (void)viewDidLoad {
  [super viewDidLoad];
 // self.title = @"PayPal SDK Demo";

    appDelegate = (AppDelegate *)[[UIApplication sharedApplication]delegate];
    
    _temp = [[NSMutableArray alloc]init];
  // Set up payPalConfig
  _payPalConfig = [[PayPalConfiguration alloc] init];
   // _payPalConfig.
  _payPalConfig.acceptCreditCards = YES;
  //_payPalConfig.merchantName = @"Awesome Shirts, Inc.";
    _payPalConfig.merchantName = @"";
 //   _payPalConfig.
  _payPalConfig.merchantPrivacyPolicyURL = [NSURL URLWithString:@"https://www.paypal.com/webapps/mpp/ua/privacy-full"];
  _payPalConfig.merchantUserAgreementURL = [NSURL URLWithString:@"https://www.paypal.com/webapps/mpp/ua/useragreement-full"];
  _payPalConfig.defaultUserEmail = @"abc@gmail.com";//appDelegate.customername;
 
  
    
   //_payPalConfig.rememberUser
    
    
    [PayPalMobile preconnectWithEnvironment:PayPalEnvironmentProduction];
    
    // Setting the languageOrLocale property is optional.
  //
  // If you do not set languageOrLocale, then the PayPalPaymentViewController will present
  // its user interface according to the device's current language setting.
  //
  // Setting languageOrLocale to a particular language (e.g., @"es" for Spanish) or
  // locale (e.g., @"es_MX" for Mexican Spanish) forces the PayPalPaymentViewController
  // to use that language/locale.
  //
  // For full details, including a list of available languages and locales, see PayPalPaymentViewController.h.
  
  _payPalConfig.languageOrLocale = [NSLocale preferredLanguages][0];
  
  
  // Setting the payPalShippingAddressOption property is optional.
  //
  // See PayPalConfiguration.h for details.
  
 // _payPalConfig.payPalShippingAddressOption = PayPalShippingAddressOptionPayPal;//Edited  10Sep2015.................
    
    
    _payPalConfig.payPalShippingAddressOption = PayPalShippingAddressOptionNone;
    
    

  // Do any additional setup after loading the view, typically from a nib.

  self.successView.hidden = YES;
  
  // use default environment, should be Production in real life

 // self.environment = kPayPalEnvironment;
    
        if(appDelegate.environment.length==0)
    {
        
        self.environment = PayPalEnvironmentProduction;//kPayPalEnvironment1;///////////////////////////////////////////////////
        
        NSLog(@"In ViewDid Load, Value of self.environment: %@",self.environment);
        appDelegate.environment = PayPalEnvironmentProduction;//self.environment;        
    }
}

-(IBAction) settings_Clicked:(id)sender
{
    ZZFlipsideViewController *ObjZZFlipsideViewController = [[UIStoryboard storyboardWithName:@"Main" bundle:nil] instantiateViewControllerWithIdentifier:@"Settings"];
    [self.navigationController pushViewController:ObjZZFlipsideViewController animated:YES];
}


- (void)viewWillAppear:(BOOL)animated {
  [super viewWillAppear:YES];
  // Preconnect to PayPal early
    
    if ([paymentString isEqualToString:@"ServicePage"])
    {
        
        NSLog(@"In viewWillAppear,appDelegate.environment:%@",appDelegate.environment);
        [self setPayPalEnvironment:appDelegate.environment];
        //[self setPayPalEnvironment:self.environment];//self.environment];
        
    }
    else
    {
        [self setPayPalEnvironment:appDelegate.environment];
    }
}

-(IBAction)goToBack:(UIButton *)sender
{
    appDelegate.environment=nil;
    [self.navigationController popViewControllerAnimated:YES];
}

- (void)setPayPalEnvironment:(NSString *)environment
{
    
    if ([paymentString isEqualToString:@"ServicePage"])
    {
        
       // self.environment = environment;
        
        appDelegate.environment = environment;
        
        NSLog(@"In setPayPalEnvironment method,self.environment:%@",environment);
       //NSLog(@"In setPayPalEnvironment method,self.environment:%@",self.environment);
        
        //[PayPalMobile preconnectWithEnvironment:appDelegate.environment];
        
        [PayPalMobile preconnectWithEnvironment:PayPalEnvironmentProduction];
        
        
       // [PayPalMobile preconnectWithEnvironment:environment];
       // [PayPalMobile preconnectWithEnvironment:self.environment];
        
        NSLog(@"In setPayPalEnvironment method,self.environment:%@",self.environment);
        
    }
    else{
        self.environment = environment;
        [PayPalMobile preconnectWithEnvironment:environment];
        
    }
}

#pragma mark - Receive Single Payment

- (IBAction)pay {
    
    // Remove our last completed payment, just for demo purposes.
    self.resultText = nil;
    
    PayPalPayment *payment = [[PayPalPayment alloc] init];
    payment.currencyCode = @"USD";
    
    //payment.intent = PayPalPaymentIntentSale;//*********************Added code at 23Sep2015******************..............................
    
    NSMutableArray *itemArray = [[NSMutableArray alloc]init];
    defaults = [NSUserDefaults standardUserDefaults];
    cupon_Status = [defaults stringForKey:@"cupon"];
    final_digit = [defaults stringForKey:@"final_Price"];
    
    if ([_arrayofnames count]>0)
    {
        
        if ([paymentString isEqualToString:@"ServicePage"])
        {
            
            if ([cupon_Status isEqualToString:@"skip"])
            {
                
                curr_coupon = @"no";
                for (int  i=0; i<[_arrayofnames count]; i++)
                {
                    itemName =  [_arrayofnames objectAtIndex:i];
                    _itemCost =  [_arrayOfprices objectAtIndex:i];
                    
                    if ([_itemCost hasPrefix:@"$"] && [_itemCost length] > 1)
                    {
                        _itemCost = [_itemCost substringFromIndex:1];
                    }
                    
                    
                    NSLog(@"_itemCost:%@",_itemCost);
                    
                    //NSString *str=@"14.6";
                    CGFloat _itemCost1=[_itemCost floatValue];
                    NSLog(@"_itemCost1: %.2f",_itemCost1);
                    NSString *finalCost = [NSString stringWithFormat:@"%f",_itemCost1];
                    NSLog(@"Value of finalCost:%@",finalCost);
                    
                    PayPalItem *item1 = [PayPalItem itemWithName:[NSString stringWithFormat:@"%@",itemName]
                                                    withQuantity:1
                                                       withPrice:[NSDecimalNumber decimalNumberWithString:finalCost]
                                                    withCurrency:@"USD"
                                                         withSku:@"Hip-00037"];
                    [itemArray addObject:item1];//_itemCost
                }
            }
            else
            {
                curr_coupon = @"yes";
                for (int  i=0; i<[_arrayofnames count]; i++)
                {
                    itemName =  [_arrayofnames objectAtIndex:i];
                }
                _itemCost =  final_digit;
                
                if ([_itemCost hasPrefix:@"$"] && [_itemCost length] > 1)
                {
                    _itemCost = [_itemCost substringFromIndex:1];
                }
                
                PayPalItem *item1 = [PayPalItem itemWithName:[NSString stringWithFormat:@"%@",itemName]
                                                withQuantity:1
                                                   withPrice:[NSDecimalNumber decimalNumberWithString:_itemCost]
                                                withCurrency:@"USD"
                                                     withSku:@"Hip-00037"];
                [itemArray addObject:item1];
            }
        }
        else
        {
            
            if ([cupon_Status isEqualToString:@"skip"])
            {
               
                curr_coupon = @"no";
                for (int  i=0; i<[_arrayofnames count]; i++)
                {
                    itemName =  [_arrayofnames objectAtIndex:i];
                    _itemCost =  [_arrayOfprices objectAtIndex:i];
                    
                    if ([_itemCost hasPrefix:@"$"] && [_itemCost length] > 1)
                    {
                        _itemCost = [_itemCost substringFromIndex:1];
                    }
                    
                    PayPalItem *item1 = [PayPalItem itemWithName:[NSString stringWithFormat:@"%@",itemName]
                                                    withQuantity:1
                                                       withPrice:[NSDecimalNumber decimalNumberWithString:@"$1"]
                                                    withCurrency:@"USD"
                                                         withSku:@"Hip-00037"];//_itemCost
                    [itemArray addObject:item1];
                }
            }
            else
            {
                curr_coupon = @"yes";
                for (int  i=0; i<[_arrayofnames count]; i++)
                {
                    itemName =  [_arrayofnames objectAtIndex:i];
                }
                _itemCost =  final_digit;
                
                if ([_itemCost hasPrefix:@"$"] && [_itemCost length] > 1)
                {
                    _itemCost = [_itemCost substringFromIndex:1];
                }
                
                PayPalItem *item1 = [PayPalItem itemWithName:[NSString stringWithFormat:@"%@",itemName]
                                                withQuantity:1
                                                   withPrice:[NSDecimalNumber decimalNumberWithString:_itemCost]
                                                withCurrency:@"USD"
                                                     withSku:@"Hip-00037"];
                [itemArray addObject:item1];
            }
        }
        // Note: For purposes of illustration, this example shows a payment that includes
        //       both payment details (subtotal, shipping, tax) and multiple items.
        //       You would only specify these if appropriate to your situation.
        //       Otherwise, you can leave payment.items and/or payment.paymentDetails nil,
        //       and simply set payment.amount to your total charge.
        
        
        //if (!payment.processable) {
            // This particular payment will always be processable. If, for
            // example, the amount was negative or the shortDescription was
            // empty, this payment wouldn't be processable, and you'd want
            // to handle that here.
       // }
        
        
        
        if (!payment.processable)
        {
            
            NSLog(@"Error");
            
        }
        
        
        NSLog(@"Values in itemArray:%@",itemArray);
        
        if ([paymentString isEqualToString:@"ServicePage"])
        {
            
            subtotal = [PayPalItem totalPriceForItems:itemArray];
            shipping = [[NSDecimalNumber alloc] initWithString:@"0.00"];
            tax = [[NSDecimalNumber alloc] initWithString:service];
            total = [[subtotal decimalNumberByAdding:shipping] decimalNumberByAdding:tax];
            
            [defaults setObject:total forKey:@"Payment_amount"];
        }
        else
        {
            subtotal = [PayPalItem totalPriceForItems:itemArray];
            shipping = [[NSDecimalNumber alloc] initWithString:@"0.00"];
            tax = [[NSDecimalNumber alloc] initWithString:product];
            total = [[subtotal decimalNumberByAdding:shipping] decimalNumberByAdding:tax];
            [defaults setObject:total forKey:@"Payment_amount"];
        }
        
        NSLog(@"Value of subtotal:%@",subtotal);
        
        ;
         /* Added code at 24Sep2015................... starts  */
        paymentDetails = [PayPalPaymentDetails paymentDetailsWithSubtotal:subtotal
                                                                                   withShipping:shipping
                                                                                        withTax:tax];
        payment.amount = total;
        //          payment.currencyCode = @"USD";
        payment.shortDescription = @"Car Products";
        payment.items = itemArray;  // if not including multiple items, then leave payment.items as nil
        payment.paymentDetails = paymentDetails;
        
        // Update payPalConfig re accepting credit cards.
        _payPalConfig.acceptCreditCards = appDelegate.acceptcard;
        /* Added code at 24Sep2015................... ends  */
        
        PayPalPaymentViewController *paymentViewController;
        paymentViewController = [[PayPalPaymentViewController alloc] initWithPayment:payment
                                                                                                    configuration:self.payPalConfig
                                                                                                         delegate:self];
        
        
        //setEnvironment:PayPalEnvironmentProduction];
        [self presentViewController:paymentViewController animated:YES completion:nil];
    }
    else
    {
        UIAlertView *alert = [[UIAlertView alloc]initWithTitle:@"Alert" message:@"no Products avialable" delegate:nil cancelButtonTitle:nil otherButtonTitles:@"Ok", nil];
        [alert show];
    }
}
#pragma mark PayPalPaymentDelegate methods

- (void)payPalPaymentViewController:(PayPalPaymentViewController *)paymentViewController didCompletePayment:(PayPalPayment *)completedPayment
{
    
    
  self.resultText = [completedPayment description];
  [self showSuccess];
  [self sendCompletedPaymentToServer:completedPayment]; // Payment was processed successfully; send to server for verification and fulfillment
  [self dismissViewControllerAnimated:YES completion:nil];
}

- (void)payPalPaymentDidCancel:(PayPalPaymentViewController *)paymentViewController
{
    
  self.resultText = nil;
  self.successView.hidden = YES;
  [self dismissViewControllerAnimated:YES completion:nil];
}

#pragma mark Proof of payment validation

- (void)sendCompletedPaymentToServer:(PayPalPayment *)completedPayment {
    
  // TODO: Send completedPayment.confirmation to server
    NSString *paymentSTR = [NSString stringWithFormat:@"%@",completedPayment.confirmation];
    
    NSDictionary *arr = completedPayment.confirmation;
    NSMutableArray *dicdata = [arr valueForKey:@"response"];
    payment_Status = [dicdata valueForKey:@"state"];
    payment_Id = [dicdata valueForKey:@"id"];
    defaults = [NSUserDefaults standardUserDefaults];
    [defaults setObject:paymentSTR forKey:@"lastpayment"];
    
}

#pragma mark - Authorize Future Payments

- (IBAction)getUserAuthorizationForFuturePayments:(id)sender {
  
  PayPalFuturePaymentViewController *futurePaymentViewController = [[PayPalFuturePaymentViewController alloc] initWithConfiguration:self.payPalConfig delegate:self];
  [self presentViewController:futurePaymentViewController animated:YES completion:nil];
}


#pragma mark PayPalFuturePaymentDelegate methods

- (void)payPalFuturePaymentViewController:(PayPalFuturePaymentViewController *)futurePaymentViewController
                didAuthorizeFuturePayment:(NSDictionary *)futurePaymentAuthorization
{
    
    
  self.resultText = [futurePaymentAuthorization description];
  [self showSuccess];
  [self sendFuturePaymentAuthorizationToServer:futurePaymentAuthorization];
  [self dismissViewControllerAnimated:YES completion:nil];
}

- (void)payPalFuturePaymentDidCancel:(PayPalFuturePaymentViewController *)futurePaymentViewController
{
    
  self.successView.hidden = YES;
  [self dismissViewControllerAnimated:YES completion:nil];
}

- (void)sendFuturePaymentAuthorizationToServer:(NSDictionary *)authorization
{
    
  // TODO: Send authorization to server
}


#pragma mark - Authorize Profile Sharing

- (IBAction)getUserAuthorizationForProfileSharing:(id)sender
{
    
  NSSet *scopeValues = [NSSet setWithArray:@[kPayPalOAuth2ScopeOpenId, kPayPalOAuth2ScopeEmail, kPayPalOAuth2ScopeAddress, kPayPalOAuth2ScopePhone]];
  PayPalProfileSharingViewController *profileSharingPaymentViewController = [[PayPalProfileSharingViewController alloc] initWithScopeValues:scopeValues configuration:self.payPalConfig delegate:self];
  [self presentViewController:profileSharingPaymentViewController animated:YES completion:nil];
    
}


#pragma mark PayPalProfileSharingDelegate methods

- (void)payPalProfileSharingViewController:(PayPalProfileSharingViewController *)profileSharingViewController
             userDidLogInWithAuthorization:(NSDictionary *)profileSharingAuthorization
{
    
  self.resultText = [profileSharingAuthorization description];
  [self showSuccess];
  [self sendProfileSharingAuthorizationToServer:profileSharingAuthorization];
  [self dismissViewControllerAnimated:YES completion:nil];
}

- (void)userDidCancelPayPalProfileSharingViewController:(PayPalProfileSharingViewController *)profileSharingViewController
{
    
  self.successView.hidden = YES;
  [self dismissViewControllerAnimated:YES completion:nil];
}

- (void)sendProfileSharingAuthorizationToServer:(NSDictionary *)authorization
{
    
    
    
  // TODO: Send authorization to server
}


#pragma mark - Helpers

- (void)showSuccess {
    
  self.successView.hidden = NO;
  self.successView.alpha = 1.0f;
  [UIView beginAnimations:nil context:NULL];
  [UIView setAnimationDuration:0.5];
  [UIView setAnimationDelay:2.0];
  self.successView.alpha = 0.0f;
  [UIView commitAnimations];
}

#pragma mark - Flipside View Controller

- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender {
    
  if ([[segue identifier] isEqualToString:@"pushSettings"]) {
    [[segue destinationViewController] setDelegate:(id)self];
  }
}

@end





//
//  ZZFlipsideViewController.h
//  PayPal-iOS-SDK-Sample-App
//
//  Copyright (c) 2014, PayPal
//  All rights reserved.
//


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////




#import <UIKit/UIKit.h>
#import "PayPalMobile.h"
#import "AppDelegate.h"

@class ZZFlipsideViewController;

@protocol ZZFlipsideViewControllerDelegate

//- (BOOL)acceptCreditCards;
- (void)setAcceptCreditCards:(BOOL)processCreditCards;
//- (void)setPayPalEnvironment:(NSString *)environment;

@property(nonatomic, strong, readwrite) NSString *environment;
@property(nonatomic, strong, readwrite) NSString *resultText;

@end



#pragma mark -

@interface ZZFlipsideViewController : UIViewController


@property (nonatomic, strong) NSString *paymentString;
@property(weak, nonatomic) id <ZZFlipsideViewControllerDelegate> delegate;

@end



//
//  ZZFlipsideViewController.m
//  PayPal-iOS-SDK-Sample-App
//
//  Copyright (c) 2014, PayPal
//  All rights reserved.
//
//

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#import "ZZFlipsideViewController.h"
#import "ZZMainViewController.h"
#import <QuartzCore/QuartzCore.h>

@interface ZZFlipsideViewController ()

@property(nonatomic, strong, readwrite) IBOutlet UISegmentedControl *environmentSegmentedControl;
@property(nonatomic, strong, readwrite) IBOutlet UISwitch *acceptCreditCardsSwitch;
@property(nonatomic, strong, readwrite) IBOutlet UITextView *payPalResultTextView;
@property(nonatomic, strong, readwrite) IBOutlet UILabel *payPalResultLabel;
@end

@implementation ZZFlipsideViewController
AppDelegate *appDelegate;

- (void)awakeFromNib {
   // self.contentSizeForViewInPopover = CGSizeMake(320.0, 480.0);
    [super awakeFromNib];
}

- (void)viewDidLoad {
    
    [super viewDidLoad];
    
    
    appDelegate = (AppDelegate *)[[UIApplication sharedApplication]delegate];
    
}

- (void)logEnvironment {
    //self.delegate.acceptCreditCards = 1;
}

- (void)viewWillAppear:(BOOL)animated
{
    
    
    [self logEnvironment];
    int numberOfSegments = (int)self.environmentSegmentedControl.numberOfSegments;
    while (numberOfSegments--) {
        NSString *title = [self.environmentSegmentedControl titleForSegmentAtIndex:numberOfSegments];
        if ([[title lowercaseString] isEqualToString:self.delegate.environment]) {
            self.environmentSegmentedControl.selectedSegmentIndex = numberOfSegments;
            break;
        }
    }
    self.acceptCreditCardsSwitch.on = appDelegate.acceptcard;
    
    if ([self.delegate resultText]) {
        NSLog(@"***** self.delegate resultText: %@ *****", [self.delegate resultText]);
        self.payPalResultTextView.text = [[self.delegate resultText] stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
    } else {
        self.payPalResultTextView.hidden = YES;
        self.payPalResultLabel.hidden = YES;
    }
    self.payPalResultTextView.layer.cornerRadius = 8.0f;
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

#pragma mark - Actions

- (IBAction)environmentControlDidUpdate:(id)sender {
    
    if (self.environmentSegmentedControl == sender) {
        
        NSString *title =[[self.environmentSegmentedControl titleForSegmentAtIndex:self.environmentSegmentedControl.selectedSegmentIndex] lowercaseString] ;
        
        if( [title isEqualToString:@"mock"])
        {
            appDelegate.environment = @"mock";
        }
        else if ([title isEqualToString:@"sandbox"])
        {
            appDelegate.environment = @"sandbox";
        }
        else if ([title isEqualToString:@"live"])
        {
            appDelegate.environment = @"live";
        }
    }
    [self logEnvironment];
}


-(IBAction)goToBack:(UIButton *)sender
{
    [self.navigationController popViewControllerAnimated:YES];
}

- (IBAction)processCreditCardsChanged:(id)sender {
    
    [self.delegate setAcceptCreditCards:self.acceptCreditCardsSwitch.on];
    
    UISwitch *mySwitch = (UISwitch *)sender;
    if ([mySwitch isOn])
    {
        appDelegate.acceptcard =1;
    
    [self.delegate setAcceptCreditCards:self.acceptCreditCardsSwitch.on];
    }
    else
    {
        appDelegate.acceptcard =0;
        self.acceptCreditCardsSwitch.on = NO;
        [self.delegate setAcceptCreditCards:self.acceptCreditCardsSwitch.on];
    }
    [self logEnvironment];
}

@end

**Comment by bluk** [comment]
You may want to update to the latest PayPal iOS SDK `2.11.5` currently for Xcode 6.4 and `2.12.2` for Xcode 7. It seems you are on `2.9.0`.

```
PayPal SDK: Request has failed with error: invalid_client - System error (invalid_client). Please try again later. (401) | PayPal Debug-ID: <SomeDebugID> [live, PayPal iOS SDK 2.12.2] | Details: (
        {
        "error_description" = "Client Authentication failed";
    }
).
```

The above error occurs because your Client ID is not correct. For the code:

```
  [PayPalMobile initializeWithClientIdsForEnvironments:@{PayPalEnvironmentProduction : @"YOUR_CLIENT_ID_FOR_PRODUCTION",
                                                         PayPalEnvironmentSandbox : @"YOUR_CLIENT_ID_FOR_SANDBOX"}];
```

Ensure you have replaced `YOUR_CLIENT_ID_FOR_PRODUCTION` with your "live" production client ID. The client ID is different for the production vs. sandbox environment.

**Comment by Ha33y** [comment]
Hi Bluk,

  Thanks for immideate response. But i'm used different client ID for the production and sandbox. Is it necessary to use Paypal SDK 2.11.5 for Xcode 6.2 . Because,previously i used Paypal SDK 2.11.5. but i'm facing lot of issues.It doestn't allowd to integrate evan sandbox mode for testing. So,I'm used Paypal SDK 2.9.0  .It works fine for sandbox mode. but while changing from Sandbox to Live. above metioned issue occurred.  Any help will be great appraisable.

Thanks,
Harry

**Comment by bluk** [comment]
@Ha33y Can you describe in more detail what issue you have when you use PayPal SDK 2.11.5 and sandbox mode? I assume you're using the same code with both 2.9.0 and 2.11.5. Is there any additional error message or what is the behavior difference?

Try reading the [REST Payments Overview](https://developer.paypal.com/docs/integration/direct/rest-payments-overview/) and the [Manage Your Applications](https://developer.paypal.com/docs/integration/admin/manage-apps/). [developer.paypal.com](https://developer.paypal.com) is the general resource which you can use to learn more about the PayPal APIs.

**Comment by Ha33y** [comment]
Hi Bryant,

   Previously whenever i use Paypal SDK 2.11.5,lot errors occurs. i read
some blogs for that.They metioned 2.9 is useful.So, i go through that.It
works fine for sandbox. Is this issue occurs because of that version
only????


Please help me.

*Thanks and Regards,*

*Hareesh Gangadhara || iOS Developer*
*(8888110839)*



HN Web Marketing Pvt Ltd

5th Floor, Pyako Tower,
Above Domino's Pizza,
Karve Statute, Petrol Circle,

Kothrud,Pune - 411038

Email Id :-*info@hnwebmarketing.com <info@hnwebmarketing.com>*

**Comment by bluk** [comment]
@Ha33y Can you be more specific for the errors for `2.11.5`? We can't efficiently help you without more specific detail (either logs in the console or a description of the behavior). Thanks.

**Comment by Ha33y** [comment]
Hi Bryant,


   Actually Whatever ClientID i use, its wrong. That's why i get issues.
Thank you for great co-ordination.

*Thanks and Regards,*

*Hareesh Gangadhara || iOS Developer*
*(8888110839)*



HN Web Marketing Pvt Ltd

5th Floor, Pyako Tower,
Above Domino's Pizza,
Karve Statute, Petrol Circle,

Kothrud,Pune - 411038

Email Id :-*info@hnwebmarketing.com <info@hnwebmarketing.com>*

**Comment by bluk** [comment]
Glad it works.
