### ISSUE TITLE
Old SDK for IOS 9 Crash

### ISSUE THREAD

**Issue by jason469618528** [paypal/PayPal-iOS-SDK#335]

**Comment by jason469618528** [comment]
![0cdf8005-b473-4aba-9a55-73d3090ba127](https://cloud.githubusercontent.com/assets/4940053/10100175/3be1d87a-63c2-11e5-8679-5c194ff92d98.png)

**Comment by jason469618528** [comment]
![Uploading 1E5CEA0B-B894-4C17-A218-A516A7131856.png…]()

**Comment by jason469618528** [comment]
![1e5cea0b-b894-4c17-a218-a516a7131856](https://cloud.githubusercontent.com/assets/4940053/10100282/2902f5da-63c3-11e5-990a-e60c16afa0f5.png)

**Comment by jason469618528** [comment]
ios 8 is ok.

**Comment by bluk** [comment]
Hello, this seems like the same as issue #310 . Can you print the version of the SDK that you're using?
```
NSLog(@"%@", [PayPalMobile libraryVersion]);
```
You should use SDK version 2.11.5 if you're on Xcode 6.4 or 2.12.2 if you're on Xcode 7. If that does not resolve your issue, then please reopen. Thanks!

**Comment by jason469618528** [comment]
PayPal iOS SDK 2.2.1

**Comment by bluk** [comment]
@jason469618528 Thanks for the version info. Please try upgrading the SDK to see if it fixes your issue. Hope that helps.

**Comment by jason469618528** [comment]
yeah,Should I upgrade to Which of the verison?

**Comment by bluk** [comment]
I recommend `2.12.2` but only if you are on Xcode 7. If you are on Xcode 6.4, you can use `2.11.5`.
