### ISSUE TITLE
EMV?

### ISSUE THREAD

**Issue by centerax** [paypal/PayPal-iOS-SDK#337]
Does this SDK support the new [chip card reader](https://www.paypal.com/us/webapps/mpp/emv) ?

**Comment by ppmtscory** [comment]
@centerax no, this SDK is not compatible with the EMV Reader.  The [PPH SDK](https://github.com/paypal-mobile) is the one that will be compatible once it's publicly released in the US.

**Comment by centerax** [comment]
Thanks for your swift reply @ppmtscory . Cheers!
