### ISSUE TITLE
Payment Issue after updating latest one 

### ISSUE THREAD

**Issue by perlasivakrishna** [paypal/PayPal-iOS-SDK#338]
PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: 5dbd17fe64a97 [sandbox, PayPal iOS SDK 2.12.2]  

What are the reasons for this error..

buyer acnt and seller acnts are different 

Same thing happens in Demo App also...

But i was able to pay from another test accounts... 

So i think The error appears if same  email exists for both personal and business accounts. this might be reason. 

Thanks...

**Comment by digitalbrain** [comment]
Same problem here.

**Comment by pp-randy** [comment]
Adding StackOverflow link for reference:  http://stackoverflow.com/questions/32844636/payment-creation-error-in-paypal-ios-android-sdk

**Comment by ppmtscory** [comment]
Unfortunately there were quite a few issues with the sandbox environment yesterday that may have caused this.  Can you please test again and, if it's still happening, please provide the debug ID?

**Comment by perlasivakrishna** [comment]
It seems Solved,Not getting any issue. Thanks ..

**Comment by throughjhankar** [comment]
@perlasivakrishna how did you sovle the problem?

**Comment by perlasivakrishna** [comment]
No changes . It worked after few hours. I think there are issues in sandbox environment at that moment

**Comment by pp-randy** [comment]
@throughjhankar is you are still having an issue please create a new issue in this repository.

**Comment by pp-randy** [comment]
Locking this thread since this issue was caused by a temporary system issue at the time.  Please file a new issue if you receive this error.
