### ISSUE TITLE
File too big for Github Enterprise

### ISSUE THREAD

**Issue by plu** [paypal/PayPal-iOS-SDK#339]
Hi,

we're committing our `./Pods` folder to git. Unfortunately there's a file size limit on Github Enterprise:

`remote: error: File Pods/PayPal-iOS-SDK/CardIO/libCardIO.a is 201.95 MB; this exceeds GitHub Enterprise's file size limit of 100.00 MB`

Just want to make you aware of this issue, maybe other consumers of your SDK will run into the same problem.

Cheers,
Johannes

**Comment by Legoless** [comment]
We've just run into this issue as well. We're using CI to build this and we are commiting pods. And I don't want app size increased for 250MB just because we use a PayPal SDK? Makes no sense...

**Comment by bluk** [comment]
We are looking into this issue and will try to reduce the file size.

**Comment by tomwhipple** [comment]
Enabling BitCode causes the distributed on-device app to be smaller, binary libraries become much larger than was previously the case. Card.io is already big, so when BitCode is enabled, the library size gets much bigger. We have split out that library separately, so if you aren't using card.io you can remove it.

But as @bluk points out, we'll see if we can reduce the size somewhat.

**Comment by alpi** [comment]
AFAIK there is (sadly) no possibility to just remove the card.io part and don't use it at the moment, so i really hope we can get a solution for this soon.

**Comment by tomwhipple** [comment]
card.io is large due to the number of digit models it uses for pattern recognition. Making significant changes will be a significant amount of work. Unfortunately we can't prioritize that right now.

**Comment by plu** [comment]
https://git-lfs.github.com/

**Comment by willlarche** [comment]
+1

**Comment by xareelee** [comment]
+1

**Comment by ksylvest** [comment]
+1

**Comment by barneychen** [comment]
+1

**Comment by ankushsdei** [comment]
+1

**Comment by bluk** [comment]
[Release 2.12.4](https://github.com/paypal/PayPal-iOS-SDK/releases) has now split the libCardIO.a into separate libraries so that the individual files are under 100MB to allow easier GitHub (Enterprise) uploads. Note you should link to `libPayPalMobile.a`, `libCardIO.a`, `libopencv_core.a`, and `libopencv_imgproc.a` for your app now. Thank you for your patience.

**Comment by willlarche** [comment]
Thank you!

**Comment by plu** [comment]
great, thanks! :)
