### ISSUE TITLE
Payment Error in Sandbox Environment

### ISSUE THREAD

**Issue by NirmitDagly** [paypal/PayPal-iOS-SDK#342]
Hello,
Currently, I am trying to make Payment from Sample app of PayPal using SDK version 2.12.3. I am using XCode 7.0. While I am trying to make payment in Sandbox Environment, I am getting continuously this error as seen in attached file. Please help me to solve it out.

Regards,
Nirmit
![c25056c9f42bcc4144a17347088c25802d990e77ab0382eb4dpimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/8401881/10278144/8919d058-6b78-11e5-85ce-8d389c02cf06.jpg)

**Comment by NirmitDagly** [comment]
Also, App crashed when I click on the button 'Pay with Card'. The pre-processor macro has set to 1 and the switch is also enabled to accept payments form Credit Cards. Even there are no logs which displays why the app has crashed.

**Comment by bluk** [comment]
Seems there is more info in #343 so will close as a duplicate.
