### ISSUE TITLE
Payment issue with credit card

### ISSUE THREAD

**Issue by NirmitDagly** [paypal/PayPal-iOS-SDK#343]
Hello,
I am trying to make payments with credit card in Sandbox environment. I am constantly getting error like this.

PayPal SDK: Request has failed with error: UNKNOWN_ERROR - System error. Please try again later. (400) | PayPal Debug-ID: 4861c52492030 [sandbox, PayPal iOS SDK 2.12.3]

The debug id is 4861c52492030.

Please note that I am using my sandbox credentials to pay the payments.

Also, The Discover card is not activating for somehow.

Please tell me how can I solve this issue & get successful response of Payment.

**Comment by bluk** [comment]
@NirmitDagly It looks like you're trying to create a payment using an account whose country (India in this case) is not currently supported for PayPal REST payments. Please refer to [Country & Currency Support for PayPal REST API Payments](https://developer.paypal.com/webapps/developer/docs/integration/direct/rest_api_payment_country_currency_support/) for specific country support. Also note that domestic payments are currently not allowed for India. Hope that helps.
