### ISSUE TITLE
Accept Credit Cards disabled

### ISSUE THREAD

**Issue by weilunc** [paypal/PayPal-iOS-SDK#344]
I'm new to Paypal SDK. I was testing the demo app and I realized in Settings, the "Accept Credit Cards" was disabled. Anyone know how to enable this feature?

Really appreciate it!
![acceptcd](https://cloud.githubusercontent.com/assets/15023535/10354617/73707622-6d16-11e5-9173-2189f6221c19.png)

**Comment by bluk** [comment]
You will need to use the `PayPal-iOS-SDK+cardio-Sample-App` target. For your application, you will need to link to the `libCardIO.a` library in addition to the `libPayPalMobile.a` library.

**Comment by weilunc** [comment]
Thanks for answering my question, bluk. But I'm pretty sure I did those already.

**Comment by bluk** [comment]
Are you sure you are selecting the `PayPal-iOS-SDK+cardio-Sample-App` target in the upper left area of Xcode to launch?

<img width="449" alt="screen shot 2015-10-08 at 4 24 01 pm" src="https://cloud.githubusercontent.com/assets/94150/10380357/06246a88-6dd9-11e5-9761-4e510df21131.png">

**Comment by weilunc** [comment]
Thanks bluk! I figure it out myself.

**Comment by ppmtscory** [comment]
Closing per your last message.
