### ISSUE TITLE
Support for card swiper?

### ISSUE THREAD

**Issue by yjzar** [paypal/PayPal-iOS-SDK#346]
From my initial browsing, it seems that the PayPal Here SDK has support for the card swiper. Does this SDK support this as well (and by extension, does https://github.com/paypal/PayPal-Cordova-Plugin support the swiper?)?

If so, is the new chip card reader supported?

**Comment by ppmtscory** [comment]
@yjzar this SDK does not support the card swiper - only the PPH SDK does which can be found [here](https://github.com/paypal-mobile).
