### ISSUE TITLE
Error in duplicate Files

### ISSUE THREAD

**Issue by syedrazackimran** [paypal/PayPal-iOS-SDK#347]
duplicate symbols for architecture x86_64 , i imported all sdk file and frameworks, and also changes in build setting . facing this issues , kindly help me out
![screen shot 2015-10-09 at 7 37 08 pm](https://cloud.githubusercontent.com/assets/15051045/10395931/30ab9ac6-6ebd-11e5-893d-1c9ea03242da.png)

**Comment by bluk** [comment]
Can you please let us know which version of Xcode you are using and the version of the PayPal library? Thanks.

**Comment by bluk** [comment]
If you are still seeing this issue with the latest release, please reopen and provide the version of Xcode and the version of the PayPal library. Thanks!

**Comment by syedrazackimran** [comment]
hi

sorry for the delay replied , i solved that issues, i forget change in
build setting "NO COMMON BLOCK" . thanks for replying .
