### ISSUE TITLE
Where can I pass Receiver email ?

### ISSUE THREAD

**Issue by ioskxf** [paypal/PayPal-iOS-SDK#350]
Where can I pass Receiver email that is with old SDK?

**Comment by bluk** [comment]
The credentials (client id/secret) you use will identify your PayPal account as the receiver. See the [Developer Documentation](https://developer.paypal.com/) for [Managing your applications](https://developer.paypal.com/docs/integration/admin/manage-apps/) to get your credentials.

**Comment by ppmtscory** [comment]
What @bluk stated stands true as Third Party payments are not supported in this SDK currently.
