### ISSUE TITLE
initializeWithClientIdsForEnvironments crashes on iOS 6

### ISSUE THREAD

**Issue by RedBlueThing** [paypal/PayPal-iOS-SDK#351]
You are calling initWithBase64EncodedData:options: on NSData which is only available in iOS7:

https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSData_Class/index.html#//apple_ref/occ/instm/NSData/initWithBase64EncodedData:options:

**Comment by bluk** [comment]
[Release 2.12.4](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.12.4) should fix your issue. Hope that helps.

**Comment by RedBlueThing** [comment]
Thanks @bluk I'll give it a go.
