### ISSUE TITLE
webhook not called while paid using App SDK

### ISSUE THREAD

**Issue by tokikanno** [paypal/PayPal-iOS-SDK#352]
We're now integrating the PayPal payment into our website and app.

On the website, the webhook triggered correctly after we paid by PayPal.
But while using our app (both ios and android), there's no webhook called after paid by PayPal.

Both website and app payment are using the same client id / payment intend (sale), but only payments from the website get the webhook called.

**Comment by avidas** [comment]
@tokikanno how are you implementing the webhooks on your side, are you using one of the PayPal server sdks? Do you have any debug ids for completed payments from the mobile side that did not get an webhook notification?

**Comment by tokikanno** [comment]
@avidas : 

The problem is we didn't get the webhook events, not we can't receive and verify our webhook events.

Our server built with Django + PayPal Python REST SDK 
And we could receive and verify webhooks triggered by web PayPal payments using our server without any problem.

About the iOS / android App, we use both official PayPal mobile SDK download from github.
We could create and complete payments on both devices, but we didn't receive the PAYMENT COMPLETE webhook triggered by the app payments.

**Comment by tokikanno** [comment]
About the debug_id, I only get the debug_id when I encountered sadnbox server crash, or will the Payment / Sale id of our app payments help ?

**Comment by avidas** [comment]
Hey @tokikanno that could help as well.

**Comment by tokikanno** [comment]
@avidas 

For generating a fresh payment id, we've tried the iOS payment process again this morning, the webhook now called correctly with in 30 secs after our mobile web payments made.

I think there should be some server side issues for the mobile app webhook mechanism, because we didn't change anything in our app or server.

We'll also test the same process with our android app this afternoon, if both ios and android client work fine, then I think this case will be closed.

**Comment by tokikanno** [comment]
The android app also passed the webhook test(although the webhook response time is far more longer than iOS app). So I think it should be the server side problem.

Will close this issue.
