### ISSUE TITLE
PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 8493c45ebf1b4 [sandbox, PayPal iOS SDK 2.11.3]

### ISSUE THREAD

**Issue by githubmss** [paypal/PayPal-iOS-SDK#356]
Hello Guys,
I am using phone gap sample application and i am using sandbox environment but still getting this error  
PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 8493c45ebf1b4 [sandbox, PayPal iOS SDK 2.11.3]
Please help

**Comment by bluk** [comment]
This is the same issue as #355 so will close as a duplicate.

**Comment by KartikSinghBhadoriya** [comment]
I am facing same issue before 2 hours it's working and now I switch live to sandbox it's give me this error

PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 39c25d213574c, 39c25d213574c [sandbox, PayPal iOS SDK 2.14.2]

Please Help me ASAP

**Comment by 34tm4n** [comment]
I am also facing this same issue in sandbox environment from last 2 days and not fixed yet.

PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 3c717589d88c5, 3c717589d88c5 [sandbox, PayPal iOS SDK 2.14.2]

Please help me with it.

**Comment by adrianharris** [comment]
hi I am experiencing this exact same issue today - thanks

**Comment by anuragbhai** [comment]
Hi all,  i am also facing this issue (500) in Paypal iOS SDK version 2.16.1. Is there any update to solve this issue?

**Comment by bluk** [comment]
@anuragbhai As mentioned in the other issue, the Internal Server error is a generic error. If you are encountering this error, please create a new issue with details like your PayPal-Debug-ID and logs. If you are encountering this issue on live production, please open a ticket with [Merchant Technical Support](https://www.paypal-techsupport.com).
