### ISSUE TITLE
INTERNAL_SERVICE_ERROR - System error

### ISSUE THREAD

**Issue by swtkshk** [paypal/PayPal-iOS-SDK#357]
I am getting the following error in the sandbox mode:
PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 52328b0aa0fdc [sandbox, PayPal iOS SDK 2.12.2]
2015-10-30 14:52:41.015 bestAttempt[28510:132150] PayPal Payment Canceled

**Comment by bluk** [comment]
This is the same issue as #355 so will close as a duplicate.

**Comment by NimaiUser** [comment]
Still,I am facing this issue

**PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: b1ee54b75aaf [sandbox, PayPal iOS SDK 2.17.0]**
