### ISSUE TITLE
Installation with CocoaPods without cardIO

### ISSUE THREAD

**Issue by loryhuz** [paypal/PayPal-iOS-SDK#358]
Hello,

I want to use Paypal SDK without Card.IO (thought it was optional) but when building my project after adding ```pod 'PayPal-iOS-SDK'``` I've the following error:

```(null): Library not found for -lCardIO```

Is there a workaround to keep using Paypal with cocoapods without the link to CardIO ?

Thanks in advance.

**Comment by bluk** [comment]
The CocoaPods spec currently specifies both as `vendored_libraries`. I'm not sure if you can override that. Will see if we can provide a subspec that doesn't have CardIO in it.

**Comment by bluk** [comment]
Hi, this should be fixed in the CocoaPods 2.12.5 release. You can use `PayPal-iOS-SDK/Core` for just the PayPal libraries.
