### ISSUE TITLE
Carsh occured with PaywithCard option Selection

### ISSUE THREAD

**Issue by madhuc45** [paypal/PayPal-iOS-SDK#359]
Hi Team,

I am using latest PayPal iOS SDK with V 2.12.4. After Presenting 'PayPalPaymentViewController' Successfully, When we select an option of 'Pay with Card'  application getting crashed with error message saying 

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present a nil modal view controller on target <PayPalPaymentViewController: 0x7f812285f200
Environment: live/Sandbox(Both cases)
languageOrLocale: en-US
>
Due to unavailability of source code, Unable to trace the problem.
Please let me know the issue and resolve my issue ASAP.

Thanks in Advance,
Madhu.

**Comment by bluk** [comment]
@madhuc45 Are you linking with the CardIO libraries in your application? You will now need to link with `libCardIO.a` and the 2 other OpenCV libraries in addition to the `libPayPalMobile.a` static library.

**Comment by madhuc45** [comment]
@bluk Not Integrated other libraries, Because they are not mentioned anywhere in Sample example as well. Does we need to integrate in our app?

**Comment by bluk** [comment]
@madhuc45 Is it the same exception? Also, when you tried the Sample Application, did you try the `PayPal-iOS-SDK+cardio-Sample-App` target? There are 2 targets to demonstrate behavior with card.io and without card.io. The Sample App should work out of the box without modification.

**Comment by bluk** [comment]
@madhuc45 Please reopen if you still have issues (and if so, please provide the information in the last comment).

**Comment by chandavarshailesh** [comment]
This crash still exist , i have even checked the sample app tapping on PaywithCard crashes the app saying erminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present a nil modal view controller on target.

**Comment by qu4sar** [comment]
Same problem here! I have integrate all the static libraries that you have mentioned . There is a sandbox problem ? How i can fix ?

**Comment by bluk** [comment]
@qu4sar Can you please open a new issue with more details (e.g. which version of the SDK you are using)? Thanks!

**Comment by kathiriyaketan57** [comment]
Hello 

I am using SDK version: PayPal iOS SDK 2.17.0

and i get crash problem when i click on "Pay with Card" button . I am testing it in simulator.

Error :::::

PayPal-iOS-SDK-Sample-App[1516:48759] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present a nil modal view controller on target <PayPalPaymentViewController: 0x7fce7406ce00
Environment: sandbox
languageOrLocale: en

**Comment by xiaoleih41** [comment]
Can you reproduce this error under our [sample code](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/single_payment.md)

**Comment by ignivayogesh** [comment]
Hello Please add 
libopencv_imgproc.a
libopencv_core.a
libCardIO.a
Into "Linked Framework and Libraries."

And also add.
"$(SRCROOT)/../CardIO"
into Library search path.

**Comment by xiaoleih41** [comment]
@ignivayogesh Could you please submit a pull request?
