### ISSUE TITLE
INTERNAL_SERVICE_ERROR - SDK 2.12.3

### ISSUE THREAD

**Issue by zinnuree** [paypal/PayPal-iOS-SDK#361]
Last few days, I have been receiving following error just after I present the PayPalPaymentViewController

_payPalConfig.acceptCreditCards = NO;
_payPalConfig.languageOrLocale = [NSLocale preferredLanguages][0];
_payPalConfig.payPalShippingAddressOption = PayPalShippingAddressOptionPayPal;

[PayPalMobile preconnectWithEnvironment:PayPalEnvironmentProduction];

PayPalPayment *payment = [[PayPalPayment alloc] init];
// payment params configured here

PayPalPaymentViewController *paymentViewController = [[PayPalPaymentViewController alloc] initWithPayment:payment                                                                                                                                        configuration:self.payPalConfig
delegate:self];

[self presentViewController:paymentViewController animated:YES completion:nil];

The page shows up and then following error is displayed in the console - 

PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: c095d8fe52a1b [live, PayPal iOS SDK 2.12.3]

**Comment by bluk** [comment]
Is the error consistent for you and can you provide any other debug-ids? I tried a few different live production transactions, and they worked for me.

[Merchant Technical Support](https://www.paypal-techsupport.com) may also be able to help you with account specific issues.

**Comment by bluk** [comment]
Please reopen if this is still occurring and if you can provide any other debug-ids or information, that would be helpful. Thanks!

**Comment by zinnuree** [comment]
Unfortunately at my end, its happening all the time-

PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 4cd4efee8b0cf [live, PayPal iOS SDK 2.12.3]

PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: a90cf91db0c8c [live, PayPal iOS SDK 2.12.3]

**Comment by bluk** [comment]
There were changes to the identity service over the last few weeks. If this issue still occurs, please leave a comment with PayPal Debug IDs or contact [Merchant Technical Support](https://www.paypal-techsupport.com). Sorry for the late response.
