### ISSUE TITLE
Profile Sharing 401 Error

### ISSUE THREAD

**Issue by bopeola21** [paypal/PayPal-iOS-SDK#362]
Hi, 

I'm setting up Profile Sharing on my app and i have the mobile side set up, UI everything shows up fine also receiving the correct response (OAuth2 authorization code).

The problem I am having is when I send the authorization code to the server side in order to get the refresh and access token, in return. I am using Parse as a backend and they have what is called Cloud Code in order to run server side code. The language is Javascript, therefore "curl" does not work.

I am trying to convert the curl into something your servers will recognize. But I keep getting an 401 error. Any kind of help would be greatly appreciated, thanks!

    Parse.Cloud.define('getRefreshToken', function(request, response) {

       // request = {"code" : "xxxxx"};
	  Parse.Cloud.httpRequest({
 	       method: 'POST',
	  	url: 'https://api.paypal.com/v1/oauth2/token',
	  	headers: {
	  		'Content-Type': 'application/x-www-form-urlencoded',
	  		'client_id': 'secret'
	  	},

	  	body:       'grant_type=authorization_code&response_type=token&redirect_uri=urn:ietf:wg:oauth:2.0:oob&code=' + request.params.code,

	  	success: function(httpResponse) {
	  		 var res = JSON.parse(httpResponse.text);
	  		response.success(res.refresh_token);
	  	},

	  	error: function(httpResponse) {
	  		response.error('request failed with code' + httpResponse.status);
	  	}
     });
    });

**Comment by bluk** [comment]
The `"client_id": "secret"` is not a header key/value pair (`-u "client_id:secret"` in the curl example requests). You'll need to use an `Authorization` header with it being the corresponding `client_id:secret` values. You can read about the authentication headers here: https://developer.paypal.com/docs/api/auth-headers/

**Comment by bluk** [comment]
To be more clear, it's the HTTP Basic Auth encoding. So say the base64 encoded value of `client_id:secret` is `encoded_value`. Then the `Authorization` header value should be `Basic encoded_value`

**Comment by bopeola21** [comment]
Copying values from the example on the Paypal developer website, if I had:
client_id = EOJ2S-Z6OoN_le_KS1d75wsZ6y0SFdVsY9183IvxFyZp
secret = EClusMEUk8e9ihI7ZdVLF5cZ6y0SFdVsY9183IvxFyZp

My "client_id:secret" would be:
"EOJ2S-Z6OoN_le_KS1d75wsZ6y0SFdVsY9183IvxFyZp:EClusMEUk8e9ihI7ZdVLF5cZ6y0SFdVsY9183IvxFyZp"

And the Authorization header value would be:
Authorization: Bearer "EOJ2S-Z6OoN_le_KS1d75wsZ6y0SFdVsY9183IvxFyZp:EClusMEUk8e9ihI7ZdVLF5cZ6y0SFdVsY9183IvxFyZp"

Is this correct?

**Comment by bluk** [comment]
`Authorization: Basic RU9KMlMtWjZPb05fbGVfS1MxZDc1d3NaNnkwU0ZkVnNZOTE4M0l2eEZ5WnA6RUNsdXNNRVVrOGU5aWhJN1pkVkxGNWNaNnkwU0ZkVnNZOTE4M0l2eEZ5WnA=` should be the correct header to send.

The `client_id:secret` should be `EOJ2S-Z6OoN_le_KS1d75wsZ6y0SFdVsY9183IvxFyZp:EClusMEUk8e9ihI7ZdVLF5cZ6y0SFdVsY9183IvxFyZp` like you said. Then you need to base64 encode that value like HTTP Basic Auth does. So the base64 encoded value is `RU9KMlMtWjZPb05fbGVfS1MxZDc1d3NaNnkwU0ZkVnNZOTE4M0l2eEZ5WnA6RUNsdXNNRVVrOGU5aWhJN1pkVkxGNWNaNnkwU0ZkVnNZOTE4M0l2eEZ5WnA=`. Note also `Basic` instead of `Bearer`.

**Comment by bopeola21** [comment]
I'm still getting the 401 Error after i changed the "client_id:secret" to a base64 encoded value.

	  Parse.Cloud.httpRequest({

	  	method: 'POST',
	  	url: 'https://api.paypal.com/v1/oauth2/token',
	  	headers: {
                        // request.params['auth'] = my base64 encoded client_id:secret value
	  		'Authorization': 'Basic ' + request.params['auth'],
	  		'Content-Type': 'application/x-www-form-urlencoded'
	  	},

	  	body: 'grant_type=authorization_code&response_type=token&redirect_uri=urn:ietf:wg:oauth:2.0:oob&code=' + request.params['code'],

	  	success: function(httpResponse) {
	  		response.success(httpResponse);
	  	},

	  	error: function(httpResponse) {
	  		response.error('request failed with code' + httpResponse.status);
	  	}

	  });

    });

**Comment by bluk** [comment]
Are you able to manually run the curl request to get an access token?

My concern would be if the requests.param is not properly encoded/decoded.

On a side note, the mobile device should not have the base64 encoded value. It is best to have that value only on the server side.

**Comment by bopeola21** [comment]
The only thing I am able to obtain at the moment is the Authorization code after the user logs in through the mobile app. What I am getting stuck on is using the above code to receive the access token/refresh token.

Ok I will look into changing where I've stored the encoded value. Only reason I did it that way is because I'm an iOS guy and not too familiar with javascript, therefore it was the quickest way I knew how to convert in order to test.

**Comment by bopeola21** [comment]
I'm sure the Authorization code and the base64 encoded "client_id:secret" going into the http request is correct. I printed both values to make sure of this.

**Comment by bopeola21** [comment]
On top of everything you said that worked well, the last issue I had was my URL, it should have been 'https://api.sandbox.paypal.com/v1/oauth2/token'. Everything seems to be working fine now, thanks a bunch man seriously!!

**Comment by bluk** [comment]
Great! Glad it works.
