### ISSUE TITLE
PAYMENT_CREATION_ERROR Problem, can't find solutions, please help!

### ISSUE THREAD

**Issue by zzdjk6** [paypal/PayPal-iOS-SDK#364]
Debug-ID: eed506394ad34

I have set up this account "zzdjk6_PMY@gmail.com" which use MYR and have 8000 bulk in balance.
But when I try to request a payment on sandbox, it always give me PAYMENT_CREATION_ERROR with code 422.
Please let me know how to solve this problem?

Log here:

PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: eed506394ad34 [sandbox, PayPal iOS SDK 2.12.5]

**Comment by ppmtscory** [comment]
@zzdjk6 this has to do with the currency that you are using.  MYR is an 'in-country' currency only so your merchant account would also have to be a Malaysian account.  You can read more about our currency support [here](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/).

**Comment by zzdjk6** [comment]
@ppmtscory I'm sorry but I already add a business account with MY country - "zzdjk6-BMY@gmail.com", but how to setup it as my merchant account on sandbox? I still can't find a way to config it after reading related documents.

**Comment by zzdjk6** [comment]
@ppmtscory ok, I finally found that I can only assign 1 merchant account for 1 AppID, and only happen when creating AppID. Once my newly created AppID with "zzdjk6-BMY@gmail.com" as merchant account, using "zzdjk6_PMY@gmail.com" as buyer account is successful on sandbox. Thank you for your help :)

**Comment by ppmtscory** [comment]
Thanks for the update @zzdjk6 - glad you got it working.

**Comment by ksingh65** [comment]
Hi,

Even I am receiving the similar error: PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: 860371ba1427, 860371ba1427 [sandbox, PayPal iOS SDK 2.16.1]

**Comment by ppmtscory** [comment]
@ksingh65 for errors like this, please file a ticket with our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team as these are not SDK specific.  For your particular error, you're getting it because you're using the same account for the receiver and the sender.  You cannot pay yourself.
