### ISSUE TITLE
Official "Pay with Paypal"-Button

### ISSUE THREAD

**Issue by MichaelEckl** [paypal/PayPal-iOS-SDK#365]
Hello everybody,

i integrated the PayPal Mobile SDK in my app and it is working fine.
I'm looking for the official Paypal-Button for my iOS App.
All i found was this, but that's not for an iOS App and in the example from sdk is also used a normal button to trigger the payment:
https://www.paypal.com/buttons/select

Is there a official button "Pay with PayPal" i have to use in my app ?

Thank you,
Greetings,
Michael

**Comment by bluk** [comment]
I don't believe there is an official button, but it's a good idea for future enhancement.

**Comment by bluk** [comment]
If anyone is looking for this, the Braintree iOS SDK [provides vector art](https://github.com/braintree/braintree_ios/tree/master/BraintreeUIKit/Vector%20Art) for many different payment methods including PayPal which could possibly be used. [Braintree](https://www.braintreepayments.com) is a PayPal company which processes many different payment methods including PayPal.
