### ISSUE TITLE
Short description

### ISSUE THREAD

**Issue by LtrDan** [paypal/PayPal-iOS-SDK#367]
Hey, 2 questions:)
Is there a way to show 2 lines in the payment and then sum the amount?
- 2 shirts - 25$
-1 hat - 5$

total - 30$?

if no - is there a way to make the short description to break a line - because when i have long string - it looks like: 2 shirts and 1 hat with our br....(3 dots instead of the string)

Thank you,Dan

**Comment by bluk** [comment]
Thanks for the suggestion. We will look into enhancing this functionality.

**Comment by bluk** [comment]
[Version 2.14.4](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.14.4) will finally allow multiple lines in the short description.
