### ISSUE TITLE
Can't login in production env - Request has failed with error: AUTH_RC_RISK_FAILURE (400)

### ISSUE THREAD

**Issue by loryhuz** [paypal/PayPal-iOS-SDK#368]
Hi,

I've some issues with the Paypal iOS SDK. It was doing well in Sandbox, but when I switch to production mode I can't login to Paypal, I receive the following error:

PayPal SDK: Request has failed with error: AUTH_RC_RISK_FAILURE - Rejeté en raison d’un risque trop élevé. (400) | PayPal Debug-ID: c09ad23189347 [live, PayPal iOS SDK 2.12.7]

What are the reasons there is a too high risk ?

Thanks in advance,
Regards, lory.

**Comment by loryhuz** [comment]
You can delete this, my boss send me a wrong client id, sorry.

**Comment by ppmtscory** [comment]
@loryhuz thanks for the update!

**Comment by loryhuz** [comment]
I've now access to the Paypal account, I've created my own app and checked "allow users to login with their paypal account", and I still have this error.

**Comment by loryhuz** [comment]
I've created a new user account and it's working, but not with my real personal account (lory.huz@gmail.com).

I can login correctly on Paypal website with this login but not through iOS SDK

**Comment by ppmtscory** [comment]
@loryhuz it looks like we're detecting some inconsistencies with the login/access for your personal account.  For that account, you'll need to contact your local PayPal support team and have them take a look.  You can click 'Contact Us' at the bottom of any PayPal page for the local number.  I will also place a note in your account regarding what I see so you can reference that with the agent you speak with.  I'll be closing this now as it's not an issue with the SDK or your code.
