### ISSUE TITLE
Negative number decimal places

### ISSUE THREAD

**Issue by umarniz** [paypal/PayPal-iOS-SDK#369]
Hi,

I see a bug with adding discount coupons. Adding a negative item price complains about having too many decimal places even when there are no decimal places.

A negative value of "-150.00$" works fine. 
A negative value of "-151.00$" complains for too many decimal places.
A negative value of "-159.00$" complains for too many decimal places.
A negative value of "-160.00$" works fine.

**Comment by bluk** [comment]
Thanks for the report. The issue should be fixed in release [2.12.9](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.12.9).
