### ISSUE TITLE
paypal receiver

### ISSUE THREAD

**Issue by HiteshArtoon** [paypal/PayPal-iOS-SDK#370]
how to set receiver email address.

**Comment by ppmtscory** [comment]
The receiver is determined by the Client ID that's used in the SDK.  I assume that you are referring to Parallel or Chained payments from our Classic APIs.  Currently there's not a way to set a receiver email to facilitate the transfer of funds to different merchant accounts.

**Comment by HiteshArtoon** [comment]
tahnks.
