### ISSUE TITLE
paypal 2.4.0

### ISSUE THREAD

**Issue by syedrazackimran** [paypal/PayPal-iOS-SDK#371]
![screen shot 2015-12-29 at 11 00 14 am](https://cloud.githubusercontent.com/assets/15051045/12030021/81ee41e6-ae1d-11e5-8968-878725d26611.png)

kindly solve my issues .. ASAP. XCODE 7.0 iOS 9.0

**Comment by bluk** [comment]
Please try the latest version [2.12.9](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.12.9) to fix the issues described.

**Comment by bluk** [comment]
Please leave a comment or reopen if the latest SDK does not fix your issue.
