### ISSUE TITLE
UIAppearance

### ISSUE THREAD

**Issue by plu** [paypal/PayPal-iOS-SDK#373]
Hi,

I've read this section in the README:

`Specifically, if you are using UIAppearance to modify the appearance of any UI elements in your app, you should reverse those changes prior to presenting our viewcontroller, and set them again after dismissing the viewcontroller.`

I find it a bit cumbersome that consumers of your SDK have to do this. The consumers shouldn't have to worry about this. Instead the SDK could make sure that it sets all colors and font sizes to be displayed in your desired way.

What do you think about this?

Thanks,
plu

**Comment by bluk** [comment]
We can try looking into this. I believe the reason why this is done is partially because we wouldn't know all of the possible things to restore (only you would depending on the configuration you use).

**Comment by plu** [comment]
Hey @bluk,

thank you for coming back on this issue. I have created a sample project that includes a real world `UIAppearance` setup of the [eBay Kleinanzeigen iOS app](https://itunes.apple.com/de/app/ebay-kleinanzeigen-kostenlos./id382596778?mt=8):

[PayPalAppearance](https://github.com/plu/PayPalAppearance)

In the screenshots you can see how our `UIAppearance` setup is affecting the PayPal-iOS-SDK:

* https://raw.githubusercontent.com/plu/PayPalAppearance/master/Screenshots/with_appearance/app.png
* https://raw.githubusercontent.com/plu/PayPalAppearance/master/Screenshots/with_appearance/paypal1.png
* https://raw.githubusercontent.com/plu/PayPalAppearance/master/Screenshots/with_appearance/paypal2.png
* https://raw.githubusercontent.com/plu/PayPalAppearance/master/Screenshots/with_appearance/paypal3.png

vs.

* https://raw.githubusercontent.com/plu/PayPalAppearance/master/Screenshots/without_appearance/app.png
* https://raw.githubusercontent.com/plu/PayPalAppearance/master/Screenshots/without_appearance/paypal1.png
* https://raw.githubusercontent.com/plu/PayPalAppearance/master/Screenshots/without_appearance/paypal2.png
* https://raw.githubusercontent.com/plu/PayPalAppearance/master/Screenshots/without_appearance/paypal3.png

**Comment by iamabhiee** [comment]
Any updates for this issue?

**Comment by bluk** [comment]
No real updates. Identifying all of the different possible UIAppearance changes made by a merchant app and then correctly "undo"-ing them and then "redo"ing them is difficult without lots of possible breaking behavior. I'll definitely keep this in mind if anyone has any ideas or if I run across anything, but it is probably safer for you to make the UIAppearance calls as appropriate.
