### ISSUE TITLE
PayPal SDK: PayPalPayment not processable: 'AMD' is not a supported currency code.

### ISSUE THREAD

**Issue by LusineSargsyan** [paypal/PayPal-iOS-SDK#374]
Hello all

I'm developing an application with PayPal SDK and I want to do transfer with Armenian Drams. But I can't. But with USD or EUR county codes it works fine

Exception 
PayPalPayment *payment =  [PayPalPayment paymentWithAmount:amount currencyCode:@"ARM" shortDescription:@"myShortDesc" intent:PayPalPaymentIntentAuthorize];

Console:
PayPal SDK: PayPalPayment not processable: 'AMD' is not a supported currency code.

Best Regards
Lusine

**Comment by bluk** [comment]
I do not believe that Armenian Drams is supported via the REST API today (which the mSDK is based upon). You can visit the list of [supported currencies on the PayPal Developer Portal](https://developer.paypal.com/docs/integration/direct/rest_api_payment_country_currency_support/).

**Comment by LusineSargsyan** [comment]
thank you
