### ISSUE TITLE
JavaScript (Parse Cloud Code) Token Request results in "invalid_authz_code\\\"

### ISSUE THREAD

**Issue by JannesKlaas** [paypal/PayPal-iOS-SDK#376]
Good morning, I am struggling with accessing the REST API from Parse's Cloud code. 
I am using the following request (with the ClientID:Secret from https://developer.paypal.com/docs/integration/direct/make-your-first-call/):
```javascript
Parse.Cloud.httpRequest({
    method: 'POST',
    url: 'https://api.sandbox.paypal.com/v1/oauth2/token',
    headers: {           
        'Authorization': 'Basic RU9KMlMtWjZPb05fbGVfS1MxZDc1d3NaNnkwU0ZkVnNZOTE4M0l2eEZ5WnA6RUNsdXNNRVVrOGU5aWhJN1pkVkxGNWNaNnkwU0ZkVnNZOTE4M0l2eEZ5WnA=',
        'content-Type': 'application/x-www-form-urlencoded'
    },
    body: 'grant_type=authorization_code',
    success: function(httpResponse) {
        response.success(httpResponse);
    },
    error: function(httpResponse) {
        response.error(httpResponse);
    }
  });
```
It returns a 401, "Authorization Code is invalid\\\", "invalid_authz_code\, "Paypal-Debug-Id\":\"19de1fd3e092\". Same when I use the sandbox credentials of my app. I even created a new app to use its credentials with the same result. If I do a curl from the terminal of my mac it works fine. At my wits' end here, thanks a million for your help, Jannes

**Comment by bluk** [comment]
Are you trying to get a general access token or [trying to exchange an authorization code for an access token](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_server.md#exchange-authorization-code-for-refresh--access-tokens)? Your code seems to indicate you want an `authorization_code` exchanged but the link seems to be for the general token (where it should be `client_credentials` instead).

If you are looking to exchange an authorization code for an access token, I would double check the rest of the parameters that you're passing in the body are properly included.

**Comment by JannesKlaas** [comment]
Hi man, you are right. I mixed that up. I want to get the client_credentials and had the body set wrong. Args, stupid. Thanks a million man! Changed the code to:
```javascript
Parse.Cloud.httpRequest({

    method: 'POST',
    url: 'https://api.sandbox.paypal.com/v1/oauth2/token',
    headers: {     
    // Add credentials here      
        'Authorization': 'Basic BASE64ENCODED_CREDENTIALS',
        'content-Type': 'application/x-www-form-urlencoded'
    },
    // This is important
    body: 'grant_type=client_credentials',

    success: function(httpResponse) {
        response.success(httpResponse.data.access_token);
    },

    error: function(httpResponse) {
        response.error(httpResponse);
    }

  });
```
Thanks again!

**Comment by bluk** [comment]
Glad it works!
