### ISSUE TITLE
can I get the user's account(email maybe) when he/she login in PayPalPaymentViewController?

### ISSUE THREAD

**Issue by blackmatch** [paypal/PayPal-iOS-SDK#377]
hello, 

I want to get the user's account when he/she login to pay at the PayPalPaymentViewController. Can I ? Is any property or method to get that?

**Comment by bluk** [comment]
You cannot get the PayPal login account for security reasons. Is there a reason why you want the actual login?

You can get some PayPal profile/customer information by integrating the [Profile Sharing Mobile Integration](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/profile_sharing_mobile.md) and having your customers consent to sharing the information.
