### ISSUE TITLE
Check Payment Confirmations via Credit Card

### ISSUE THREAD

**Issue by lvandyk** [paypal/PayPal-iOS-SDK#378]
As far as I understand any payment via a Paypal account will invoke a webhook. How do credit card payments get verified on the server side? The docs say CC payments don't invoke webhooks yet.

Do I need to use the REST API to check payment details? This means I will need to setup a CRON (every minute) that loops through all unpaid items and checks if they were finally approved?

**Comment by bluk** [comment]
What type of verification are you looking for?

The [Verify a mobile payment](https://developer.paypal.com/webapps/developer/docs/integration/mobile/verify-mobile-payment/) provides some information on how to generally verify a payment. Presumably, after the payment flow is completed on the mobile device, you will notify your server details about the payment. At that time, you can look up the payment details and check things like the `state` being `approved`.

**Comment by lvandyk** [comment]
Yes thats exactly what I am doing. Getting an access token then verifying using "/payments/payment/<PAY-ID-HERE>". The problem is I am scared the payment is not yet approved when I tell my server the payment has been made. I was hoping I could use a webhook to tell me, but I have to check every minute using a CRON.
