### ISSUE TITLE
Delegate payPalFuturePaymentDidCancel dispatched when user enters wrong credentials.

### ISSUE THREAD

**Issue by jonathanpdiaz** [paypal/PayPal-iOS-SDK#380]
Hello

I got a ticket asking me to NOT dismiss the PaypalFuturePaymentViewController if the users enters wrong credentials. After some debugging I realised that the payPalFuturePaymentDidCancel delegate is been called after display the alert with the "Invalid user credentials" message.

PayPal SDK: Request has failed with error: invalid_user - Incorrect username/password. Please try again. (401) | PayPal Debug-ID: 5618a60d474f2 [sandbox, PayPal iOS SDK 2.11.5] | Details: (
        {
        "error_description" = "Invalid user credentials";
    }
).

I can't see any other public property or delegate to handle this particular case. I do need to handle the payPalFuturePaymentDidCancel as I'm doing it now to not keep the user stuck on the paypal payment screen after he hits the cancel button.

Can you guys provide me with a work around? 

Thanks. Jony.

**Comment by bluk** [comment]
Hi, can you try using the latest [PayPal iOS SDK release](https://github.com/paypal/PayPal-iOS-SDK/releases)? Currently it is version `2.13.0`. In particular, version `2.12.6` fixed a bug with invalid credentials where some authentication views were incorrectly being dismissed with wrong credentials.

**Comment by jonathanpdiaz** [comment]
@bluk thanks for the quick answer.

I did some test and it is doing what you said. Its preventing the delegate to be call. But now its not displaying the error as it was before (v 2.11.x). Now It shakes the fields. 
Could you confirm me that the only reason that cause the fields to shake is because of wrong credentials? Is there a way to get this error in a delegate to display a custom error in case is required?

Thanks. Jony.

**Comment by bluk** [comment]
Yes, it shakes the view because of wrong credentials. There are other error flows that do pop up alert views.

There is not a way to display a custom error message. I guess I wonder what kind of custom error message you would want to display.

**Comment by jonathanpdiaz** [comment]
The issue is that the previous version of the SDK displayed an alert with the error. Now, it only shakes de UI. 
Our app targets a set of users that are not advanced users, where an alert with the message fits better. A shake could cause them to confuse what the real problem is. Or not even see it.
That's the reason why I was wondering for a delegate to display a an error (something basic like "wrong credentials" inside an alert).
If the response for wrong credentials is a shake and it can be tweak, We might keep the current version (2.11.x) to keep a more verbose UX. And wait for a possible work around later, when an update of the sdk is required.

Thanks. Jony.

**Comment by bluk** [comment]
Ah gotcha. I added a bit more detail to my earlier comment but the shaking behavior existed before `2.12.6` but a bug caused the view to not shake and to dismiss the view controller instead. I'll add this as a future enhancement. It might be that there will be a choice between an alert and a shake but the text may have to be hardcoded. Will investigate.

**Comment by jonathanpdiaz** [comment]
Excellent.

We don't need the custom text on errors.
Your provided solution would work perfect in our case.

As side note, In the past, we bumped with this shake response, but it was for a pin that was blocked after a certain number of retries. We were able to see the error in the log on debug mode, but the UX was getting stuck on the log in thinking that app was not working properly, because they knew that their ping was correct.
With an option to display the error, this kind of issues could cause less confusion to the user.

Thanks again.

**Comment by bluk** [comment]
This issue should be fixed in [release 2.14.3](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.14.3). If it is still an issue, please leave a comment. Thanks for your patience.

**Comment by Miteshimmply** [comment]
Issue is still pending in  2.15.1

**Comment by bluk** [comment]
@Miteshimmply Did you set the `PayPalConfiguration.disableShakeAnimations` property to `YES`? If you did and it does not disable the animation, please open a new issue. Thanks.

**Comment by Miteshimmply** [comment]
Thanks It is working
