### ISSUE TITLE
Will Apple accept if this sdk used for monthly subscription of our cloud storage 

### ISSUE THREAD

**Issue by zufry** [paypal/PayPal-iOS-SDK#383]
I use this library to capture payment for the monthly subscription of our cloud storage in my iOS application.
I need to know whether my App will be accepted by Apple or not.
Please let me know you kind opinion on this.

Thanks in advance.

**Comment by imdevin567** [comment]
I'm not a contributor here, but I'm almost positive that will get rejected. Apple requires all digital goods and services to be purchased through in-app purchases, including monthly subscriptions.

Check out apps like Evernote and Spotify. Evernote specifically went through every possible iteration to avoid using IAP: linking to their website, removing the actual link and just showing the URL, opening in a web view, etc. Finally they just decided to bite the bullet and use IAP. Spotify in particular charges a few extra dollars a month to cover Apple's 30% fee.

**Comment by bluk** [comment]
This question is ultimately up to Apple, and you should reach out to the Apple developer relations to understand what is acceptable or not.

( My understanding from other apps/services correlates with what @imdevin567 has said. )
