### ISSUE TITLE
PAYER_ACTION_REQUIRED

### ISSUE THREAD

**Issue by Krishna7357** [paypal/PayPal-iOS-SDK#386]
Hi i have got the one issue PAYER_ACTION_REQUIRED, i am working in Sandbox mode only when I try to pay in iOS sdk it's showing me the alert "PAYER_ACTION_REQUIRED"

Please Give suggestions

**Comment by bluk** [comment]
@Krishna7357 Which version of the mSDK are you using?

**Comment by Krishna7357** [comment]
Thanks for your quick response... And the mistake was from my side. Account
details not added. Sry for the query It was solved. Thank you

**Comment by bluk** [comment]
Thanks for the followup.
