### ISSUE TITLE
Integrate both BrainTree SDK and Paypal SDK in one app

### ISSUE THREAD

**Issue by ankits16** [paypal/PayPal-iOS-SDK#387]
I am trying to integrate both braintree and paypal native in my application. I user cocoapods to integrate braintree and manual integration for paypal, but when I compile the code I see

91 duplicate symbols for architecture x86_64
I tried integrating these library individually in different project and they are working fine if I integrate them in one project I get this error please help me out to resolve this.

Thanks Ankit

**Comment by bluk** [comment]
Which version of the Braintree SDK are you trying to integrate? I assume 3.x. Are you trying to use Braintree for some functionality (but not PayPal)? If so, you may try using the Braintree CocoaPods subspecs and excluding the `Braintree/PayPal` one.

**Comment by ankits16** [comment]
trying to integrate 4.X, I need paypal in Braintree as well

**Comment by ankits16** [comment]
trying to integrate 4.X, I need paypal in Braintree as well

**Comment by bluk** [comment]
@ankits16 I tried using Braintree 4.x with the PayPal mSDK and did see the 91 duplicate symbols issue. There is some similar code between the 2 SDKs which is causing the issue.

If you don't mind, is there a reason why you want to use both SDKs? (e.g. is there a use case you need which the PayPal mSDK provides but the Braintree mSDK does not?)

**Comment by intelliot** [comment]
@ankits16 Just in case it's not clear, the [Braintree iOS SDK](https://github.com/braintree/braintree_ios/) includes its own built-in support for [PayPal - see the docs here](https://developers.braintreepayments.com/guides/paypal/overview/ios/v4). In other words, you can use Braintree to accept PayPal without using the PayPal-iOS-SDK :)

**Comment by bluk** [comment]
Depending on your use case, it is probably best to use only one of the SDKs. If there is a feature you want from the PayPal SDK that is missing from the Braintree SDK, please leave a comment so we can understand the use case better. Thanks.

**Comment by jasvindersingh-evon** [comment]
Hi,

Why I need to include PayPal SDK separately is because I have to use split payment. I tried adding a service fee through Braintree SDK for PayPal but it is giving error that "Service fee can not be applied on PayPal transactions. Service fee not supported on master merchant account."

So for Split payment for PayPal I want to use PayPal SDK separately. But getting conflicts when I installed both libraries through Pods. 

Please give a solution.

**Comment by bluk** [comment]
@jasvindersingh-evon If you are referring to [PayPal's Split Payments / Adaptive Payments](https://developer.paypal.com/docs/marketplace-split-payments/), unfortunately they are not supported in this PayPal iOS SDK. You may try looking at the [iOS MPL](https://developer.paypal.com/docs/classic/mobile/ht_mpl-itemPayment-iOS/?mark=mpl) but note that it is deprecated and there are no more updates except for critical fixes.
