### ISSUE TITLE
Paypal SDK for iOS version 2.13.2 crash

### ISSUE THREAD

**Issue by ritwikmisra** [paypal/PayPal-iOS-SDK#390]
I have used Paypal version 2.13.2 SDK for iOS.The payment with paypal account is working fine but when I am selecting the Pay with card option then the app is crashing.The crash report says --

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present a nil modal view controller on target <PayPalPaymentViewController: 0x7e3a0000
Environment: sandbox
languageOrLocale: en-US
>
.'
*** First throw call stack:
(
	0   CoreFoundation                      0x037e6a14 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x02e6de02 objc_exception_throw + 50
	2   UIKit                               0x005eaaec -[UIViewController _presentViewController:withAnimationController:completion:] + 5682
	3   UIKit                               0x005edb73 __62-[UIViewController presentViewController:animated:completion:]_block_invoke + 397
	4   UIKit                               0x005edeb8 -[UIViewController _performCoordinatedPresentOrDismiss:animated:] + 493
	5   UIKit                               0x005ed99f -[UIViewController presentViewController:animated:completion:] + 182
	6   CARLiFESTYLEExchange                0x00113b4f +[PPZebraCardIOWrapper presentCardIOPaymentViewControllerForNavigationController:forDelegate:] + 1082
	7   CARLiFESTYLEExchange                0x000d1d3c -[PPSelectPaymentFlowManager selectPayMethodViewControllerUserDidSelectCreditCard:] + 84
	8   CARLiFESTYLEExchange                0x000d5538 -[PPSelectPayMethodViewController useCreditCard] + 111
	9   CARLiFESTYLEExchange                0x00125006 __50-[PPSelectPayMethodViewControllerIOS7 viewDidLoad]_block_invoke53 + 48
	10  CARLiFESTYLEExchange                0x000c135e -[PPPaymentMethodCell tableView:didSelectRowAtIndexPath:] + 206
	11  CARLiFESTYLEExchange                0x00134192 -[PPRowBasedTableViewSection tableView:didSelectRowAtIndexPath:] + 192
	12  CARLiFESTYLEExchange                0x001349a1 -[PPSectionBasedTableViewDelegate tableView:didSelectRowAtIndexPath:] + 192
	13  UIKit                               0x0057959c -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:] + 1915
	14  UIKit                               0x0057983d -[UITableView _userSelectRowAtPendingSelectionIndexPath:] + 455
	15  UIKit                               0x0057f93f __38-[UITableView touchesEnded:withEvent:]_block_invoke + 57
	16  UIKit                               0x0041730f _runAfterCACommitDeferredBlocks + 337
	17  UIKit                               0x0042ce19 _cleanUpAfterCAFlushAndRunDeferredBlocks + 103
	18  UIKit                               0x0043ad9b _afterCACommitHandler + 102
	19  CoreFoundation                      0x036ffffe __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 30
	20  CoreFoundation                      0x036fff5e __CFRunLoopDoObservers + 398
	21  CoreFoundation                      0x036f58dc __CFRunLoopRun + 1340
	22  CoreFoundation                      0x036f50e6 CFRunLoopRunSpecific + 470
	23  CoreFoundation                      0x036f4efb CFRunLoopRunInMode + 123
	24  GraphicsServices                    0x050c7664 GSEventRunModal + 192
	25  GraphicsServices                    0x050c74a1 GSEventRun + 104
	26  UIKit                               0x00409bfa UIApplicationMain + 160
	27  CARLiFESTYLEExchange                0x00077d7a main + 138
	28  libdyld.dylib                       0x074f3a21 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException..

I have imported all the frameworks required for integrating thisSDK.I have also included these 3 libraries i.e libCardIO,libopencv_core,libopencv_imgproc in main bundle.I wonder where the problem is occurring.Do I have to change the SDK and use some previous version of paypal SDK. If I have to use some other SDK please suggest which SDK to use.

**Comment by bluk** [comment]
@ritwikmisra Please be sure in the `Other Linker Flags` that you have `-lc++ -ObjC` and have `Enable Modules (C and Objective-C` enabled, and have `Link Frameworks Automatically` enabled.

Also, another thing to check is if the included Sample App works. You need to use the `PayPal-iOS-SDK+cardio-Sample-App` target. You can also check the build settings for the target and compare them against your project's build settings.

**Comment by bluk** [comment]
Please check if the sample app works for you and to make sure you have the build settings. If the sample app works and you have the build settings specified and still have an issue, please leave a comment. Thanks.
