### ISSUE TITLE
Security issue: 3rd party app `Grabb` is registering com.paypal.ppclient.touch.v1 and com.paypal.ppclient.touch.v2 

### ISSUE THREAD

**Issue by superarts** [paypal/PayPal-iOS-SDK#394]
This is causing our app launches `Grabb` instead of `PayPal`. This is what they have in their `info.plist`.

```
      <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLName</key>
        <string>com.client.Grabb.paypal</string>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>com.client.Grabb.paypal</string>
          <string>com.paypal.ppclient.touch.v1</string>
          <string>com.paypal.ppclient.touch.v2</string>
          <string>org-appextension-feature-password-management</string>
        </array>
      </dict>
```

According to [Apple](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html), "If more than one third-party app registers to handle the same URL scheme, there is currently no process for determining which app will be given that scheme", I don't think we can do anything about it. Maybe `PayPal` should contact `Apple` about this?

In the long run, it would be good for `PayPal` to handle 3rd party apps using dynamic scheme like `Facebook`.

**Comment by bluk** [comment]
Thanks for letting us know. It seems that Grabb is incorrectly specifying the URL schemes they support. We will try to reach out.

**Comment by orinmurphy** [comment]
@bluk @superarts hi guys, apologies for this. Yes the URL scheme is incorrect on our part. It has been fixed and will be updated on the app store  v soon!

**Comment by bluk** [comment]
@orinmurphy Thanks for the info and glad that you are proactively monitoring.

**Comment by superarts** [comment]
Thanks @orinmurphy !

**Comment by orinmurphy** [comment]
@superarts no prob, thanks for pointing it out!
What did you use to find the plist?

**Comment by superarts** [comment]
@orinmurphy Just downloaded the IPA and unzipped it.
