### ISSUE TITLE
Error for direct card payment

### ISSUE THREAD

**Issue by vhraja** [paypal/PayPal-iOS-SDK#395]
Hi,

I have successfully implemented mSDK in my app but when i try to make payment via card than it gives me error "The merchant does not accept payments of this type", can any one help me out with this?

Also there is one more thing when i pay using my paypal id its going good. but its not directly transfered to my account, it waits for the authorization, what can be done so that i dont have to authorise the payment and its directly transferred?

Please reply me asap. i am stuck with this.

Regards
Varun

**Comment by bluk** [comment]
For the credit card issue, be sure your account is eligible on the [Developer Dashboard - Account Status page](https://developer.paypal.com/developer/accountStatus). Also, for direct credit cards only merchants in the US and UK are supported currently via the REST APIs (which the mSDK is based on).

For "immediate" sales payment, be sure your `PayPalPayment` has an intent of `PayPalPaymentIntentSale`. If you look at the [Single Payment](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/single_payment.md) documentation, it should identify the various types of Payment intents and what you need to do to verify the payment.
