### ISSUE TITLE
PAYMENT_CREATION_ERROR

### ISSUE THREAD

**Issue by deepak56789** [paypal/PayPal-iOS-SDK#396]
PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422).PayPal Debug-ID: 8545af6c8afc3 [live, PayPal iOS SDK 2.12.7]

Showing alert " There was a problem setting up this payment. Please visit the PayPal website to check your account.".

let us know why this error occurs always ?.Please do the needful as soon as possible.

**Comment by bluk** [comment]
If this error still occurs, please contact [PayPal Tech Support](https://www.paypal-techsupport.com) with the above information. There seems to be a problem with your account for the payment.
