### ISSUE TITLE
Missing merchant email

### ISSUE THREAD

**Issue by nokiaowner** [paypal/PayPal-iOS-SDK#397]
I built the sample project. All is well and good but cannot seem to find a property to set the merchant email? I need the customers using my app to enter their credentials and pay the merchant via the classic paypal way or pay the merchant by scanning their credit card. Thing is, to what paypal account will their money be sent? Most probably I'm missing something here. Please help!

**Comment by bluk** [comment]
When you set the `client ID` in https://github.com/paypal/PayPal-iOS-SDK/blob/master/SampleApp/PayPal-iOS-SDK-Sample-App/ZZAppDelegate.m#L17 , the client ID identifies which merchant will be paid. You can get your client ID from the [PayPal Developer Dashboard - Applications section](https://developer.paypal.com/developer/applications/) from a created REST application.

**Comment by nokiaowner** [comment]
So that means the merchant is associated with the client id. I integrated the code in an invoicing app where the merchants can and will change. In fact the app will be used by different merchants (plumbers, doctors, whatever). That means in my settings page I need to provide a field for a client ID which the merchant needs to enter? (Since different merchants will have a different paypal business account and hence a different live client ID). Am I correct?

**Comment by nokiaowner** [comment]
Sorry for posting again. If the scenario I mentioned previously is not supported, is there some other Paypal SDK I can use? Thanks!

**Comment by bluk** [comment]
Answer in your issue #398
