### ISSUE TITLE
Client ID and multiple merchants

### ISSUE THREAD

**Issue by nokiaowner** [paypal/PayPal-iOS-SDK#398]
I integrated the code in an invoicing app where the merchants can and will change. In fact the app will be used by different merchants (plumbers, doctors, whatever). That means in my settings page I need to provide a field for a client ID which the merchant needs to enter? (Since as I understand, different merchants will have a different paypal business account and hence a different live client ID). Am I correct?

If the scenario I mentioned previously is not supported, is there some other Paypal SDK I can use? Thanks!

**Comment by bluk** [comment]
Unfortunately, this SDK does not support the scenario you described. Perhaps an option is the [PayPal MPL](https://developer.paypal.com/docs/classic/mobile/gs_MPL/?mark=mpl). However, it is no longer being actively worked on aside from P0 bugs so I would strongly take that into consideration. I wish there was a better answer but there is nothing else available right now for PayPal that I'm aware of.
