### ISSUE TITLE
There was a problem communicating with paypal servers

### ISSUE THREAD

**Issue by leoo232** [paypal/PayPal-iOS-SDK#400]
Hi im using version 3.1.19.

I have added 
allow-intent href="https://www.paypal.com/

 in the config, still it didnt work

is it with paypal or the sdk? workd fine with ios but not Android

Thank in advance

**Comment by bluk** [comment]
I believe version `3.1.19` means you're using the [PayPal-Cordova-Plugin](https://github.com/paypal/PayPal-Cordova-Plugin) project.

For the Android issue, you should try using version [`3.1.23` of the Cordova plugin](https://github.com/paypal/PayPal-Cordova-Plugin/releases). There were a few fixes for the Android SDK for communicating wit the PayPal servers.

For any other issues with the Cordova plugin, you may get better assistance by opening an issue in the [PayPal Cordova Plugin issues](https://github.com/paypal/PayPal-Cordova-Plugin/issues) page.
