### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by devojyoti** [paypal/PayPal-iOS-SDK#403]
Getting Internal Server error in Production mode but works for sandbox mode. 

Log:

> PayPal iOS SDK version: PayPal iOS SDK 2.14.0
> 
> PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 102beb465708a, 102beb465708a [live, PayPal iOS SDK 2.14.0]
> 
> PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: efbe5b62d0dc4, efbe5b62d0dc4 [live, PayPal iOS SDK 2.14.0]

**Comment by bluk** [comment]
I believe there was a temporary server side issue for these requests. I did a couple of live production tests which worked.

If this issue is still occurring, please leave a comment.

**Comment by devojyoti** [comment]
Still getting this issue.

**Comment by bluk** [comment]
For internal tracking: SRE-39754

**Comment by tanvan81** [comment]
I've same problem

request failure with http statusCode:500,exception:Internal Server Error
request failed with server response:{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"73f42b854305c"}
INTERNAL_SERVICE_ERROR

**Comment by bluk** [comment]
@tanvan81 For your issue, I've opened PPPLPAYPT-7281 for internal tracking. I would also double check that any shipping/billing addresses used are valid.

**Comment by bluk** [comment]
@tanvan81 Can you try again? I've been told issue PPPLPAYPT-7281 is resolved.

**Comment by bluk** [comment]
SRE-39754 has been fixed and deployed. Please leave a comment if there's still any issue or contact [Merchant Technical Support](https://www.paypal-techsupport.com) if you have account specific questions. Thanks!

**Comment by adrianharris** [comment]
hi - I am experiencing this same issue today - thanks

**Comment by bluk** [comment]
@adrianharris Please see #440 for information on this specific error (500s are returned for many different reasons). Thanks.
