### ISSUE TITLE
PayPalMobile preconnectWithEnvironment crashes in ios

### ISSUE THREAD

**Issue by ghumpress** [paypal/PayPal-iOS-SDK#406]
I called `PayPalMobile.preconnectWithEnvironment(PayPalEnvironmentNoNetwork)`  method in viewWillAppear method. It crashes the app there. Before that I set this method in AppDelegate.swift:

`PayPalMobile.initializeWithClientIdsForEnvironments([PayPalEnvironmentSandbox: "CLIENT_ID"])`

Even I created a new app with my paypal account & get a new sandbox ID. I tried  putting the preconnectWithEnvironment method in viewDidAppear & debugged the code. The app keep crashing at this line again & again.Then I put the above method like this:

`required init(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
       PayPalMobile.preconnectWithEnvironment(PayPalEnvironmentNoNetwork)
    }`

The app still crashes in the preconnectWithEnvironment. This is the console message I'm getting. 

![screen shot 2016-03-23 at 18 51 17](https://cloud.githubusercontent.com/assets/8467088/13985787/e37df156-f128-11e5-9d7d-2b1ae14310f1.png)

**Comment by ghumpress** [comment]
The code worked fine when I created my first project. Then I made a copy of the same project. In the second project the app is crashing while calling preconnectWithEnvironment method. Any help would be great

**Comment by bluk** [comment]
Is your CFBundleVersion set in your app's Info.plist file?

**Comment by ghumpress** [comment]
I couldn't find CFBundleVersion in plist. here is my plist

![screen shot 2016-03-24 at 13 07 25](https://cloud.githubusercontent.com/assets/8467088/14010674/7fd7ac34-f1c1-11e5-807a-66de588efeff.png)

**Comment by ghumpress** [comment]
@bluk you're absolutely spot on. I missed the CFBundleVersion in the second project. I added it & now working. Thanks a lot dear. you saved me.

**Comment by bluk** [comment]
@ghumpress Glad it works. Have a good day!
