### ISSUE TITLE
Can't get access token with python3

### ISSUE THREAD

**Issue by djn40** [paypal/PayPal-iOS-SDK#410]
I'm trying to get an access token for the API.
If using Curl, it works fine but when using rauth (an Oauth python library) and requests_oauthlib (another library) it says 'client credentials are missing'.
Any help?

**Comment by ppmtscory** [comment]
Are you trying to generate an access token on the client side?  If so, you wouldn't (nor should you) have your client secret available on the client.  Can you let us know the steps you are taking with this iOS SDK?  I'm confused as to why you'd need to generate an access token within this SDK....

**Comment by djn40** [comment]
Hi
I'm attempting to connect to he REST API, since the python sdk doesn't
support referenced transactions.
My client secret and Id is stored in a postgres database, which I query
from within a python script.
I am then using the python request_oauthlib library to request a token from
https://api.sandbox.paypal.com/v1/oauth2/token.
Using cURL, and the -u option with client_id:client_secret works fine, but
using oauthlib it returns an error saying client credentials are missing.
I get the same error using Rauth (a different unrelated python library).

Thanks.

**Comment by ppmtscory** [comment]
So, to clarify, is the issue not with the iOS SDK at all?  it sounds like your issues are with the respective libraries that you are using and not with a PayPal SDK.  By the way, we also have a [Python SDK](https://github.com/paypal/PayPal-Python-SDK) that you can use.

**Comment by djn40** [comment]
Hi
Yeah sorry, it's not to do with the SDK.
I can't use the python SDK because it doesn't seemt to support reference
transactions.

Also, I've used two different librarys and got similar errors, so not sure
what the problem is.

Thanks for your help.

**Comment by ppmtscory** [comment]
Correct - reference transactions are not available via the REST APIs yet, therefore that's the reason you are not able to use the Python SDK for that.  However, you can use the Python SDK to generate an access token based on client credentials.

As for your issues with the credentials, I'd file issues with those libraries respectively to ensure that everything is good with them.  I'd double check the requests first to ensure that they are, in fact, including both the client ID and client Secret.

I will be closing this issue as it doesn't have to do with this SDK specifically.

**Comment by bluk** [comment]
@djn40 For the requests_oauthlib, you may want to try:

```
from oauthlib.oauth2 import BackendApplicationClient
from requests_oauthlib import OAuth2Session

client_id = '....'
client_secret = '....'
client = BackendApplicationClient(client_id=client_id, client_secret=client_secret)
oauth = OAuth2Session(client=client)
token = oauth.fetch_token(token_url='https://api.sandbox.paypal.com/v1/oauth2/token', username=client_id, password=client_secret)
```

That may work depending on the version of requests_oauthlib you have. I would double check with the library implementation you are using since it seems to have changed from the various documentation out there.

**Comment by djn40** [comment]
Hi
Ok thanks that worked, turnes out I was using the wrong keyword arguments
(client_id instead of username).
So now, to get a URI< I call client.get, correct?
Do I need to pass in the token?
Can't find much good documentation on this.

Thanks very much.

**Comment by bluk** [comment]
@djn40 Something like this could work:
```
payment_request = oauth.get('https://api.sandbox.paypal.com/v1/payments/payment/PAY-45S10645X6045710KK342OQA')
print "%s" % payment_request.text
```
You should open an issue with the libraries' documentation/samples for future support if they are unclear.

BTW, if the REST API does not provide support for looking up your reference transactions, using the access token may be a moot point. If you rely on the SOAP/NVP endpoints to get your information, you should read the [NVP / SOAP Apps 101](https://developer.paypal.com/docs/classic/lifecycle/apps101/) to understand those APIs and how to issue requests to them.

**Comment by djn40** [comment]
Hi
I was just reading the reference transactions documentation and it doesn't
look like REST supports it.
So I will use NVP instead.

Thanks for all your help in this issue.

**Comment by djn40** [comment]
Hi
I know this isn't relevant to the issue, but I have no idea how to obtain
sandbox API credentials.
I've read all the guides, but they aren't telling me anything.

I have an account (dylan@treshna.com) and have created several test
accounts within that account.
Do I need to create an app just for testing?
It seems like a lot of info to give out for a sandbox app.

Thanks.

**Comment by bluk** [comment]
@djn40 I believe you must create an app for testing. I assume you're trying to create one in the [NVP / SOAP section on the developer dashboard](https://developer.paypal.com/developer/applications/).

**Comment by djn40** [comment]
Yeah, but it says the application I created is a live one and I can't see
how to make it sandbox.
There's also no way of saying 'this is a test app' in the application
create page.

Thanks.

**Comment by bluk** [comment]
@djn40 Actually I forgot but an AppID for sandbox SOAP/NVP testing is provided at the very bottom of https://www.paypal-apps.com/user/my-account/applications/new or the sandbox test API credentials are provided at https://developer.paypal.com/docs/classic/api/gs_PayPalAPIs/ .

**Comment by djn40** [comment]
Ok so I've created a test sand box account.
The account details (including API creds) are meant to show up when the
profile icon is clicked, but this diolog is inaccessible with screen
readers.
Any tips?

Thanks.

**Comment by bluk** [comment]
@djn40 Unfortunately, I don't have any immediate tips. :(

I have created internal ticket SRE-39960 to make the credentials screen readable.
