### ISSUE TITLE
Not able to set recipient_email on run time 

### ISSUE THREAD

**Issue by ali2245** [paypal/PayPal-iOS-SDK#411]
Sir,
      My requirement is to take payment in different account, that will randomly assigned at runtime. In MPL sdk there was an option of setting payment.recipient, but this type of method is not available with this SDK. I can set client_id for each email but how can a know that what is client_id and where to get it.
pls give me a solution sir...

Thanks, Regards
Md. Shahzad Ali

**Comment by bluk** [comment]
@ali2245 The use case you described is not supported by this SDK, and unfortunately there isn't a solution other than to use the iOS MPL (note that the MPL SDK is only receiving critical fixes). See https://github.com/paypal/PayPal-iOS-SDK/issues/9 .

**Comment by ali2245** [comment]
thanks to reply 
I used MPL SDK for it.
