### ISSUE TITLE
VALIDATION_ERROR occurs while authorizing payment in Future Payments Server-Side Integration

### ISSUE THREAD

**Issue by sreejith2base** [paypal/PayPal-iOS-SDK#413]
### Required Information

- Mode : Sandbox
- PayPal iOS SDK Version: 2.13.2
- iOS Version and Device:  iOS 9.3 on an iPhone 5
- PayPal-Debug-ID: b8f448a0da4b5
-

### Issue Description
>According to  '**Future Payments Server-Side Integration**' document in authorizing payment step redirect URL is not required parameter. When I am trying to pass without  'redirect_urls' it returns an error saying 'redirect_urls' is required when payment_method is paypal.

**>Request**

curl 'https://api.sandbox.paypal.com/v1/payments/payment' \
    -H "Content-Type: application/json" \
    -H "PayPal-Client-Metadata-Id: c2edbd6e97b14ff2b19ddb8eec9d264c" \
    -H "Authorization: Bearer <Access Token>" \
-u "<Client ID>:<Client Secret>"\
    -d '{
           "intent":"authorize",
           "payer":{
              "payment_method":"paypal"
           },
           "transactions":[
              {
                 "amount":{
                    "currency":"USD",
                    "total":"1.88"
                 },
                 "description":"future of sauces"
              }
           ]
        }'

**>Response**

{"name":"VALIDATION_ERROR","details":[{"field":"redirect_urls","issue":"This field required when payment_method is 'paypal'"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/#VALIDATION_ERROR","debug_id":"b8f448a0da4b5"}

**Comment by bluk** [comment]
Can you try the request *without* the `-u "<Client ID>:<Client Secret>"` option in curl? The Authorization header should be enough to authenticate and authorize the request. See the [example in the documentation here](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_server.md#example-authorize-then-capture).

BTW, I removed the values of the Authorization header and your `-u Client ID:Client Secret`. While it's only sandbox, generally, I would advise against posting any credentials. You can generate a new client secret in the [Developer site](https://developer.paypal.com/) if needed.

**Comment by sreejith2base** [comment]
I have removed 'Client ID:Client Secret' now. When I tried to curl post the data the following error occurred. Please help me to solve this


**>Request**

curl 'https://api.sandbox.paypal.com/v1/payments/payment' \
    -H "Content-Type: application/json" \
    -H "PayPal-Client-Metadata-Id: c2edbd6e97b14ff2b19ddb8eec9d264c" \
    -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" \
    -d '{
           "intent":"authorize",
           "payer":{
              "payment_method":"paypal"
           },
           "transactions":[
              {
                 "amount":{
                    "currency":"USD",
                    "total":"1.88"
                 },
                 "description":"future of sauces"
              }
           ]
        }'

**>Response**

{"name":"VALIDATION_ERROR","details":[{"field":"redirect_urls","issue":"This field required when payment_method is 'paypal'"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/#VALIDATION_ERROR","debug_id":"f95fc9e56b292"}

**Comment by bluk** [comment]
Are you [Exchanging the Authorization Code you got from the Future Payments mobile SDK payment flow for a Refresh and Access Token](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_server.md#exchange-authorization-code-for-refresh--access-tokens)? Then, are you using the Access Token returned from that exchange to create the payment. You may have to [Refresh an Access Token](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_server.md#refresh-an-access-token) if it has expired.

I tried the Future Payment flow in sandbox using a sample app and was able to complete it successfully, exchange the authorization code for the refresh and access token, and use the access token to create a payment without redirect URLs.

**Comment by bluk** [comment]
@sreejith2base I believe the issue is that you need to exchange the authorization code for a bearer token (and maybe use the refresh token). If this is still an issue, please leave a comment, and we'll reopen.

**Comment by sreejith2base** [comment]
I got the issue when I was authorizing  payment. Finally I have found, the issue was generated when I tried to authorize payment of  other sandbox test accounts. The issue was now fixed by using my sand box test accounts. Thank you for your Response
