### ISSUE TITLE
[Feature Request]: Support carthage

### ISSUE THREAD

**Issue by hatebyte** [paypal/PayPal-iOS-SDK#417]

**Comment by CoolHandLuke88** [comment]
+1

**Comment by burnto** [comment]
The [Braintree iOS SDK](https://github.com/braintree/braintree_ios) includes the latest PayPal iOS code and supports Carthage, and is the integration approach we recommend.

**Comment by CoolHandLuke88** [comment]
Silly question, but what if I don't want to use brain tree. I just want to simply use the pay pal sdk without all the extra bulk that comes with braintree? It would be nice to have. Crossing my fingers you guys get it added for this sdk. ;)

**Comment by bluk** [comment]
@hatebyte @CoolHandLuke88 The Braintree v.zero SDK can support just PayPal (without card support if that's what you want), is open source, has more robust credit card support (if you are heavily reliant on credit cards), and is more customizable from a UI perspective. I recommend that you take a look if Braintree can support your business. Braintree is a PayPal company.

That being said, I did add a "beta" project at https://github.com/paypal/PayPal-iOS-SDK/tree/master/PayPalMobileSDKFramework . You can read details at the [README.md](https://github.com/paypal/PayPal-iOS-SDK/tree/master/PayPalMobileSDKFramework). You will need to add a `master` branch right now in your `Cartfile`:

```
github "paypal/PayPal-iOS-SDK" "master"
```

You will also need to add:

```
#import <PayPalMobileSDK/PayPalMobileSDK.h>
```

as an import. I recommend this only to test if this works for you and not for production yet. Trying to get feedback if this solution works for various scenarios. It seemed to work with the sample code in the documentation.

**Comment by bluk** [comment]
I'll close this issue for now since there's a way to try using Carthage now. If there's any feedback, please leave a comment.
