### ISSUE TITLE
Capture Payment Failure Code 400

### ISSUE THREAD

**Issue by bopeola21** [paypal/PayPal-iOS-SDK#418]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal iOS SDK Version: 2.14.2
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.): 6s
- PayPal-Debug-ID(s) (from any logs): Result: request failed with code400

I am having a problem capturing a future payment with the code listed below. I keep getting error code 400. Also what would the access token be in order to capture a payment if it is a single payment with credit card? Thanks in advance!

Parse.Cloud.define('capturePayment', function(request, response) {
  var Buffer = require('buffer').Buffer;
  var string = '[client_id] : [client secret]';
  var buffer1 = new Buffer(string);
  var b3 = buffer1.toString('base64');

    Parse.Cloud.httpRequest({

      method: 'POST',

      url: 'https://api.sandbox.paypal.com/v1/payments/authorization/[authorization_id]/capture',
      headers: {

        'Authorization': 'Bearer ' + b3,
        'Content-Type': 'application/json'
      },

      body: {
        'amount': {
          'currency': 'USD',
          'total' : '40.00'
        }
        'is_final_capture':true
      },

      success: function(httpResponse) {
        response.success(httpResponse);
      },

      error: function(httpResponse) {
        response.error('request failed with code' + httpResponse.status);
      }

    });

});

**Comment by bluk** [comment]
For the future payments issue, are you trying to use your app's client id and secret (in `var string = '[client_id] : [client secret]';`) to authorize the payment or the access token you got from an authorization code/refresh token exchange? You should use the [access token](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_server.md#request-3) for this future payments code path.

If you aren't exchanging your authorization code (received from this SDK after consumer consents) for an access and refresh token, you will need to exchange the authorization code for an access token which you use directly. The access token has limited time usage, so you will want to keep the refresh token to periodically request a new access token. See the [mobile client side Future Payments](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_mobile.md) and then the [server side Future Payments](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_server.md) documentation for more detailed information.

For a single payment (not related to the above issue), you need to use your client ID/secret to exchange for your app's access token. See the [REST API authentication and headers documentation](https://developer.paypal.com/docs/api/auth-headers/), specifically the `OAuth Request / Response` section.

Note that while both your issues involve access tokens, each token is scoped to different usages.

You may also be interested in the [PayPal Node SDK](https://github.com/paypal/PayPal-node-SDK) which also has samples for some of the server side code.

If you still have a question, please leave a comment and we'll reopen, or open a new issue. Thanks.

**Comment by bopeola21** [comment]
Thanks for the reply.

I apologize I should have worded my question better, when i mentioned "capturing a future payment" I just meant capturing a payment in general. In other words capturing a single payment at a later time. The second part of your answer helped but now I'm getting error code 401 when trying to get my app's access token.

Also quick question I know there is Profile Sharing but is it possible to get the users email and/or phone number using Future Payments (i really mean future payments this time lol).

Parse.Cloud.define('getOAuth', function(request, response) {
  var Buffer = require('buffer').Buffer;
  var string = '[client_id] : [client secret]';
  var buffer1 = new Buffer(string);
  var b3 = buffer1.toString('base64');

    Parse.Cloud.httpRequest({

      method: 'GET',
      //'https://api.paypal.com/v1/oauth2/token'
      url: 'https://api.sandbox.paypal.com/v1/oauth2/token',
      headers: {

        'Authorization': 'Bearer ' + b3,
        'Content-Type': 'application/x-www-form-urlencoded',
        'Accept-Language': 'en_US'
      },

      body: 'grant_type=client_credentials',

      success: function(httpResponse) {
        console.log(httpResponse.text);
        response.success(httpResponse);
      },

      error: function(httpResponse) {
        response.error('request failed with code' + httpResponse.status);
      }

    });

});

**Comment by bluk** [comment]
The `    'Authorization': 'Bearer ' + b3,` is not correct in this case. You will need to use a Basic Authentication header.

So something like:
`Authorization: Basic QWxhZGRpbjpPcGVuU2VzYW1l`. Also be careful about spacing (there should be none between the the client id, the `:`, and your client secret.

**Comment by bluk** [comment]
Regarding your second question regarding future payments, you may be able to get a possible email address back after creating the payment in the payer info (see the response example in the docs), but I recommend using the profile sharing.

**Comment by bopeola21** [comment]
Thanks for the reply. 

I'm now getting error code 0 when I changed it to 'Basic'.

'Authorization': 'Basic ' + b3,

**Comment by bluk** [comment]
I'm not sure where the `0` error code is coming from. Can you try using the `curl` request on this [Auth Headers documentation page](https://developer.paypal.com/docs/api/auth-headers/) to make sure you're using the right credentials?

Also, are you using the Parse services or have you installed Parse to your own server? The Parse cloud service may not support making TLS 1.2 requests (last I checked a few months ago), so there might be an issue there. PayPal requires TLS v1.2 for making requests to the sandbox API currently, and will transition live production in the future.

**Comment by bopeola21** [comment]
I was able to access Paypal servers 5 months ago using Cloud Code. When did the requirements change? Also I'm not sure what you meant by your first statement, I assumed you meant try the clientId and clientKey in the example. I did that and got error code 400. Tried with both content type 'Content-Type': 'application/x-www-form-urlencoded' and 'Content-Type': 'application/json'. Same error

Parse.Cloud.define('getOAuth', function(request, response) {
  var Buffer = require('buffer').Buffer;
  var string = 'EOJ2S-Z6OoN_le_KS1d75wsZ6y0SFdVsY9183IvxFyZp:EClusMEUk8e9ihI7ZdVLF5cZ6y0SFdVsY9183IvxFyZp';
  var buffer1 = new Buffer(string);
  var b3 = buffer1.toString('base64');

    Parse.Cloud.httpRequest({

      method: 'POST',
      //'https://api.paypal.com/v1/oauth2/token'
      url: 'https://api.sandbox.paypal.com/v1/oauth2/token',
      headers: {

        'Authorization': 'Basic ' + b3,
        'Content-Type': 'application/json',
        'Accept-Language': 'en_US'
      },

      body: 'grant_type=client_credentials',

      success: function(httpResponse) {
        console.log(httpResponse.text);
        response.success(httpResponse);
      },

      error: function(httpResponse) {
        response.error('request failed with code' + httpResponse.status);
      }

    });

});

**Comment by bluk** [comment]
The [PayPal TLS GitHub repository](https://github.com/paypal/TLS-update) has links with more information. I believe the sandbox update was done around middle of January. The links on the repo has information on when production will change.

You should use `'Content-Type': 'application/x-www-form-urlencoded'` (not `application/json`). While looking at this, there was another developer that had an issue ( https://github.com/paypal/PayPal-iOS-SDK/issues/376#issuecomment-170668200 ). It appears the Parse cloud service might work as-is today. Their code was very similar to yours so that might help. You may want to try and base64 encode your client ID, ":", and secret offline instead of using the buffer package and hardcoding the value into the header to make it very similar to ensure that works.

**Comment by bopeola21** [comment]
Thanks for the link I check it out and copied and pasted his code, also took your advice with encoding offline still nothing. This is my exact error.

 [Error]: {"uuid":"42a60818-e3b4-e6b2-46ef-d0ab1f218c16","status":0,"headers":{},"text":"Request failed; 35-111 SSL connect error; Connection refused","buffer":[],"cookies":{}} (Code: 141, Version: 1.12.0)
Optional(Error Domain=Parse Code=141 "{"uuid":"42a60818-e3b4-e6b2-46ef-d0ab1f218c16","status":0,"headers":{},"text":"Request failed; 35-111 SSL connect error; Connection refused","buffer":[],"cookies":{}}" UserInfo={code=141, temporary=0, error={"uuid":"42a60818-e3b4-e6b2-46ef-d0ab1f218c16","status":0,"headers":{},"text":"Request failed; 35-111 SSL connect error; Connection refused","buffer":[],"cookies":{}}, NSLocalizedDescription={"uuid":"42a60818-e3b4-e6b2-46ef-d0ab1f218c16","status":0,"headers":{},"text":"Request failed; 35-111 SSL connect error; Connection refused","buffer":[],"cookies":{}}})

**Comment by bluk** [comment]
Doing a Google search for `Request failed; 35-111 SSL connect error; Connection refused`, revealed one of my earlier StackOverflow answers about Parse not supporting TLS 1.2, but there was also another link in https://groups.google.com/forum/#!topic/parse-developers/PUKBGgHZUlU where a developer had to open a ticket with Facebook about the issue and they got part of a resolution. I think you will need to see if you can resolve this Parse issue with their support team. I don't think it's anything specific to your code.

Note that Parse the hosted service itself will be [shutdown early next year](http://blog.parse.com/announcements/moving-on/), so I'm unsure how much support they will give. They have provided an implementation that you can run on your own servers if you want. It might also solve your issue if the server environment is setup to allow TLS v1.2 requests though I can't make any guarantees.

I will close this issue since I think only Parse or switching environments can solve this problem.
