### ISSUE TITLE
Payment issue on iOS simulator

### ISSUE THREAD

**Issue by tekride** [paypal/PayPal-iOS-SDK#419]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal iOS SDK Version:PayPal iOS SDK 2.14.1
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.): 9.2 - Simulator
- PayPal-Debug-ID(s) (from any logs): PayPal Debug-ID: b50bde1a5cc70, b50bde1a5cc70

### Issue Description
> Please include as many details (logs, steps to reproduce, screenshots) as you can to help us reproduce this issue faster.
When I go for payment it directly throws below message

PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: b50bde1a5cc70, b50bde1a5cc70 [sandbox, PayPal iOS SDK 2.14.1]

Also I am getting "-canOpenURL: failed for URL: "org-appextension-feature-password-management://" - error: "(null)" before above msg even i have added proper LSApplicationQueriesSchemes key in plist

**Comment by bluk** [comment]
@tekride Are you trying to pay yourself and/or have you tried different sandbox accounts? You should use a sandbox account that is not tied to the sandbox merchant account in your app. You can create additional buyer sandbox accounts at https://developer.paypal.com/developer/accounts/ .

**Comment by bluk** [comment]
@tekride If you are not using the same account to pay yourself, then please leave a comment and we'll reopen. Thanks.
