### ISSUE TITLE
Why I can't scan IC recognition

### ISSUE THREAD

**Issue by lifengfhkj** [paypal/PayPal-iOS-SDK#420]
Why I can't scan IC recognition
##
# Required Information

- Mode (Mock/Sandbox/Live):
- PayPal iOS SDK Version:
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.):
- PayPal-Debug-ID(s) (from any logs):

### Issue Description
> Please include as many details (logs, steps to reproduce, screenshots) as you can to help us reproduce this issue faster.

**Comment by bluk** [comment]
card.io basically only scans embossed cards right now, and unfortunately, I don't have a timetable when/if this will be enhanced. The source is available at https://github.com/card-io/card.io-iOS-source if you wish to take a look or improve it.
