### ISSUE TITLE
Invisible button on PayPalPaymentViewController 

### ISSUE THREAD

**Issue by edwardyue** [paypal/PayPal-iOS-SDK#423]
Hihi, i got a same problem that mentioned is some previous thread and I still can't resolve the issue.

I tried below but the button is still missing....could you help?

PayPalPaymentViewController *paymentViewController = [[PayPalPaymentViewController alloc] initWithPayment:payment
                                                                                            configuration:self.payPalConfig
                                                                                                 delegate:self];

[[UIBarButtonItem appearance] setTintColor:nil];
[[UINavigationBar appearance] setTintColor:nil];
self.navigationController.navigationBar.tintColor = nil;

[self presentViewController:paymentViewController animated:YES completion:nil];

**Comment by bluk** [comment]
Are there any other UIAppearance customizations that you're using?

What version of iOS are you using and what version of the SDK? Also, does the sample app in this repository work for you?

**Comment by edwardyue** [comment]
Thanks for reply. When I search "UIAppearance" in my project, I can't find any hence I believe I did not use it.
My build target IOS is version 8 and the paypal SDK is 2.14.2. When I deploy the sample app, i do see the button. However when I move the entire storyboard to my project, the button is disappeared. Any thoughts?

many thanks!

**Comment by edwardyue** [comment]
Oh thanks! you reminded me. I do have other UIAppearance customization. I got the button back after removed it.

Many thanks!
Edward

**Comment by bluk** [comment]
Great! You're welcome.
