### ISSUE TITLE
Pass address with card payment

### ISSUE THREAD

**Issue by Astutech** [paypal/PayPal-iOS-SDK#424]
Hi.

Is there an option to allow the user to pass their shipping address (stored in the app) when using card.io and sending a card payment? Or is this deemed a security risk?

Many thanks

**Comment by bluk** [comment]
You can [set the shippingAddress](https://github.com/paypal/PayPal-iOS-SDK/blob/master/PayPalMobile/PayPalPayment.h#L197) in a PayPalPayment if your app has already collected the information. Is there a specific use case that you want to use the shipping address for?

**Comment by Astutech** [comment]
I have enabled the shippingAddress from app part, but this only becomes an option if the user pays using Paypal rather than scanning their card - if they scan their card there is no option to select the shipping address, just a button to process payment and no address is found when I go through my verification process.

I should probably add that im using Phonegap Build.

Thanks

**Comment by Astutech** [comment]
Hi, any response to my last please? Thanks

**Comment by bluk** [comment]
@Astutech Sorry for the delay. There is not an option for this. The shipping address can be collected by your app but will need to be built by you. The PayPal shipping address is a convenience since they may have shipping addresses already associated with their PayPal account.

**Comment by Astutech** [comment]
Ok, thanks. Is there anyway to pass any piece of data with a card payment? Like an email address or the buyers name (taken from local storage in the app)? Its just when the card payments appear in the PayPal account there's nothing to say who its from?

**Comment by Astutech** [comment]
Hi Bluk, sorry to chase but if you could update me on my last question that would be great, many thanks.

**Comment by bluk** [comment]
@Astutech There isn't really a way to pass in the email address or buyer's name with a card payment. You can try passing in an [Invoice ID](https://github.com/paypal/PayPal-iOS-SDK/blob/master/PayPalMobile/PayPalPayment.h#L201) to keep track of the payment.

**Comment by Astutech** [comment]
@bluk Thanks for your reply. Surely PayPal would require the name and address of the card holder in order to verify the payment for processing?

**Comment by bluk** [comment]
@Astutech In this flow, it isn't required.

I recommend you look into the [Braintree v.zero](https://github.com/braintree/braintree_ios) SDK if it is supported for your business's country of origin, and you're more interested in the credit card processing and minimizing decline rates. There are similar capabilities for PayPal processing in the v.zero SDKs. You can find [more documentation here](https://developers.braintreepayments.com/start/hello-client/ios/v4). (Note: Braintree is a PayPal company).
