### ISSUE TITLE
How to check sandbox transactions?

### ISSUE THREAD

**Issue by pphan** [paypal/PayPal-iOS-SDK#430]
After make payment from iOS app, I saw like this response at below 

[client: {
    environment = mock;
    "paypal_sdk_version" = "2.14.3";
    platform = iOS;
    "product_name" = "PayPal iOS SDK";
}, response_type: payment, response: {
    "create_time" = "2016-06-16T20:56:40Z";
    id = "PAY-NONETWORKPAYIDEXAMPLE123";
    intent = sale;
    state = approved;
}]

When I check from my paypal developer account, I could not find my sandbox transaction. 

Thanks!

**Comment by bluk** [comment]
You're in `mock` mode which does not actually communicate with sandbox. You need to set your environment to `PayPalEnvironmentSandbox` as [demonstrated in the sample](https://github.com/paypal/PayPal-iOS-SDK/blob/master/SampleApp/PayPal-iOS-SDK-Sample-App/ZZMainViewController.m#L95). There's some included [documentation](https://github.com/paypal/PayPal-iOS-SDK#use-cases) in this repository which may also help clarify. Hope that helps.
