### ISSUE TITLE
There was a problem setting up this payment

### ISSUE THREAD

**Issue by balkarov** [paypal/PayPal-iOS-SDK#431]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal iOS SDK Version: 2.14.3
- Simulator iOS 9.3 iPhone 6
- PayPal-Debug-ID(s) (from any logs): PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: 915b923b1d92a, 915b923b1d92a [sandbox, PayPal iOS SDK 2.14.3]

### Issue Description
When I click Log In with sandbox account, I get this error 
"There was a problem setting up this payment. Please visit the PayPal website to check your account".

My account:
Pass has upper and lowercase letters and numbers (14 characters)

Account Type:
Business
Status:
Verified
Country:
DE
Notes:

Credit Card Number:
5232101600548338
Credit Card Type:
MASTERCARD
Expiration Date:
07/2021
PayPal

Balance:
20000.00 EUR (I try buy 1700.00 EUR)

__________

My main account has RUB. Ok, I created new app with currency RUB.
Change in App all items to RUB and I get the same error too. My balance is 20000.00 RUB (I try pay 1700.00 RUB)

PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: cee44435d9ff5, cee44435d9ff5 [sandbox, PayPal iOS SDK 2.14.3]

Help me please

**Comment by ppmtscory** [comment]
@balkarov the debug IDs don't seem to be pulling up for me, however, I believe the issue is that you are doing a CC payment with an account that doesn't offer that functionality.  Direct Credit Card payments with this SDK are only offered to US and UK merchants at this time.  You can review more about that [here](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/#direct-credit-card-payments).  Please test a PayPal payment with your DE account and let me know how that goes.

**Comment by balkarov** [comment]
What I should do that to test in sandbox? 
I need register new account in US? Or create new sandbox account in US?

**Comment by ppmtscory** [comment]
That's correct.  If you'd like to test that functionality, you can create US sandbox accounts to use.  When you create your REST App, you'll need to select the US business sandbox account email address to tie the credentials to.

**Comment by balkarov** [comment]
Ok, I will try

**Comment by balkarov** [comment]
I have a one more problem
```
_payPalConfig = [[PayPalConfiguration alloc] init];
_payPalConfig.payPalShippingAddressOption = PayPalShippingAddressOptionPayPal;
```

In payPal controller I choose Shipping Address (PayPal account address). But in response I get Shipping Address: (null).

```
CurrencyCode: EUR
Amount: 416.99
Short Description: Clothes
Intent: sale
Processable: Already processed
Display: €416.99
Confirmation: {
    client =     {
        environment = sandbox;
        "paypal_sdk_version" = "2.14.3";
        platform = iOS;
        "product_name" = "PayPal iOS SDK";
    };
    response =     {
        "create_time" = "2016-06-23T12:54:24Z";
        id = "PAY-3H962440US5*******";
        intent = sale;
        state = approved;
    };
    "response_type" = payment;
}
Details: Subtotal: 299.99, Shipping: 117, Tax: (null)
Shipping Address: (null)
Invoice Number: (null)
Custom: (null)
Soft Descriptor: (null)
BN code: (null)
Item: '{Some|299.99|EUR|(null)}'
```
Why I get response Shipping Address: (null)?

**Comment by ppmtscory** [comment]
Is this in the initial response from the SDK back to your app prior to the 'Verify Payment' step?  The shipping address should be shown when you do the payment lookup (verify payment step)...
```
curl https://api.sandbox.paypal.com/v1/payments/payment/PAY-5YK922393D847794YKER7MUI \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer accessToken"
```

**Comment by balkarov** [comment]
No, this new question. Because I cannot create new issue without PR :(
This problem I get after authentication -> choose shipping address -> Click Pay -> And I get response with Shipping Address: (null). Why Shipping Address is NULL, but I chose shipping address?

**Comment by ppmtscory** [comment]
The shipping address is tied to the transaction so you'll see the shipping address when you do the verify payment step.  Please do the curl command I mentioned previously and you'll see the shipping address.

**Comment by runia** [comment]
Where is I must do curl? 
In iOS code?

**Comment by balkarov** [comment]
Where is I must do curl? In iOS code. 
I have a problem in method 
- (void)payPalPaymentViewController:(PayPalPaymentViewController *)paymentViewController didCompletePayment:(PayPalPayment *)completedPayment { }

completedPayment Show me Shipping Address (null)

**Comment by bluk** [comment]
@balkarov You would do the equivalent `curl` command in your server code eventually. The basic idea is that you must send the payment confirmation data to your server. Your server should verify the payment.

Just to give you an idea though, you can run the curl command in your command prompt/Terminal to understand what information you should be getting.

You can see an idea on how to send the payment confirmation to your server on the [Single Payment](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/single_payment.md) document in this repository (step 8). And then please read the [verify the payment of proof](https://developer.paypal.com/webapps/developer/docs/integration/mobile/verify-mobile-payment/) doc linked.

**Comment by balkarov** [comment]
Yes, I know.
But my Shipping Address (null)
How I send server without Shipping Address? I need Shipping Address after user pay

**Comment by balkarov** [comment]
Can you help me?

**Comment by bluk** [comment]
@balkarov You only need to send the payment confirmation info (without shipping address info) to your server:

In particular, the information:
```
        id = "PAY-3H962440US5*******";
        intent = sale;
        state = approved;
```

Then on your server, you use this `id` to lookup the entire payment resource (including the selected shipping address) given back when you perform a GET on  on your server using a request similar [to the curl one mentioned earlier](https://github.com/paypal/PayPal-iOS-SDK/issues/431#issuecomment-228097285).

**Comment by bluk** [comment]
If this is still an issue, please leave a comment. Thanks!

**Comment by balkarov** [comment]
Where is I get Bearer accessToken?

**Comment by bluk** [comment]
@balkarov See the documentation on the [REST API authentication and headers](https://developer.paypal.com/docs/api/auth-headers/) for some `curl` examples you can try on your command line. Specifically:

```
curl https://api.sandbox.paypal.com/v1/oauth2/token \
  -H "Accept: application/json" \
  -H "Accept-Language: en_US" \
  -u "<client-id>:<secret>" \
  -d "grant_type=client_credentials"
```

Be sure to have the `:` in between your app's client ID and secret.
