### ISSUE TITLE
invoicing

### ISSUE THREAD

**Issue by alimehdipk** [paypal/PayPal-iOS-SDK#434]
### Required Information

- Mode : Sandbox
- PayPal iOS SDK Version:2.14.4
- iOS Version and Device  iOS 9.3:
- PayPal-Debug-ID(s) (from any logs): 8785ce97199fd

### Issue Description
> how can i get invoice of my transaction in email made from this sdk?

**Comment by bluk** [comment]
This SDK does not support sending an invoice/email directly. (Note, you can set an [optional invoice number](https://github.com/paypal/PayPal-iOS-SDK/blob/master/PayPalMobile/PayPalPayment.h#L200) for your tracking purposes, but it doesn't send an invoice.)

Your app can send any relevant information to your server, and your server can send an email to the customer if needed.

If you still have an issue/question, please leave a comment or open a new issue.
