### ISSUE TITLE
INTERNAL_SERVICE_ERROR

### ISSUE THREAD

**Issue by aamirjind** [paypal/PayPal-iOS-SDK#441]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal iOS SDK Version: 2.14.3
- iOS Version and Device : iOS 9x
- PayPal-Debug-ID(s) (from any logs):

### Issue Description
> PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 7f5de87739239, 7f5de87739239 [sandbox, PayPal iOS SDK 2.14.3]

**Comment by bluk** [comment]
This issue seems to be the same as #440 , so please see that issue for the latest information.
