### ISSUE TITLE
Programatically assign language

### ISSUE THREAD

**Issue by TaoNhan** [paypal/PayPal-iOS-SDK#442]
Hello!

I am making an app where the language is managed through a local variable (instead of using the language of the device) and I was wondering if it is possible to programatically set the language programatically for the Paypal SDK
Thank you!

**Comment by bluk** [comment]
@TaoNhan The PayPal iOS SDK uses the language of the device to display any translated strings, and unfortunately, there isn't a way to set it programmatically. I think Apple recommends all apps to use the language preferences set on the device. You should be able to still process transactions using different supported currencies if needed.
