### ISSUE TITLE
Bitcode Error When Archiving

### ISSUE THREAD

**Issue by gudatcomputers** [paypal/PayPal-iOS-SDK#443]
### Required Information

- Mode (Mock/Sandbox/Live): ALL
- PayPal iOS SDK Version: 2.14.4
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.):n/a archive issue
- PayPal-Debug-ID(s) (from any logs):n/a archive issue

### Issue Description
> Please include as many details (logs, steps to reproduce, screenshots) as you can to help us reproduce this issue faster.
Archive an app using 2.14.4.  My specific app is targeting 8.4, running Xcode 7.3.1

The error generated is 
**error: Invalid bitcode version (Producer: '800.0.24.1_0' Reader: '703.0.31_0')**

**Comment by bluk** [comment]
@gudatcomputers Thank you for reporting the issue. This should be fixed in [2.14.5](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.14.5), and sorry for the inconvenience.
