### ISSUE TITLE
Payment issue with sandbox - 500 error

### ISSUE THREAD

**Issue by quocbao1087** [paypal/PayPal-iOS-SDK#446]
Required Information

- Mode (Sandbox):
- PayPal iOS SDK Version:2.14.5
- iOS Version and Device (iOS 9.3 on an iPhone 6s):
- PayPal-Debug-ID(s) (from any logs):PayPal Debug-ID: 4236d5a76db88, 4236d5a76db88

Issue Description
After make payment, I got this error:
PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 4236d5a76db88, 4236d5a76db88 [sandbox, PayPal iOS SDK 2.14.5]
I check in my Paypal sandbox account, that payment has been made successfully. Can you help me to check my Paypal Debug -ID to know what wrong?

**Comment by bluk** [comment]
@quocbao1087 There was an issue in the sandbox environment earlier today, but it should be fixed. Can you please try again? If it still occurs, please leave a comment and we'll reopen the issue or contact [PayPal Tech Support](https://www.paypal-techsupport.com).

**Comment by quocbao1087** [comment]
it is fixed, but now I have another issue.
after payment success, no return in this function:

-(void)payPalPaymentViewController:(PayPalPaymentViewController *)paymentViewController didCompletePayment:(PayPalPayment *)completedPayment{
    NSLog(@"[INFO] in module - didCompletePayment!!!");

[self dismissViewControllerAnimated:YES completion:nil];
 
}

**Comment by quocbao1087** [comment]
hi, Bluk,
I still face to this problem.
Sometime the payment success without error, sometime I have that issue.

INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: f29029c786077, f29029c786077 [sandbox, PayPal iOS SDK 2.14.5]

Can you help me to know what is wrong to fix this?

**Comment by bluk** [comment]
@quocbao1087 Unfortunately, you appear to be hitting a sandbox capacity limitation which is why it sometimes works and sometimes does not. SRE-42473 is open for this issue. I'll leave this issue open until that is resolved. Production should not encounter this issue.

**Comment by bluk** [comment]
This capacity issue was resolved so closing this issue.

**Comment by kowaiwoon** [comment]
@bluk  I have same issue with PayPal-iOS-SDK 2.16.1

PayPal SDK: Request has failed with error: ADDRESS_ADDITION_ERROR - Error encountered while adding shipping address to PayPal account. (500) | PayPal Debug-ID: 1c547f6db801d, 1c547f6db801d [sandbox, PayPal iOS SDK 2.16.1]

Please let me know what was the problem.

Thank you.

**Comment by kowaiwoon** [comment]
@bluk  And i get this error too.

PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: 4a3c63bd5c3b, 4a3c63bd5c3b [sandbox, PayPal iOS SDK 2.16.1]

**Comment by MukeshMuteja786** [comment]
Having Same issue
PayPal SDK: Request has failed with error: DUPLICATE_REQUEST_ID - System error. Please try again later. (400) | PayPal Debug-ID: cb6c88aef2c09, cb6c88aef2c09 [sandbox, PayPal iOS SDK 2.16.1]

**Comment by bluk** [comment]
@kowaiwoon Can you please try again? If you encounter another error, please create a new issue. The problems are unrelated to the original issue.

@MukeshMuteja786 For the 400 error you received, the issue seems to be because your sandbox merchant account does not support domestic transactions. Usually this is because you are trying to do direct credit card payments in an unsupported country like India. If you want more details, please contact [PayPal Merchant Technical Support](https://www.paypal-techsupport.com) who can look into your sandbox account details.
