### ISSUE TITLE
didCompletePayment but there is no payment in sandbox account and the balance didn't change

### ISSUE THREAD

**Issue by quocbao1087** [paypal/PayPal-iOS-SDK#447]
### Required Information

- Mode (Sandbox):
- PayPal iOS SDK Version:2.14.4 and 2.14.5
- iOS Version and Device (iOS 9.3 on an iPhone 6s):
- PayPal-Debug-ID(s) (from any logs):
my paypal account: bao.nq@verzdesign.com.sg
may paypal sandbox account: bao.nq-buyer@verzdesign.com.sg

Issue Description
I made payment successfully , I see log in function didCompletePayment. but I didn't see any payment in my sandbox account and the balance still does not change.

**Comment by bluk** [comment]
@quocbao1087 For the sandbox account, are you logging into the store's seller sandbox account to check the payment? Usually this would be `<original-email>-facilitator@<original-domain>" similar to your `-buyer` account email. You should login via https://www.sandbox.paypal.com/ .

You can find the seller sandbox account by looking into your app's Sandbox API Credentials (the same page as the one where you found your Client ID).

If you can provide a `PayPal-Debug-ID` (printed in the Xcode console logs), that would be helpful to further debug if necessary.

**Comment by quocbao1087** [comment]
Yes, I logged in to seller sandbox but it is the same as buyer that there is no payments created.
How to print PayPal-Debug-ID?
`-(void)payPalPaymentViewController:(PayPalPaymentViewController *)paymentViewController didCompletePayment:(PayPalPayment *)completedPayment{
    NSLog(@"Paypal Payment success!!!");
    [self dismissViewControllerAnimated:YES completion:nil];  
}`
I only see the log that "Paypal Payment success!!!"

**Comment by bluk** [comment]
Sorry, the `PayPal-Debug-ID` is only printed if something goes wrong in the request/responses.

Can you log the `completedPayment.confirmation` (somewhat similar to the [last step in the single payment doc](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/single_payment.md) ) and give back the result?

It should be something like:

```
confirmation: {
    "create_time" = "2016-08-18T16:23:59Z";
    id = "PAY-65A88594JE744223SK626A6I";
    intent = sale;
    state = approved;
}
```

The id is the Payment ID which you can look up via the REST API and use to verify the payment.

**Comment by quocbao1087** [comment]
Sorry, I forgot to change PayPalEnvironmentNoNetwork to PayPalEnvironmentSandbox. Now it is working fine. Thank you very much!
