### ISSUE TITLE
It doesn't support Simplified and Traditional (iOS 9.0 or above)

### ISSUE THREAD

**Issue by youngshingjun** [paypal/PayPal-iOS-SDK#449]
PayPal SDK It doesn't support Simplified Chinese and Traditional Chinese (iOS 9.0 or above).

//Sample Code

NSUserDefaults* defaults = [NSUserDefaults standardUserDefaults];
NSArray* languages = [defaults objectForKey:@"AppleLanguages"];
NSString* language = [languages objectAtIndex:0];

if ([language hasPrefix:@"zh-Hans"]) {
// Language is Simplified Chinese.
}

if ([language hasPrefix:@"zh-Hant"] ||
        [language hasPrefix:@"zh-HK"] ||
        [language hasPrefix:@"zh-MO"] ||
        [language hasPrefix:@"zh-TW"] ||
        [language hasPrefix:@"zh-SG"] ) {
// Language is Traditional Chinese.
}

**Comment by bluk** [comment]
Thanks for reporting the issue. [Release 2.14.6](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.14.6) should resolve the bug.

**Comment by youngshingjun** [comment]
@bluk PayPal iOS SDK 2.14.6 not resolve the bug. 
My device is iPhone 5S (Gold) iOS system is 9.3.4.
![img_0830](https://cloud.githubusercontent.com/assets/746817/17920980/2923fcc8-6a0a-11e6-80f5-fff8183832a6.PNG)

**Comment by bluk** [comment]
Can you please confirm if you've localized your app in the Project settings? Click on the Xcode project in the file navigation browser, Select your project and on the Info tab, you should have something like:

![screen shot 2016-08-24 at 9 37 43 am](https://cloud.githubusercontent.com/assets/94150/17934710/8950a99c-69de-11e6-93db-b4032436fd8a.png)

Furthermore, is the iOS simulator or phone set to use Chinese as its preferred language? In the Settings > General > Language & Region > iPhone Language.

**Comment by youngshingjun** [comment]
@bluk My phone set to use Chinese as its preferred language.
![img_0831](https://cloud.githubusercontent.com/assets/746817/17951626/2431a530-6a96-11e6-9fb0-6e38d72e0aca.png)
My Project settings something like:
<img width="447" alt="img_0832" src="https://cloud.githubusercontent.com/assets/746817/17951659/60ee72b4-6a96-11e6-95cc-bec0ffd66e20.png">

**Comment by youngshingjun** [comment]
@bluk If your app use Chinese as its preferred language (iOS 9.0 or above), so Targets > Info something like:
<img width="553" alt="img_0833" src="https://cloud.githubusercontent.com/assets/746817/17952217/eeecc756-6a9a-11e6-9062-f0a1c295be83.png">
You should set CFBundleDevelopmentRegion to en_US (Info.plist)

**Comment by bluk** [comment]
@youngshingjun Please see if [2.14.7](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.14.7) resolves your issue. Thanks.

**Comment by youngshingjun** [comment]
@bluk #449 issue is resolved. Thanks.

**Comment by bluk** [comment]
@youngshingjun Great!
