### ISSUE TITLE
IPN - notify_url

### ISSUE THREAD

**Issue by quocbao1087** [paypal/PayPal-iOS-SDK#450]
Hi, 
How can to set notify_url and invoice in new sdk?
because I have a magento website that integrated Paypal IPN as default. I want to make payment on mobile app then Paypal auto send notify payment to notify url, mangeto can process order as before.

**Comment by bluk** [comment]
The PayPal REST API (which this SDK is built on top of) uses [Webhook notifications](https://developer.paypal.com/docs/integration/direct/rest/webhooks/) for callbacks. I would strongly recommend investigating web hooks.

That being said, you can set a Instant Payment Notification URL in your seller account which may receive events you need. For testing, you will need to login to your seller account on [sandbox.paypal.com](https://www.sandbox.paypal.com/us/cgi-bin/webscr?cmd=_profile-ipn-notify) and enable IPN there.

**Comment by quocbao1087** [comment]
Can I ignore these step in paypal integration, will it cause anything wrong?
1. paymentWillComplete
2. webhook notification

**Comment by bluk** [comment]
@quocbao1087 It depends on your specific integration. You can ignore the `paymentWillComplete` callback if you want. You can also not use webhooks depending on your mobile and server integration.
