### ISSUE TITLE
paymentWillComplete but not paymentDidComplete

### ISSUE THREAD

**Issue by quocbao1087** [paypal/PayPal-iOS-SDK#451]
Hi, Not sure this is an issue, I am just not clear about the workflow.

I made payment, paymentDidComplete did not happen, only paymentWillComplete happen. 
In this case, what workflow to do to update payment status to my web server?

**Comment by quocbao1087** [comment]
Btw, Sometime paymentDidComplete happens, sometime nothing happen after payment success when I test on sandbox account.

**Comment by bluk** [comment]
Are you always calling the `completionBlock` callback in `paymentWillComplete`?

**Comment by quocbao1087** [comment]
yes?

**Comment by bluk** [comment]
@quocbao1087 Are you calling the `completionBlock` on the main thread? Something like:

```
dispatch_async(dispatch_get_main_queue(), ^{
  completionBlock();
})
```

Also, does the sample application work for you (e.g. using your client ID, does the `paymentDidComplete` always get called?)

**Comment by quocbao1087** [comment]
@bluk 
I know this is out of scope. But I don't know where is the issue to able to fix!
It works in xcode.
But when I make a module in Appcelerator Titanium cross platform.
Sometime didCompletePayment get called, sometime didCompletePayment didn't get called.

**Comment by bluk** [comment]
@quocbao1087 Unfortunately we don't officially support the Appcelerator platform. I would investigate if switching Appcelerator to always execute code to use the main thread fixes the issues first. You may get better assistance with the Appcelerator forums.
