### ISSUE TITLE
Checking this device ...unstop loading

### ISSUE THREAD

**Issue by quocbao1087** [paypal/PayPal-iOS-SDK#453]
- Mode (Sandbox):
- PayPal iOS SDK Version:2.14.5
- iOS Version and Device (iPhone 6s):
![simulator screen shot aug 24 2016 12 46 25 pm](https://cloud.githubusercontent.com/assets/7627512/17919675/69efc6da-69f9-11e6-95e3-2eca421c2fb7.png)

**Comment by bluk** [comment]
@quocbao1087 Does this occur with the sample application included in this repository? I would also check that you are on the main thread when presenting view controllers.

**Comment by bluk** [comment]
See #451 since I think it's the same issue.
