### ISSUE TITLE
org-appextension-feature-password-management

### ISSUE THREAD

**Issue by antons81** [paypal/PayPal-iOS-SDK#455]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal iOS SDK Version: PayPal-iOS-SDK (2.14.7)
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.): 10.0
- PayPal-Debug-ID(s) (from any logs): 

### Issue Description
Hello Paypal, after I have updated sdk to last one, I cannot do login from web paypal anymore. getting this error 

>  -canOpenURL: failed for URL: "org-appextension-feature-password-management://" - error: "(null)"

I have already added this: org-appextension-feature-password-management to my plist file but nothing helps. It simply stuck and app not responsive. This is not crash, simply cannot touch anything after that. Please advice

**Comment by bluk** [comment]
@antons81 Is there any PayPal Debug ID or any other information? The message you indicated is not [an actual error](https://github.com/paypal/PayPal-iOS-SDK/issues/324#issuecomment-232385792). Sorry for the delay in response.

**Comment by antons81** [comment]
Hi @bluk What exactly do you need? As I investigated this issue, it's happens on simulator only, because it's not happening on device (I have 1Password installed there). But simulator simply stuck and nothing happens

**Comment by bluk** [comment]
@antons81 Just to be clear,  when you said`login from web paypal`, are you making a single payment, future payment, or using the Login with PayPal flow? I'm assuming that you're talking about clicking the Login button similar to:

<img width="320" alt="screen shot 2016-09-06 at 9 43 16 am" src="https://cloud.githubusercontent.com/assets/94150/18278106/7b18becc-7416-11e6-98b1-adb1c00b0abc.png">

And nothing happens during a payment flow.

Were there any other changes made to your system? I see that you're using iOS 10 SDK, but did it work in iOS 9.x SDK? Or did you mean that it worked with a previous 2.14.6 or lower version of the PayPal SDK with the iOS 10 SDK?

Also, are there any settings in the Simulator that you have enabled that aren't the default? Maybe try `Reset Content and Settings` for the simulator to double check? I've tried using Xcode 8 beta 6 and using the sample app in this repository, the app seems to work in the iOS 10 simulator.

**Comment by antons81** [comment]
@bluk Thank for the response. I am using PayPal iOS SDK.

Also, are there any settings in the Simulator that you have enabled that aren't the default? Maybe try 

> Reset Content and Settings for the simulator to double check? I've tried using Xcode 8 beta 6 and using the sample app in this repository, the app seems to work in the iOS 10 simulator.

I am using 7.3.1 mean time

**Comment by bluk** [comment]
Xcode 8 GM was released and I did a quick test and I was able to login successfully in the simulator. If you still encounter an issue with Xcode 8 GM and with the Xcode simulator reset, please leave a comment and I'll re-open.
