### ISSUE TITLE
 Request has failed with error: DUPLICATE_REQUEST_ID

### ISSUE THREAD

**Issue by Hitarth2000** [paypal/PayPal-iOS-SDK#457]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal iOS SDK Version: PayPal iOS SDK 2.14.7
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.): iPhone 6 with 9.3
- PayPal-Debug-ID(s) (from any logs): Debug-ID: 9fe30a135a7b5, 9fe30a135a7b5

### Issue Description
Working with PayPalEnvironmentSandbox Environment. When i tried to do transaction with testing credit card , i got the below issue. 

PayPal SDK: Request has failed with error: DUPLICATE_REQUEST_ID - System error. Please try again later. (400) | PayPal Debug-ID: 9fe30a135a7b5, 9fe30a135a7b5 [sandbox, PayPal iOS SDK 2.14.7]

Please help me out on this.

**Comment by bluk** [comment]
@Hitarth2000 It seems you're trying to do a domestic credit card transaction in an unsupported country. Please refer to [Country & Currency Support](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/) for PayPal REST API Payments for specific country support especially for credit cards. Also, make sure that you have a PRO seller account if you are in a supported country. For account specific help, you may also want to reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com).

**Comment by Hitarth2000** [comment]
Yes i was trying for INDIA which is not supported for direct Credit card. That is fine.   -buyer email id was working but for the same credit card which is embedded to that email id was not working. Then i got that direct credit card is not supported for all country.. . Thanks.
