### ISSUE TITLE
credit card successfully charged but payment cannot be verified

### ISSUE THREAD

**Issue by panlong90** [paypal/PayPal-iOS-SDK#460]
### Required Information

- Mode (Sandbox):
- PayPal iOS SDK Version:"2.14.7";
- iOS Version and Device: iOS 9.3 on an iPhone 6s+
- PayPal-Debug-ID(s) (from any logs): "72c60894c7b7c"

### Issue Description
payment with PayPal account can be verified without any problem. Payment with credit card option cannot be verified (through a Lambda function call). I keep getting error "Invalid Resource ID".  I can see the transaction record in the sandbox account which shows the CC has been successfully charged.

**Comment by bluk** [comment]
Are you using the same account credentials? Please ensure that the REST application's client ID you used in your mobile app matches the client ID/secret pair you used to verify the payment on your server.

**Comment by panlong90** [comment]
Yes, I verify both PayPal account option and credit card option using the same server function. And payment with Paypal option can be verified while the CC option cannot.

**Comment by panlong90** [comment]
With some thorough scrutiny, I'm embarrassed to say that indeed I made a mistake in the client credentials. Case closed.

**Comment by bluk** [comment]
Glad it works now!

**Comment by panlong90** [comment]
Thanks for your help!
