### ISSUE TITLE
Sandbox login Failed

### ISSUE THREAD

**Issue by Miteshimmply** [paypal/PayPal-iOS-SDK#465]
### Required Information
- Mode (Sandbox):
- PayPal iOS SDK Version: 2.15.1
- iOS Version and Device (iOS 9.0 above on Simulator):
- PayPal-Debug-ID(s) (from any logs): 85b0a950db512, 85b0a950db512

### Issue Description
> Please include as many details (logs, steps to reproduce, screenshots) as you can to help us reproduce this issue faster.

1) I have setup in AppDelegate.m file in Demo as below:

  [PayPalMobile initializeWithClientIdsForEnvironments:[NSDictionary dictionaryWithObjectsAndKeys:@"ATGne7GGEGIv42Nr7gtvfgBjlvK3BacvRKYaivapKY3QYn0efqQ4ZVWRr5qatPrLAyBMuMxvXWVWwpuB",PayPalEnvironmentSandbox, nil]];

2) Setup PayPalEnvironment as below:
#define kPayPalEnvironment PayPalEnvironmentSandbox

3) Create Paypal personal Account:
 Create Paypal personal account and click on dashboard then i have created app in My Apps & Credentials Section and then create app in REST API appsANd got Client ID and i have placed in step 1 and run.
I have enter Working Paypal login credential and i got below error:
2016-09-22 11:36:09.101 PayPal-iOS-SDK-Sample-App[701:17736] PayPal SDK: Request has failed with error: invalid_user - Incorrect username/password. Please try again. (401) | PayPal Debug-ID: 85b0a950db512, 85b0a950db512 [sandbox, PayPal iOS SDK 2.15.1] | Details: (
        {
        "error_description" = "Invalid user credentials";
    }
).

Please help me to solve out this issue.

**Comment by bluk** [comment]
Are you using a sandbox PayPal account's credentials?

Please go to the Developer Dashboard under [Sandbox > Accounts](https://developer.paypal.com/developer/accounts/) to create a PayPal sandbox account. You can find [more information here](https://developer.paypal.com/docs/classic/lifecycle/ug_sandbox/) about how to test with a sandbox PayPal account. Usually, a sandbox account looks like `<your email>-buyer@<your domain>` by default.

**Comment by Miteshimmply** [comment]
Hi i am using email-buyer@gmail.com but same error getting

**Comment by bluk** [comment]
@Miteshimmply Can you open a new private/incognito browser and try logging into the PayPal Sandbox Website https://www.sandbox.paypal.com using your test sandbox account that you obtained from the above links? You can also reset your sandbox account's password to ensure that your password is correct.

Also, can you try creating a new sandbox test account and using that? I've logged into a few test sandbox accounts and didn't see an issue.

**Comment by Miteshimmply** [comment]
Thanks a lot Sandbox account is working but I got Below issue :
I Received successfully Authorisation Code and when i pass Authorisation code with ClientID and SecretKey with Authorisation. I got response like below 

access_token": "6oyryV79E.KtpAvPudpI8VIko.ntdPikU9HCDfg0tO0",
    "expires_in": 23323,
   "Nonce":"TPW3zlCAjznPs2D0VQlQXwiEfTesR-dRiU_qhbUngzxR3NmeBxqKEL",
    "refresh_token": "MFYQJTPW3zlCAjznPs2D0VQlQXwiEfTesR-dRiU_qhbUngzxR3NmeBxqKELcmGtSI739R-awwvOyGVO1LJbowy7n8Ul3vsf5HQDTCzUlDylqBvW0",
    "scope": "https://api.paypal.com/v1/payments/.* https://uri.paypal.com/services/payments/futurepayments",
    "token_type": "Bearer"

But when i pass refresh token it gives below error :

 error = "invalid_refresh_token";
 "error_description" = "No consent were granted";

**Comment by bluk** [comment]
I removed the tokens in your example. Even though they are for sandbox, generally, you should not post any credentials in these issues.

A few things that you may want to look at is if the REST application has the right permissions. In your REST application details page (where you got your client ID/secret).

![screen shot 2016-09-23 at 10 06 40 am](https://cloud.githubusercontent.com/assets/94150/18790728/79c3ee72-8175-11e6-8d98-106cf9c336ec.png)

Furthermore, please ensure that you're using the sandbox client ID in your mobile app in sandbox mode and your server side app is also using the sandbox client ID and secret in sandbox mode.

You may find [additional Paypal Future Payment documentation here](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_mobile.md) helpful (linked off the README.md). The [server side doc](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_server.md) might also be useful.

**Comment by Miteshimmply** [comment]
Thanks for reply.
I want to use only Paypal login future. I am using Paypal as social login so i need user detail so i read your document but something is missing so can you give me some step to integrate Paypal login for iOS mobile Application.

**Comment by bluk** [comment]
The [Profile Sharing](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/profile_sharing_mobile.md) documentation is the most appropriate.

You will need to specify the scopes you want in the client code (step 5 in [Obtaining User Consent](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/profile_sharing_mobile.md#obtain-customer-consent) ).

Also, in that same page with the REST API credentials in the developer dashboard (where you got your client ID/secret), please ensure that you have the correct scope permissions set there as well and the URLs for privacy policy and user agreement are correct.

![screen shot 2016-09-26 at 11 19 00 am](https://cloud.githubusercontent.com/assets/94150/18842619/388766f6-83db-11e6-8ad4-aaf97bf3412b.png)

**Comment by bluk** [comment]
I'm closing this since there isn't any activity. If you're still encountering an issue, please leave a comment and we can reopen. Thanks.

**Comment by Miteshimmply** [comment]
Thanks please close this but i have a question:

Sandbox will allow login only sandbox user not very user, Right?
Production will allow every user, Right?

So i will keep both PayPalEnvironmentProduction and PayPalEnvironmentSandbox , It will take as per environment , when i put my application on app store it will Take production only if i selected production mode in code.

**Comment by bluk** [comment]
Yes. Just to be clear, sandbox environment only allows sandbox users to be logged in. Production only allows live/real accounts to log in (sandbox accounts cannot log into the regular live production environment).

You can keep both client IDs but you must set the environment to `PayPalEnvironmentProduction` like you said in the app store.

**Comment by Miteshimmply** [comment]
Thanks A lot

**Comment by Miteshimmply** [comment]
I have set Below credential for live production with paypal Login

      <key>PayPalEnvironmentProduction</key>
       <string>Live Production Client ID</string>
        <key>PayPalEnvironmentSandbox</key>
        <string>Sandbox Client ID</string>
        <key>PayPalClientID</key>
        <string>Live Production Client ID</string>
        <key>PayPalSecretKey</key>
        <string>Live Production Secret Key</string>

I am getting error window on Login page Please find attached file.

Thanks a lot.
![simulator screen shot 17-oct-2016 5 56 46 pm](https://cloud.githubusercontent.com/assets/22363445/19440238/cafa8aa8-949e-11e6-9b1d-f8481957a205.png)

**Comment by bluk** [comment]
First, you should not be embedding your client secret into your mobile application:

```
    <key>PayPalSecretKey</key>
    <string>Live Production Secret Key</string>
```

It is a security issue if someone reverse engineers your app and is able to get both your client ID and secret.

Second, can you please open a new issue with a PayPal-Debug-ID that you get from your logs? Be sure that you have actually switched the PayPalEnvironment in your code. The error could be many different things.

**Comment by bluk** [comment]
BTW, if there isn't a PayPal-Debug-ID, can you please do a `traceroute api-m.sandbox.paypal.com` and copy the command's output into the issue (for at least the last few hops)? That could help isolate network issues.

**Comment by Miteshimmply** [comment]
Thank for Reply.
I have set PayPalEnvironment = PayPalEnvironmentProduction

I have make set of Key/Value in Plist File:
<key>PayPalEnvironmentProduction</key>
   <string>Live Production Client ID</string>
    <key>PayPalEnvironmentSandbox</key>
    <string>Sandbox Client ID</string>
    <key>PayPalClientID</key>
    <string>Live Production Client ID</string>
    <key>PayPalSecretKey</key>
    <string>Live Production Secret Key</string>

**in Paypal iOS Integration there is a syntax , it is compulsory to add in APPDelegate.m File like below:**
**[PayPalMobile initializeWithClientIdsForEnvironments:@{PayPalEnvironmentProduction:PayPalEnvironmentProductionString ,PayPalEnvironmentSandbox:PayPalEnvironmentSandboxString}];**

1) First we get authorisation code.
2) Then i call Paypal API : **https://api.paypal.com/v1/oauth2/token**   with Body **grant_type=authorization_code&response_type=token&redirect_uri=urn:ietf:wg:oauth:2.0:oob&code=%@**   With Additional Header 
@"Accept": @"application/json", @"Accept-Language": @"en_US", @"Content-Type": @"application/x-www-form-urlencoded",@"Authorization": credentials}

in Above Authorization key i pass value as Basic ClientID:SecretKey(Which i took from Plist file) 
so secret key and client ID is compulsory to make Authorization successful.

Can you please tell me where i am wrong , Please suggest me.

**Comment by bluk** [comment]
The code where you are exchanging the authorization code for a token should be running on your server. So everything including and after the:

```
1) First we get authorisation code.
2) Then i call Paypal API : https://api.paypal.com/v1/oauth2/token with Body grant_type=authorization_code&response_type=token&redirect_uri=urn:ietf:wg:oauth:2.0:oob&code=%@ With Additional Header 
@"Accept": @"application/json", @"Accept-Language": @"en_US", @"Content-Type": @"application/x-www-form-urlencoded",@"Authorization": credentials}
```

should only be done on a secure server.

See the documentation for [Future Payments](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_server.md#exchange-authorization-code-for-refresh--access-tokens) and [Profile-Sharing](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/profile_sharing_server.md) for more information.

**Comment by Miteshimmply** [comment]
Thanks but i am only using Paypal login for user detail so i am not sending authorisation code to server i am using of your api call like below:

1) - (void)payPalProfileSharingViewController:(PayPalProfileSharingViewController *)profileSharingViewController
             userDidLogInWithAuthorization:(NSDictionary *)profileSharingAuthorization
{      
    [self sendProfileSharingAuthorizationToServer:profileSharingAuthorization];     
}

- (void)sendProfileSharingAuthorizationToServer:(NSDictionary *)authorisation
{
   In this i got authorisation code and i pass to like below

grant_type=authorization_code&response_type=token&redirect_uri=urn:ietf:wg:oauth:2.0:oob&code=%@  and additional header needs for authorisation is (Basic PayPalClientID:PayPalSecretKey)
}

2) I got Refresh token from above response And i pass to like below :
 [self refreshAccessToken:refresh_token];
3) I got access token by passing refresh token and i pass to like below:
 [self fetchUserInfoWithAccessToken:access_token];
4) I got user detail by passing (Bearer accessToken)

i don't need to send any detail to server , all this thing i got calling all your paypal api.

**Comment by bluk** [comment]
@Miteshimmply You must send the authorization code to a secured server. While you can do what you described, the API you are using is for server side integrations and is insecure to directly call in a mobile app.

The client secret should never be in a mobile app. If someone looks at your Info.plist (or otherwise reverse engineers your app) and gets your client ID and secret, they can do anything that you are authorized to do (e.g. make illegitimate charges, cause you to refund payments, steal customer information, etc. which could potentially lead to financial and legal penalties similar to violating PCI compliance). While the integration is more complicated, it is for your customers' safety and your own that you secure your code and integration.

**Comment by Miteshimmply** [comment]
Thanks for reply.

**Comment by bluk** [comment]
@Miteshimmply For 1), yes. Please see https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/profile_sharing_server.md for how to integrate with your server. Everything after "Obtain an Authorization Code" must be done only on the server.

For 2) you should not take the client ID/secret as a parameter for security reasons, but I can't recommend what to do since every server environment is unique on how to secure your credentials. I suggest hiring a security consultant or an integration engineer to help.

**Comment by kamanijenis16** [comment]
![simulator screen shot - iphone 6s - 2018-02-03 at 18 05 29](https://user-images.githubusercontent.com/36103974/35767163-dca4daf4-090c-11e8-82bd-d146e884f5fd.png)

PayPalPaymentViewController in not visible LogIn button right side.
