### ISSUE TITLE
Checkout proccess - Paypal and App Mobile

### ISSUE THREAD

**Issue by Abreu0101** [paypal/PayPal-iOS-SDK#469]
I have an app when user can buy products, and i'm using Paypal to manage the transaction, from there i send the response to my server to validate the transaction Id and give the product to the user.

So the proccess is: App -> Paypal > MyServer

My question is, how can I manage múltiple user buying, when for example there is only one product in stock.

Example: I could check the quantity in stock before open the Paypal checkout screen, but can happen that two user open the checkout proccess(because there is still one product) and Paypal will take the Money (of the two, but only the first response that I receive from server will be the valid).. So, what can we do in that cases?

Sorry not sure, if we can post questions here (not an issue per se).
Thanks in advance

**Comment by bluk** [comment]
@Abreu0101 Some web store software puts a lease/reservation on items put into a shopping cart to prevent this scenario. So this will decrement the stock inventory count temporarily and may help prevent completing a checkout without having any inventory in stock. You'll need to see if your server software supports this.

From PayPal's perspective, you may want to see if the [authorize/capture](https://developer.paypal.com/docs/integration/direct/capture-payment/) or [order](https://developer.paypal.com/docs/integration/direct/create-process-order/) flow is right for you.

In the event that you take orders you cannot fulfill or need to give back the money for some other reason, you can use the [refund APIs](https://developer.paypal.com/docs/integration/direct/refund-payment/). However, you should not use refunds as your primary method for handling this scenario (e.g. if you refund most of your payments, then your account may be identified as having significant risk which you will need to resolve with account support).

Hope that helps!
