### ISSUE TITLE
Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. 

### ISSUE THREAD

**Issue by shu-ua** [paypal/PayPal-iOS-SDK#470]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal iOS SDK Version: 
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.): iOS 10.0 on iPhone Simulator
- PayPal-Debug-ID(s) (from any logs): a9740cfac4f01

### Issue Description
During 2 weeks, when I trying to make Paypal payment on sandbox I got the messages  - "There was a problem setting up this payment. Please visit the PayPal website to check your account.".

I tried to use several accounts with different currencies, creating a new app in PayPal, etc.

Log: 
> 2016-10-05 02:43:17.336 *[42300:5485478] PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: a9740cfac4f01, a9740cfac4f01 [sandbox, PayPal iOS SDK 2.15.1]

Screenshot: 
<img width="311" alt="screenshot at oct 05 02-50-15" src="https://cloud.githubusercontent.com/assets/2602405/19096742/80869b7a-8aa7-11e6-9936-2306e6df4ade.png">

**Comment by bluk** [comment]
Looking at the `a9740cfac4f01` request, it seems you are using paying yourself (e.g. using the account associated with the client ID/secret to pay yourself).  In the sandbox test environment, you will need to create a [test PayPal account](https://developer.paypal.com/developer/accounts/) and use it instead to login and pay.

**Comment by sauchye** [comment]
> PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: cbe13fe2eb5f4, cbe13fe2eb5f4 [live, PayPal iOS SDK 2.18.1]

As same me, I register new account , and other account test but tips me
