### ISSUE TITLE
App freeze when start

### ISSUE THREAD

**Issue by balkarov** [paypal/PayPal-iOS-SDK#471]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal iOS SDK Version: 2.15.1
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.): iPhone 6s iOS 10
- PayPal-Debug-ID(s) (from any logs):

### Issue Description
Hello!
When I call this (in didFinishLaunchingWithOptions)
```
    [PayPalMobile initializeWithClientIdsForEnvironments:@{
        PayPalEnvironmentProduction : @"my key",
        PayPalEnvironmentSandbox : @"my key"
    }];
```

App freeze 5 seconds 

My solution: I run this method in background 

```
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        [PayPalMobile initializeWithClientIdsForEnvironments:@{
            PayPalEnvironmentProduction : @"my key",
            PayPalEnvironmentSandbox : @"my key"
        }];
    });
```

But is it normal? Or has other solution?

**Comment by bluk** [comment]
@balkarov It isn't normal. I don't have an exact iPhone 6s but on a couple of different phones with iOS 10, the sample apps don't exhibit this behavior. Does the sample app in this repository also show this?

**Comment by balkarov** [comment]
I cannot show here sample app with my secret keys. In the simulator I have the same problem. 
But when I remove this method all work good.

**Comment by balkarov** [comment]
I download simple project from this repo and it has the same problem.
Run app, and 3-5 seconds app freeze

**Comment by balkarov** [comment]
Can somebody help me?

**Comment by balkarov** [comment]
Why is   dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)... is not normal?

**Comment by bluk** [comment]
The `dispatch_async` solution should be ok as long as you guarantee that the `initializeWithClientIdsForEnvironments` call returns before you call any other PayPal method.

As far as why it is slow on your system, I'm not sure and haven't been able to reproduce on a couple of different devices using the sample in this repository.

**Comment by balkarov** [comment]
Hmm... It's very strange. Now all work good. In all devices my app and sample app from this repo.

**Comment by bluk** [comment]
I'm not too sure but if the issue re-occurs, please leave a comment and anything else you discover if possible. Thanks.
