### ISSUE TITLE
PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500

### ISSUE THREAD

**Issue by DannyGlover** [paypal/PayPal-iOS-SDK#472]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal iOS SDK Version: 2.15.1
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.): iOS sim and iOS 10.x iPhone 5, 5s, 6s
- PayPal-Debug-ID(s) (from any logs): 4aa9a9e6d4526, 4aa9a9e6d4526

### Issue Description
> Please include as many details (logs, steps to reproduce, screenshots) as you can to help us reproduce this issue faster.

PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 4aa9a9e6d4526, 4aa9a9e6d4526 [sandbox, PayPal iOS SDK 2.15.1]

PayPal was working fine in sandbox mode for me yesterday, today I keep getting the above error.

I noticed on the status site that PayPal was doing maintenance work on their sandbox site, but it's marked as complete and it's still not working.

What's going on PayPal?

**Comment by bluk** [comment]
There is a sandbox issue at the moment. This may be related to https://github.com/paypal/PayPal-PHP-SDK/issues/676 but I also opened internal tracking issue PPPLPAYPT-13517 for mobile SDKs. My apologies for the issue.

**Comment by DannyGlover** [comment]
Thank you @bluk !

Appreciate it

**Comment by bluk** [comment]
This should be fixed now. I was able to execute a payment earlier using the iOS SDK. If you're still encountering an issue, please leave a comment. Thanks for your patience and our apologies for the issue.

**Comment by DannyGlover** [comment]
Hey @bluk 

This was fixed, but it is now failing again intermittently

**Comment by bluk** [comment]
Opened internal issue SRE-43445 for tracking the intermittent issue. Thanks.

**Comment by Apofeozzz** [comment]
Today I've got the same issue -
PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: ce419dcf93d92, ce419dcf93d92 [sandbox, PayPal iOS SDK 2.14.7]

**Comment by manuel-norsync** [comment]
Seems like it is failing again intermittently. 
Error: "System Error. Please try again later"
I am using the "pay with card" option.

**Comment by bluk** [comment]
This issue should now be resolved. Thanks for your patience.

**Comment by Apofeozzz** [comment]
Thanks. Now it seems to work fine.

**Comment by pooja816** [comment]
Hi...
Today I got the issue
PayPal SDK: Request has failed with error: internal_error - Internal Error (500) | PayPal Debug-ID: 39b81f477fea7, 39b81f477fea7 [sandbox, PayPal iOS SDK 2.14.5] | Details: (
        {
        "error_description" = "Connection time out during load_user_data";
    }
).

**Comment by bluk** [comment]
@pooja816 The error was an internal error that should now be resolved. I was able to successfully test with sandbox earlier this morning. If you encounter similar errors, please open a new issue (the 500 error response is a generic response which can be unrelated to previous 500 errors).
