### ISSUE TITLE
Is there an option to remove a direct payment per country?

### ISSUE THREAD

**Issue by demiangreen** [paypal/PayPal-iOS-SDK#474]
We we work on local Russian market and the direct payments are not supported here. Our users tap on direct payment option and loose time entering cards number or scanning the card. Is there an option to remove a direct payment per country?

**Comment by bluk** [comment]
You can disable direct credit cards via https://github.com/paypal/PayPal-iOS-SDK/blob/master/PayPalMobile/PayPalConfiguration.h#L52 .

Note that direct credit cards are deprecated in general for this mobile SDK as of [2.16.0](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.16.0). You should also be aware that Direct Credit Card support in this SDK is limited based on [your account's country](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/). I would try to look at the [Braintree SDKs](https://www.braintreepayments.com) if you are interested in credit card support.

If you still have a question, please leave a comment and we'll reopen the issue. Thanks!
