### ISSUE TITLE
To process your delivery, the following issues must be corrected:  Invalid Bundle Structure - The binary file 'thisisappname.app/PayPalMobile/libPayPalMobile.a' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles.

### ISSUE THREAD

**Issue by quocbao1087** [paypal/PayPal-iOS-SDK#475]
### Required Information

- Mode (Mock/Sandbox/Live):LIVE submit to Store

### Issue Description
Hi, when I submit app to itunesconnect
They reply an email to me with this content:
" We have discovered one or more issues with your recent delivery for "This is App Name". To process your delivery, the following issues must be corrected:

Invalid Bundle Structure - The binary file 'thisisappname.app/PayPalMobile/libPayPalMobile.a' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide for information on the iOS app bundle structure. "

I tested ok when I install ipa to iphone for development.

**Comment by bluk** [comment]
@quocbao1087 It seems you are including the static library in your app distribution. You do not need to copy the static library into your app's resources. So in your app target's Build Phases, I would look into the `Copy Bundle Resources` phase or any other Copy Files phase and remove the static library there. You must have the static library in the `Link Binary with Libraries` phase.

**Comment by bluk** [comment]
If this is still an issue, please leave a comment, and we'll reopen. Thanks!

**Comment by amit-pandey11** [comment]
Hi, I also have the same issue, How to solve this? I have check that the .a file is only in the pod section and nowhere else in the project. When I run the project on my simulator and device it works fine but when I try to upload the app to then it shows the error:

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'myIosApp.app/libPayPalMobile.a' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

**Comment by xiaoleih41** [comment]
@amit-pandey11 This SDK has been deprecated. Please consider to integrate Express checkout via Braintree SDK or Braintree direct SDK instead. For detail please check the [READ.MD](https://github.com/paypal/PayPal-iOS-SDK).
