### ISSUE TITLE
DUPLICATE_REQUEST_ID - System error.

### ISSUE THREAD

**Issue by manish-1612** [paypal/PayPal-iOS-SDK#476]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal iOS SDK Version: PayPal iOS SDK 2.14.7
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.): iOS 9.3, iPhone 5S simulator
- PayPal-Debug-ID(s) (from any logs): PayPal Debug-ID: 77a0089627fdf, 77a0089627fdf

### Issue Description
> I am trying to integrate PayPal in my Test App. While running the app in Sandbox mode, it is providing me an error
`PayPal SDK: Request has failed with error: DUPLICATE_REQUEST_ID - System error. Please try again later. (400)` 

For reference, I am attaching the code where I am integrating Paypal in my app

`
import UIKit

class ViewController: UIViewController{
    
    var payPalConfig : PayPalConfiguration!
    

    // MARK :- Lifecycle methods
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        payPalConfig = PayPalConfiguration()
        payPalConfig.acceptCreditCards = true
        payPalConfig.merchantName = "MERCHANT_EMAIL"

        payPalConfig.merchantPrivacyPolicyURL = NSURL(string: "https://www.paypal.com/webapps/mpp/ua/privacy-full")
        payPalConfig.merchantUserAgreementURL = NSURL(string : "https://www.paypal.com/webapps/mpp/ua/useragreement-full")
        payPalConfig.languageOrLocale = NSLocale.preferredLanguages()[0]
        payPalConfig.payPalShippingAddressOption = PayPalShippingAddressOption.PayPal
        print("sdk : \(PayPalMobile.libraryVersion())")
    }
    
    override func viewWillAppear(animated: Bool) {
        //do as per your desire
        
        PayPalMobile.preconnectWithEnvironment(PayPalEnvironmentSandbox)

    }
    
    override func viewWillDisappear(animated: Bool) {
        //do as per your desire
    }
    
    override func viewDidAppear(animated: Bool) {
        //do as per your desire
    }
    
    override func viewDidDisappear(animated: Bool) {
        //do as per your desire
    }
    
    // MARK :- Memory warning handling
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    @IBAction func makePaymentProcess(sender: UIButton) {
        
        let item1 = PayPalItem(name: "iPhone5S", withQuantity: 3, withPrice: NSDecimalNumber(double : 755.00), withCurrency:"USD", withSku: "SKU-iPhone5S")
        let item2 = PayPalItem(name: "MacbookAir", withQuantity: 2, withPrice: NSDecimalNumber(double : 1669.00), withCurrency:"USD", withSku: "SKU-MacBookAir")
        
        
        let items = [item1, item2]
        
        let subTotal = PayPalItem.totalPriceForItems(items)
        let shippingAddress = NSDecimalNumber(string: "5.66")
        let tax = NSDecimalNumber(string: "1.25")
        
        let paymentDetails = PayPalPaymentDetails(subtotal: subTotal, withShipping: shippingAddress, withTax: tax)
        let total  = (subTotal.decimalNumberByAdding(shippingAddress)).decimalNumberByAdding(tax)
        
        
        let payment = PayPalPayment(amount: total, currencyCode:"USD" , shortDescription: "My payment 2", intent: PayPalPaymentIntent.Sale)
        payment.items = items
        payment.paymentDetails = paymentDetails
        
        
        if payment.processable{
            let paymentVC = PayPalPaymentViewController(payment: payment, configuration: payPalConfig, delegate: self)
            self.presentViewController(paymentVC!, animated: true, completion: nil)
        }else{
            print("Payment not processable: \(payment)")
        }
    }
    

}

//MARK:- Paypal Delegates
extension ViewController : PayPalPaymentDelegate{
    
    func payPalPaymentDidCancel(paymentViewController: PayPalPaymentViewController) {
        //do something
        print("failure payment cancelled")
        self.dismissViewControllerAnimated(true, completion: nil)
    }
    
    
    
    func payPalPaymentViewController(paymentViewController: PayPalPaymentViewController, didCompletePayment completedPayment: PayPalPayment) {
        //do something
        print("success in did complete")
        print("PAYEMENT : \(completedPayment)")
        self.dismissViewControllerAnimated(true, completion: nil)
    }
    
    
    
    func payPalPaymentViewController(paymentViewController: PayPalPaymentViewController, willCompletePayment
        completedPayment: PayPalPayment, completionBlock: PayPalPaymentDelegateCompletionBlock) {
        
        
      //print("confirmation : \(completedPayment.confirmation)")
        
       completionBlock()
    
    }
}`

Please help me out.
Thank You.

**Comment by bluk** [comment]
Hi, the underlying error seems to indicate the domestic transaction is unsupported. Please ensure that [your account is supported for credit card transactions](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/). Usually this is because the sandbox merchant account is located in an unsupported country. For instance, if your merchant account is based in India, then direct credit card transactions are not supported for your country.

Also, please note that direct credit card support has been deprecated in this SDK as of the latest [version 2.16.0](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.16.0). I strongly suggest for any new integration to see if [Braintree Payments](https://www.braintreepayments.com) can support you. Please check if they support your country as well.
