### ISSUE TITLE
How to clear stored user-data ? 

### ISSUE THREAD

**Issue by manuel-norsync** [paypal/PayPal-iOS-SDK#478]
### Issue Description
> Is there a way to remove all stored data from Users, like accounts and credit cards numbers?
I know  that there is an option to prevent that. But I am looking for an option to do it dynamically.

Thanks.

**Comment by bluk** [comment]
Does the [`clearAllUserData` method](https://github.com/paypal/PayPal-iOS-SDK/blob/master/PayPalMobile/PayPalMobile.h#L76) work for you or are you looking for something else?

**Comment by manuel-norsync** [comment]
Yes @bluk, that was exactly what was a looking for. 
Sorry to bother you, but how can I call it from my App?
Because I couldn't find that method in the paypal-payments.js. Should I added in there? 

Thanks.
