### ISSUE TITLE
Not able to install pod 'PayPal-iOS-SDK' for target 9.0 in xcode 7.3.1 

### ISSUE THREAD

**Issue by Anilkr91** [paypal/PayPal-iOS-SDK#479]
[!] Error installing PayPal-iOS-SDK
[!] /usr/bin/git clone https://github.com/paypal/PayPal-iOS-SDK.git /var/folders/tb/c82x4b7x7b38cl8gz1gsywp40000gn/T/d20161029-4115-1t36mub --template= --single-branch --depth 1

Cloning into '/var/folders/tb/c82x4b7x7b38cl8gz1gsywp40000gn/T/d20161029-4115-1t36mub'...
error: RPC failed; curl 56 SSLRead() return error -36
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:122:in `rescue in execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:120:in`execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.0.0/lib/cocoapods-downloader/base.rb:154:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.0.0/lib/cocoapods-downloader/git.rb:64:in`block in clone'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:153:in `block in ui_sub_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in`section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:152:in `ui_sub_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.0.0/lib/cocoapods-downloader/git.rb:62:in`clone'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.0.0/lib/cocoapods-downloader/git.rb:30:in `download!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.0.0/lib/cocoapods-downloader/base.rb:82:in`block in download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:137:in `block in ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in`section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:136:in `ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.0.0/lib/cocoapods-downloader/base.rb:80:in`download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:103:in `download_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:70:in`download_request'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:170:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:153:in`block in uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:180:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:180:in`in_tmpdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:152:in `uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:33:in`download_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:39:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/external_sources/abstract_external_source.rb:114:in`block in pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:84:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/external_sources/abstract_external_source.rb:112:in`pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:479:in`fetch_external_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:455:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:454:in`each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:454:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in`section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:453:in `fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:73:in`analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:227:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:151:in`block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:150:in`resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in`run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in`run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in`load'
/usr/local/bin/pod:22:in `<main>'

**Comment by bluk** [comment]
This is an issue with the size of the repository and curl being able to maintain a connection apparently. We are looking into possible solutions, but one possible workaround for now is to clone the repository and have your Podfile point to your local repository instead:

See https://guides.cocoapods.org/using/the-podfile.html#using-the-files-from-a-folder-local-to-the-machine .

**Comment by bluk** [comment]
Closing this issue because this SDK has been deprecated. Existing integrations will be supported but new integrations should use [Braintree Direct](https://www.braintreepayments.com/products/braintree-direct) in [supported countries](https://www.braintreepayments.com/country-selection). In other countries, use [Express Checkout](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/) and choose the Braintree SDK integration option.

The git repository for the Braintree iOS SDK should not have these issues.
