### ISSUE TITLE
Express Payment via Creditcard

### ISSUE THREAD

**Issue by nordfogel** [paypal/PayPal-iOS-SDK#48]
Hi,

is there a way to start the card reader/scanner directly from within the PayPalPaymentViewController? We do not want the extra screen displaying paypal and credit card button. Our intention is to place those two buttons in our own view controller next to three more payment options. From this view controller both buttons will start the PayPalPaymentViewController straight forward to the choice we did before BUT we would like to avoid the upcoming choice of paypal or credit card and want to force one or the other directly without another tab of the user.

Thanks a lot for your help!

**Comment by tomwhipple** [comment]
The current recommendation would now be to use [Braintree](https://braintreepayments.com). The UI is quite customizable and the product is designed to minimize PCI work.
