### ISSUE TITLE
failed to pod 'PayPal-iOS-SDK' keep Installing CardIO(5.3.2)

### ISSUE THREAD

**Issue by ywqqqqq** [paypal/PayPal-iOS-SDK#480]
platform : ios, '7.0'
Xcode version   :  XCode 8.0
cocoapods version : 1.0.1

when i pod install --no-repo-update
it always keeps Installing CardIO (5.3.2)...

**Comment by RoraxHan** [comment]
I have same problem now.
Did you solve this problem?
