### ISSUE TITLE
PayPal-iOS-SDK/PayPalMobile.h file not found

### ISSUE THREAD

**Issue by 15038777234** [paypal/PayPal-iOS-SDK#482]
I use Cocoapods for hosting, but prompt PayPal - iOS - SDK/PayPalMobile. H file not found.I can compile operation, is can't prompt knock code, run on Xcode8.1 version
![qq20161109-0](https://cloud.githubusercontent.com/assets/4713847/20135206/8a5fe052-a6a9-11e6-884b-b563f2c9cd2c.png)
![qq20161109-1](https://cloud.githubusercontent.com/assets/4713847/20135215/9014c148-a6a9-11e6-8899-21b8113cad38.png)

**Comment by bluk** [comment]
Hi, can you please try using `#import "PayPalMobile.h"` and seeing if that works?

**Comment by 15038777234** [comment]
@bluk `#import "PayPalMobile.h"`， I tried to hold the wrong, because I use cocoapods custody.I try not cocoapods hosting today, try added directly to the project.

**Comment by 15038777234** [comment]
@bluk Now drag and drop directly to the project give you code, I have removed the cocoapods custody.But I don't know what the reason, I have three colleagues.A colleague to update I submit code can normal tip, but I met the same problem with another.We use are Xcode8 development tool, the computer system is the same.This is not the Xcode8 bug
![qq20161110-0](https://cloud.githubusercontent.com/assets/4713847/20160277/ba2cfd98-a720-11e6-811d-0908eb7afbea.png)

**Comment by bluk** [comment]
Based on your progress in issue #483, it seems that you have solved your issue here. If that is not the case, please leave a comment or open a new issue.
