### ISSUE TITLE
Implement recurring functionality using Paypal iOS SDK and Android SDK

### ISSUE THREAD

**Issue by rushabh0999** [paypal/PayPal-iOS-SDK#486]
I want to implement recurring payment in Android/iOS Application using PayPal sdk. 

I am not looking for web bases services where browser will open within Application and it will process recurring payment on paypal. I want to implement recurring payment via PayPal SDK only.

**Comment by bluk** [comment]
@rushabh0999 Recurring payment isn't planned currently for these SDKs. I suggest looking at the [Braintree Payments](https://www.braintreepayments.com) iOS and Android SDKs which support vaulted payment methods (including PayPal). You may be able to use the [recurring billing functionality](https://developers.braintreepayments.com/guides/recurring-billing/overview). Please feel free to contact [Braintree Support](support@braintreepayments.com) to see if it meets your needs.
