### ISSUE TITLE
Sandbox returning INTERNAL SERVICE ERROR on iPod

### ISSUE THREAD

**Issue by joaocruz04** [paypal/PayPal-iOS-SDK#487]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal iOS SDK Version: 2.16.1
- iOS Version and Device: iPod (MKH62FD/A) with iOS 9.3 (13E233)
- PayPal-Debug-ID(s) (from any logs): 657662c469f05, 657662c469f05

### Issue Description
I initiate a payment in sandbox, then I use my testing account and it returns an INTERNAL_SERVICE_ERROR. 

`PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 657662c469f05, 657662c469f05 [sandbox, PayPal iOS SDK 2.16.1]`

This only occurs in this iPod. If I run the same build on my iPhone with iOS10, everything goes smooth.

**Comment by joaocruz04** [comment]
Now in the evening, it is happening too with the iPhone..

Mode (Mock/Sandbox/Live): Sandbox
PayPal iOS SDK Version: 2.16.1
iOS Version and Device: iPhone 6S (MKQN2QL/A) with iOS 10.1.1 (14B150)
PayPal-Debug-ID(s) (from any logs): 930b60d23b0c1, 930b60d23b0c1

**Comment by jaypatel512** [comment]
Hey @joaocruz04 !

We had some sandbox issues last weekend, and caused a lot of payments to throw this error. Can you please try and check again and see if you are still seeing this error.

Please re-open this issue if this is still reproducible. Thanks.
