### ISSUE TITLE
Pay with Credit Card navigation bar tint color

### ISSUE THREAD

**Issue by bmctigue** [paypal/PayPal-iOS-SDK#49]
Hi,

It seems the barTintColor on the navigation bar in the pay with credit card screen is hardcoded to white. We need the text(tint color) to be white, so we need to be able to change the background color of the nav bar. Could you please adjust this so the nav bar honors the appearance setting for the nav bar barTintColor. We would like to release an app with a week that depends on this. Any quick help would be much appreciated.

Bruce McTigue

**Comment by bayraa1992** [comment]
@ssuchanowski 
you should change navigationBarColors 

    [[UINavigationBar appearance] setTintColor:nil];
    [[UINavigationBar appearance] setTitleTextAttributes:@{ NSForegroundColorAttributeName : [ConstantValues systemBlackColor]}];
    [[UINavigationBar appearance] setBarTintColor:nil];
}

before presenting PayPalPaymentViewController
and  write restore navigationbarColors in the 
viewWillAppear on presentedViewController

**Comment by ssuchanowski** [comment]
@bayraa1992 - please read the post first. I posted the exact solution there.
