### ISSUE TITLE
Method TotalPriceforItem from PayPalItem Class gives 0 value

### ISSUE THREAD

**Issue by luthfifr** [paypal/PayPal-iOS-SDK#490]
### Required Information

- Mode (Mock/Sandbox/Live): Mock/Sandbox
- PayPal iOS SDK Version: 2.16
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.): iOS 10.1/iPhone 7+ until 4
- PayPal-Debug-ID(s) (from any logs): 76653:7061696

### Issue Description
I have an issue that method TotalPriceforItem from PayPalItem class gives 0 value, it suppose to give me not a 0 value because the PayPalItem array is not empty and the price of the product is showing up correctly. Here's the code snippet:
![paypal_code snippet](https://cloud.githubusercontent.com/assets/22187764/20787449/6b8c0962-b7de-11e6-8f65-c87010d4b4c7.png)

And here's what printed in debugger:
![paypal_debugger](https://cloud.githubusercontent.com/assets/22187764/20787483/9b725eb0-b7de-11e6-8c6e-9e36c34f992f.png)

What did I do wrong? Thank you.

**Comment by bluk** [comment]
For the above code, what is `item`? `PayPalItem.totalPrice` is expecting an array of `PayPalItem` types and ignores objects which are not of type `PayPalItem`. It seems that `items.append(item)` is appending an array of items to an array of items but not entirely sure.

**Comment by luthfifr** [comment]
sorry I made a little mistake, I wasn't aware that I created another array in var item. It solved.

**Comment by posakya** [comment]
@luthfifr i am also facing same problem how did you solved this problem.. can you help me to shot out this problem
