### ISSUE TITLE
Errors about OpenURL

### ISSUE THREAD

**Issue by bradXie1992** [paypal/PayPal-iOS-SDK#492]
Hi,
We get bug reports from our users claiming to receive error message :
-canOpenURL: failed for URL: "org-appextension-feature-password-management://" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"

How to solve this problem?

**Comment by bluk** [comment]
Are your users other developers (e.g. you have a built a library that incorporates the PayPal-iOS-SDK)? Also, is this with a device or just the simulator? Previous developers have had the `OSStatus error -10814` error show up in the simulator but not in the real device.

In general, this message indicates that the 1Password functionality is not available. See https://github.com/paypal/PayPal-iOS-SDK/issues/324#issuecomment-185801166 for more details.
