### ISSUE TITLE
I am getting error "invalid client credentials"

### ISSUE THREAD

**Issue by vijju31198** [paypal/PayPal-iOS-SDK#495]
I am getting error "invalid client credentials" while trying to getting Access token with valid client Id, secret, refresh token to URL https://api.sandbox.paypal.com/v1/oauth2/token

 Please help me to resolve this error.

Content Type - application/x-www-form-urlencoded; charset=UTF-8

**Paypal-Debug-Id:** 3727fafea4bd2
**Complete Error** 

HttpResponseProxy{HTTP/1.1 401 Unauthorized [Date: Tue, 17 Jan 2017 16:22:30 GMT, Server: Apache, paypal-debug-id: 3727fafea4bd2, Paypal-Debug-Id: 3727fafea4bd2, Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D3326377560%26HTTP_X_PP_AZ_LOCATOR%3D; Expires=Tue, 17 Jan 2017 16:52:30 GMT; domain=.paypal.com; path=/; Secure; HttpOnly, Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT, Content-Length: 0, Connection: close, Content-Type: text/plain; charset=ISO-8859-1] [Content-Type: text/plain; charset=ISO-8859-1,Content-Length: 0,Chunked: false]}

**Comment by bluk** [comment]
Your request seems to indicate it didn't have a valid value for the `Authorization` header (e.g. also ensure that it isn't null/empty).

Are you trying to use Future Payments or something else? You may find the [following documentation](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_server.md#refresh-an-access-token) helpful.

If you're still having an issue, please leave a comment with more details about your request (e.g. don't put in your actual client ID/secret/refresh token but the code you are using to construct your request would be helpful).
