### ISSUE TITLE
Client Authentication failed

### ISSUE THREAD

**Issue by takomborerwa** [paypal/PayPal-iOS-SDK#496]
### Required Information

- Mode (Mock/Sandbox/Live):
- PayPal iOS SDK Version:
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.):
- PayPal-Debug-ID(s) (from any logs):

- Mode -> Sandbox
- PayPal iOS SDK Version: 2.16.1
- iOS Version and Device: iOS 10 on an iPhone 6 (Simulator)
- PayPal-Debug-ID(s) (from any logs): pgdAtrkgL72AmczLVklyYnoXmZFK-8H-7ycclNcJjLk2IsEFXjFzv9b0Mvb2k4G5.U8dme-VBTapKt4WHblMmJMgL3tG

So I am trying to add log in with PayPal to the app using the following guide -> https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/profile_sharing_server.md#retrieve-customer-information. 
inside the app for the moment until I move everything to the server.

I have been able to:

1. Obtain an Authorization Code
2. Exchange Authorization Code for Refresh / Access Tokens

I am now trying to perform step 3 -> Refresh an Access Token

` 

NSString *urlString         = @"https://api.sandbox.paypal.com/v1/oauth2/token";
    NSString *accessToken       = refreshAndAccessTokenRequestResponse[@"access_token"];
    NSString *refreshToken      = refreshAndAccessTokenRequestResponse[@"refresh_token"];
    
    NSString *credentialString  = [NSString stringWithFormat:@"%@=", accessToken];
    NSData *credentialData      = [credentialString dataUsingEncoding:NSUTF8StringEncoding];
    NSString *credentials       = [NSString stringWithFormat:@"Basic %@", credentialData];
    
    NSString *grantTypeString   = [NSString stringWithFormat:@"grant_type=refresh_token&refresh_token=%@", refreshToken];
    NSData *grantTypeData       = [grantTypeString dataUsingEncoding:NSASCIIStringEncoding
                                                allowLossyConversion:YES];
    
    ASIHTTPRequest *resquest    = [[ASIHTTPRequest alloc] initWithURL:[NSURL URLWithString:urlString]];
    resquest.requestMethod      = @"GET";
    [resquest addRequestHeader:@"Content-Type"       value:@"application/x-www-form-urlencoded"];
    [resquest addRequestHeader:@"Authorization"      value:credentials];
    [resquest setPostBody:[NSMutableData dataWithData:grantTypeData]];
    [resquest startSynchronous];
`

The result of the above request is 
-> 401 Unauthorized
-> invalid_client 
-> Client Authentication failed

Which is strange because everything works until this point "Refresh an Access Token", suggesting that my client and secret keys are all correct. In addition, i have also tried with a fresh sandbox account with a new client and secret key.

Not sure what i am doing wrong here, can you help me please?

**Comment by bluk** [comment]
For anyone casually reading this, you should only do this on a secured server. If anyone is able to get your client secret (e.g. by decompiling your app), they will be able to perform actions like creating payments/refunds/etc.

That being said, your request should be similar to exchanging an authorization code for the refresh token and access token. The only real difference should be the body of the request. Setting up a NSMutableURLRequest (which would be similar to the ASIHTTPRequest) would be like:

```NSURL* URL = [NSURL URLWithString:@"https://api.sandbox.paypal.com/v1/oauth2/token"];
    NSMutableURLRequest* request = [NSMutableURLRequest requestWithURL:URL];
    request.HTTPMethod = @"POST";

    [request addValue:@"application/json" forHTTPHeaderField:@"Accept"];
    [request addValue:@"Basic <base64 encoded "clientId value:clientSecret value">" forHTTPHeaderField:@"Authorization"];
    [request addValue:@"application/x-www-form-urlencoded; charset=utf-8" forHTTPHeaderField:@"Content-Type"];

    // Should be the only real difference below
    NSDictionary* bodyParameters = @{
    	@"grant_type": @"refresh_token",
    	@"refresh_token": @"<your refresh token value>",
    };
    request.HTTPBody = [NSStringFromQueryParameters(bodyParameters) dataUsingEncoding:NSUTF8StringEncoding];```

Hope that helps!
