### ISSUE TITLE
Can not be less than 2 U.S. dollars to pay, how to deal with

### ISSUE THREAD

**Issue by lzj0718** [paypal/PayPal-iOS-SDK#502]
PayPal SDK: PayPalPayment not processable: '0.07000000000000001024' contains too many fractional digits. (For USD, can be no more than 2.)

**Comment by bluk** [comment]
You must decide when and where to round, truncate, or do other calculations to make the number acceptable for payment. You can look into `NSDecimalNumber`s rounding capabilities to help you if necessary. I would also ensure that you are using `NSDecimalNumber` for all your calculations.

**Comment by lzj0718** [comment]
thank you.According to you, the problem has been solved.
