### ISSUE TITLE
acceptCreditCards unclear

### ISSUE THREAD

**Issue by ivpusic** [paypal/PayPal-iOS-SDK#507]
Hi,

I have just a short question. Does `acceptCreditCards` option enables paying by direct credit card (requires paypal pro https://developer.paypal.com/docs/integration/direct/payments/accept-credit-cards/) or it is not using paypal pro for this, but some other paypal mechanisms to charge customer credit card?

**Comment by bluk** [comment]
@ivpusic Hello, they are not the same product. In the end, this SDK uses the PayPal REST APIs which have more limited official support than PayPal Pro for credit card flows.

I would strongly recommend that you look at [Braintree Payments](https://www.braintreepayments.com) for credit card processing and PayPal if you are interested in both. Braintree is a PayPal service. You can contact [Braintree Support](https://articles.braintreepayments.com/) at the bottom of the page to make sure it supports your currency/country and other needs. The Braintree SDKs also offer more customization than this one provides.

Hope that helps!
