### ISSUE TITLE
Paypal crash with error "-[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'"

### ISSUE THREAD

**Issue by jorden0154** [paypal/PayPal-iOS-SDK#508]
### General information

* SDK/Library version: <2.16.2>
* Environment: <Sandbox>
* `PayPal-Debug-ID` values: 
* iOS Version and Device: <ios10>
* Integration type and version: 

### Issue description

<*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000105a63d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010506ddeb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000105a0b885 -[__NSArray0 objectAtIndex:] + 101
	3   LoadArmy                            0x0000000100ae7205 +[PPAPIResponseDictionary filterResponse:type:] + 1365
	4   LoadArmy                            0x0000000100ae6844 -[PPAPIResponseDictionary initWithType:response:environemnt:] + 223
	5   LoadArmy                            0x0000000100ae6ac7 +[PPAPIResponseDictionary responseWithType:response:environment:] + 92
	6   LoadArmy                            0x0000000100ab60b9 __77-[PPServiceManager processCreditCardPayment:completion:withPreviousResponse:]_block_invoke.321 + 234
	7   LoadArmy                            0x0000000100ab5b4d __110-[PPServiceManager handleRequestResponseWithRetryBlock:withFailBlock:withCreateRequestBlock:withSuccessBlock:]_block_invoke.296 + 327
	8   LoadArmy                            0x0000000100aa8a11 -[PPServiceRequest urlConnection:didSucceedWithData:] + 278
	9   LoadArmy                            0x0000000100af28a5 __28-[PPSimpleURLConnection win]_block_invoke + 427
	10  libdispatch.dylib                   0x0000000105f02d9d _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x0000000105f233eb _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x0000000105f0b1ef _dispatch_main_queue_callback_4CF + 1738
	13  CoreFoundation                      0x00000001059bd0f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x000000010597eb99 __CFRunLoopRun + 2073
	15  CoreFoundation                      0x000000010597e0f8 CFRunLoopRunSpecific + 488
	16  GraphicsServices                    0x0000000106f1ead2 GSEventRunModal + 161
	17  UIKit                               0x000000010367df09 UIApplicationMain + 171
	18  LoadArmy                            0x0000000100a2395f main + 111
	19  libdyld.dylib                       0x0000000105f5892d start + 1
	20  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException>

**Comment by bluk** [comment]
Can you please provide more details? A backtrace would be helpful. Thanks.

**Comment by maksumon** [comment]
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000113567d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000112da921e objc_exception_throw + 48
	2   CoreFoundation                      0x000000011357f7dd -[__NSArray0 objectAtIndex:] + 93
	3   PetBacker                           0x000000010c9fa12d +[PPAPIResponseDictionary filterResponse:type:] + 1401
	4   PetBacker                           0x000000010c9f974a -[PPAPIResponseDictionary initWithType:response:environemnt:] + 230
	5   PetBacker                           0x000000010c9f99ca +[PPAPIResponseDictionary responseWithType:response:environment:] + 92
	6   PetBacker                           0x000000010c9c9d23 __77-[PPServiceManager processCreditCardPayment:completion:withPreviousResponse:]_block_invoke317 + 232
	7   PetBacker                           0x000000010c9c9750 __110-[PPServiceManager handleRequestResponseWithRetryBlock:withFailBlock:withCreateRequestBlock:withSuccessBlock:]_block_invoke290 + 289
	8   PetBacker                           0x000000010c9bd4ec -[PPServiceRequest urlConnection:didSucceedWithData:] + 278
	9   PetBacker                           0x000000010ca05007 __28-[PPSimpleURLConnection win]_block_invoke + 422
	10  libdispatch.dylib                   0x00000001146c8978 _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x00000001146f20cd _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x00000001146d28a4 _dispatch_main_queue_callback_4CF + 406
	13  CoreFoundation                      0x000000011352be49 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x00000001134f137d __CFRunLoopRun + 2205
	15  CoreFoundation                      0x00000001134f0884 CFRunLoopRunSpecific + 420
	16  GraphicsServices                    0x00000001165efa6f GSEventRunModal + 161
	17  UIKit                               0x00000001114bac68 UIApplicationMain + 159
	18  PetBacker                           0x000000010c7087af main + 111
	19  libdyld.dylib                       0x000000011473e68d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by jorden0154** [comment]
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000105a63d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010506ddeb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000105a0b885 -[__NSArray0 objectAtIndex:] + 101
	3   LoadArmy                            0x0000000100ae7205 +[PPAPIResponseDictionary filterResponse:type:] + 1365
	4   LoadArmy                            0x0000000100ae6844 -[PPAPIResponseDictionary initWithType:response:environemnt:] + 223
	5   LoadArmy                            0x0000000100ae6ac7 +[PPAPIResponseDictionary responseWithType:response:environment:] + 92
	6   LoadArmy                            0x0000000100ab60b9 __77-[PPServiceManager processCreditCardPayment:completion:withPreviousResponse:]_block_invoke.321 + 234
	7   LoadArmy                            0x0000000100ab5b4d __110-[PPServiceManager handleRequestResponseWithRetryBlock:withFailBlock:withCreateRequestBlock:withSuccessBlock:]_block_invoke.296 + 327
	8   LoadArmy                            0x0000000100aa8a11 -[PPServiceRequest urlConnection:didSucceedWithData:] + 278
	9   LoadArmy                            0x0000000100af28a5 __28-[PPSimpleURLConnection win]_block_invoke + 427
	10  libdispatch.dylib                   0x0000000105f02d9d _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x0000000105f233eb _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x0000000105f0b1ef _dispatch_main_queue_callback_4CF + 1738
	13  CoreFoundation                      0x00000001059bd0f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x000000010597eb99 __CFRunLoopRun + 2073
	15  CoreFoundation                      0x000000010597e0f8 CFRunLoopRunSpecific + 488
	16  GraphicsServices                    0x0000000106f1ead2 GSEventRunModal + 161
	17  UIKit                               0x000000010367df09 UIApplicationMain + 171
	18  LoadArmy                            0x0000000100a2395f main + 111
	19  libdyld.dylib                       0x0000000105f5892d start + 1
	20  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by bluk** [comment]
Thank you for the backtrace details. [Release 2.16.3](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.16.3) should fix the issue with parsing API responses.

**Comment by Dnyanda** [comment]
I am using  PayPal iOS SDK  2.17 in Xamarin Form, getting same error
