### ISSUE TITLE
PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR

### ISSUE THREAD

**Issue by ultranano** [paypal/PayPal-iOS-SDK#511]
### General information
* SDK/Library version: 2.16.3
* Environment: Sandbox
* `PayPal-Debug-ID` values: d1ea0bf1a981c
* iOS Version and Device: iOS 10.2 - iPhone 7
* Integration type and version: CocoaPods

### Issue description
From Today we have this message error after login on Sandbox
PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - Si è verificato un problema nella disposizione del pagamento. Vai su paypal.it e controlla il tuo conto. (422) | PayPal Debug-ID: d1ea0bf1a981c, d1ea0bf1a981c [sandbox, PayPal iOS SDK 2.16.3]

Yesterday works fine
could you please help us to debug this issue?

Best

Andrea

**Comment by bluk** [comment]
There seemed to be an issue with sandbox earlier today that was corrected. Can you please try again? I was able to make a sandbox payment a few minutes ago.

If it occurs again, please leave a comment with a PayPal-Debug-ID or open a new issue. Thanks.

**Comment by ultranano** [comment]
Thanks @bluk now works correctly!
