### ISSUE TITLE
is this SDK supports Split Payment between two Person?

### ISSUE THREAD

**Issue by kuldeep13990** [paypal/PayPal-iOS-SDK#515]
i need to split amount between two person, so my question is that is this SDK support it?

i did this before with PayPal MPL SDK but now there's BitCode Enable Issue so i am not able to do that.

**Comment by bluk** [comment]
@kuldeep13990 This SDK does not support parallel payments. See https://github.com/paypal/PayPal-REST-API-issues/issues/2 for related discussion.
