### ISSUE TITLE
CardIO delegates not getting called

### ISSUE THREAD

**Issue by MustajabJafry** [paypal/PayPal-iOS-SDK#517]
I have a question here. 
Using:

> CardIO (5.4.1)
> PayPal-iOS-SDK( 2.16.3)
> Cocoapods version: 1.2.0

I implemented **CardIOPaymentViewControllerDelegate** and **CardIOViewDelegate** delegates.
But when I enter card info or cancel the request none of the method gets called. i have searched for it but found no luck.
These are the methods:
```
func cardIOView(_ cardIOView: CardIOView!, didScanCard cardInfo: CardIOCreditCardInfo!)
{
}
```

```
func payPalPaymentDidCancel(_ paymentViewController: PayPalPaymentViewController)
{
}
```

```
func userDidProvide(_ cardInfo: CardIOCreditCardInfo!, in paymentViewController: CardIOPaymentViewController!)
{
}
```

**Comment by bluk** [comment]
The PayPal iOS SDK acts as the delegate for card.io, so you won't receive calls the card.io delegate calls. If you want credit card support using this SDK, I advise that you read the [direct credit card REST API info page](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/) to make sure your PayPal business account meets the requirements for support.

If credit/debit cards are a significant portion of your business, I would strongly consider trying to get a production account with [Braintree Payments](https://developers.braintreepayments.com/start/overview) (a PayPal service) who offer more customization, an [open source SDK](https://github.braintreeps.com/dx/braintree-ios), and more credit card options.

**Comment by Gerst20051** [comment]
Having the same issue with iOS 11. Any resolution for this?

**Comment by bluk** [comment]
@Gerst20051 Are you using card.io with the PayPal SDK? If you are, the PayPal SDK is the acting delegate for card.io, so the card.io delegate methods won't be called for you.

Have been running some tests with iOS 11.0.1 device and a 11.1 beta device, and it seems that card.io functions as it did in past iOS releases. If you have more details, can you post a new issue with the details? Thanks.

**Comment by Gerst20051** [comment]
Hey, @bluk thanks for taking some time to look into this. Using card.io a similar issue exists here. https://github.com/card-io/card.io-iOS-SDK/issues/267 Can provide anything that may help.

These two delegate methods userDidCancelPaymentViewController and userDidProvideCreditCardInfo are no longer called in iOS 11.

https://github.com/card-io/card.io-iOS-SDK/blob/master/CardIO/CardIOPaymentViewControllerDelegate.h
