### ISSUE TITLE
Incorrect fractional digits validation on PayPalPayment object

### ISSUE THREAD

**Issue by dimitar-lazarov** [paypal/PayPal-iOS-SDK#520]
### General information

* SDK/Library version: 2.16.3
* Environment: Sandbox and Production
* `PayPal-Debug-ID` values: none
* iOS Version and Device:  iOS 10.3.1 on an iPhone 6s 
* Integration type and version: CocoaPods 1.2.1

### Issue description
Steps to reproduce:
1. In the sample project single payment example set the item price as
**Swift**
`NSDecimalNumber(decimal: 84.99)`
**Objective-C**
`[[NSDecimalNumber alloc] initWithDouble:84.99]`

2. Run the sample project example - the payment fails with the following error
`PayPal SDK: PayPalPayment not processable: '216.46000000000001024' contains too many fractional digits. (For USD, can be no more than 2.)`

### Discussion
The issue appears when the value can't be represented exactly as a floating point number. When the NSDecimalNumber string initialiser is used everything works fine. If the PayPal SDK requires string initialiser to be used it would be much better to change these properties type to NSString, because there is no way to indicate that a 'wrong' initialiser has been used.

**Comment by bluk** [comment]
You're correct that the `NSDecimalNumber` string initializer should be used. We'll try to enhance the documentation and/or look into deprecating the constructors with `NSDecimalNumber` parameters.

**Comment by bluk** [comment]
Added a note to use NSDecimalNumber with strings in the headers for [2.17.0 release](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.17.0).
