### ISSUE TITLE
How to Verify the PayPal Email ID?

### ISSUE THREAD

**Issue by kuldeep13990** [paypal/PayPal-iOS-SDK#521]
I want to check wether user entered PayPal email is valid or not.

and for that i used below url.

https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize?client_id=MY-CLIENT-ID&response_type=code&scope=openid+email+address+phone&redirect_uri="MY REDIRECT URI"

I also add my URI in PayPal App Redirect URI but i get below error.

**Relying Party Validation error: scope in the request does not match any of the registered clients. Please check the request.**

How can i fix that?

**Comment by pp-randy** [comment]
Go into your [Sandbox REST APP](https://developer.paypal.com/developer/applications/) settings.  

Next go to the Log In with PayPal Advanced Options.
![image](https://cloud.githubusercontent.com/assets/6819909/25046670/5bd32e28-20f8-11e7-80f4-b7c96da89105.png)

Add the options for what you are wanting to request.
![image](https://cloud.githubusercontent.com/assets/6819909/25046761/e059c332-20f8-11e7-8995-deaf5eefd4b2.png)


At the bottom you could consider unchecking this option.  A confirmed email address means the PayPal user received the confirmation email and completed those steps. 
![image](https://cloud.githubusercontent.com/assets/6819909/25046721/b2d7916e-20f8-11e7-99a2-f7a4a07c6f88.png)

**Comment by kuldeep13990** [comment]
@pp-randy  thanks a lot man, now it's working.
