### ISSUE TITLE
 error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by Shahbaz-Akram** [paypal/PayPal-iOS-SDK#522]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* iOS Version and Device: 
* Integration type and version:

**Comment by Shahbaz-Akram** [comment]
i just drag and drop PayPalMobile folder to existing project.Follow all things which are mentioned in doc . But at the end this error received. Dont know why it is occor
![screen shot 2017-04-18 at 10 20 27 am](https://cloud.githubusercontent.com/assets/8728903/25115566/b1769efc-2420-11e7-87f7-fb791f027dcd.png)

**Comment by bluk** [comment]
I would double check if you can do a complete clean rebuild. Also, see if the library is being included more than once when you're linking. You can look at the Sample App's build settings to double check.

**Comment by Shahbaz-Akram** [comment]
Thanks for suggestion there was double copies
