### ISSUE TITLE
Application Crash when using Card io

### ISSUE THREAD

**Issue by amitdagar** [paypal/PayPal-iOS-SDK#524]
Hi ,
I am using paypal sdk for swift, and everything is working fine but when i set  `payPalConfig.acceptCreditCards = true` application get crashed when click on **pay with card button** of PayPalPaymentViewController.

**Comment by bluk** [comment]
Based on your comment on https://github.com/paypal/PayPal-iOS-SDK/issues/372, I assume this is a new integration.

As of release [2.16.0](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.16.0), credit card usage in this SDK has been deprecated, and the sample was changed to discourage usage of it. Especially note that [Direct Credit Card support](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/#direct-credit-card-payments) is only supported with specific merchant accounts in the REST API which this SDK uses. It is strongly recommended that you use [Braintree Payments](https://www.braintreepayments.com), a PayPal service, to perform credit card processing which has support for more countries.

If you use this SDK for credit card processing, you can check out version 2.15.1 and see the sample app as an example on [how to setup card.io with the SDK](https://github.com/paypal/PayPal-iOS-SDK/tree/2.15.1#if-you-dont-use-cocoapods-then). The major difference is that the card.io libraries path is added to the `Library Search Path` in the Build Settings and the card.io libraries are added to the `Link Binary with Libraries` Build Phases.

If you still have a question or issue, please leave a comment and we can reopen this issue. Thanks.
