### ISSUE TITLE
Refund methods - advice needed

### ISSUE THREAD

**Issue by rrepaka** [paypal/PayPal-iOS-SDK#525]
Hello Paypal,

We are using PAYPAL IOS SDK in our IPAD app to process credit cards. we need to implement full refunds in our app. we have seen two methods in PPHTransactionManager class

Question 1 :  can we use below method, by just passing Transaction ID to this method ?
	beginRefund:(PPHTransactionRecord *)previousTransaction 

Question 2 : what is the difference between 	
	beginRefund:(PPHTransactionRecord *)previousTransaction    VS  beginRefundUsingUIWithInvoice:(PPHInvoice *)invoice
	
	beginRefundUsingUIWithInvoice:(PPHInvoice *)invoice , do we need to pass the whole invoice object ? Or just passing invoice Id is enough ?

**Comment by bluk** [comment]
Hello, I think you've already opened this issue in the right repository for PayPal Here: https://github.com/paypal/paypal-here-sdk-ios-distribution/issues/126 so will close this issue.
