### ISSUE TITLE
INTERNAL_SERVICE_ERROR

### ISSUE THREAD

**Issue by sanket003** [paypal/PayPal-iOS-SDK#527]
### General information

* SDK/Library version: PayPal-iOS-SDK 2.17.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: ef522ec96fdca
* iOS Version and Device: iOS 10.2 on simulator
* Integration type and version: Manual

### Issue description

When I'm trying to login with PayPal, getting following error

PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: ef522ec96fdca, ef522ec96fdca [sandbox, PayPal iOS SDK 2.17.0]

P.S. - It was working few days back.

**Comment by xiaoleih41** [comment]
There was a sandbox issue last night. Please try again as it is supposed to be solved.

**Comment by xiaoleih41** [comment]
Close this case as it appears to be solved.
