### ISSUE TITLE
PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: adff3caad0c01, adff3caad0c01 [sandbox, PayPal iOS SDK 2.17.0]

### ISSUE THREAD

**Issue by pritikumbhar** [paypal/PayPal-iOS-SDK#528]
### General information

* SDK/Library version: PayPal iOS SDK 2.17.0
* Environment: Sandbox
* `PayPal-Debug-ID` values:  Debug-ID: adff3caad0c01
* iOS Version and Device: 
* Integration type and version:

**Comment by quyentrinh** [comment]
Hi, I have exact same issue today.
Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 5956b6a82adcf, 5956b6a82adcf [sandbox, PayPal iOS SDK 2.17.0]

**Comment by xiaoleih41** [comment]
There was a sandbox issue yesterday. Please check again as it is supposed to be resolved.

**Comment by xiaoleih41** [comment]
Close this thread as the issue appears to be solved.
