### ISSUE TITLE
recursive payment ??

### ISSUE THREAD

**Issue by ghimireprashant** [paypal/PayPal-iOS-SDK#529]
process for recursive payment using paypal sdk?

**Comment by xiaoleih41** [comment]
@ghimireprashant If you are looking for [future payment](https://developer.paypal.com/docs/integration/mobile/make-future-payment/). Please follow the 
 instruction listed on [README.md](https://github.com/paypal/PayPal-iOS-SDK) to integrate future payment.

**Comment by xiaoleih41** [comment]
Close this thread due to inactivity. Please resubmit if you have any questions.
