### ISSUE TITLE
Request has failed with error: closed_user - System error (closed_user)

### ISSUE THREAD

**Issue by quyentrinh** [paypal/PayPal-iOS-SDK#530]
Help me check this issue, tks.

### General information

* SDK/Library version: PayPal iOS SDK 2.17.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: ab786e0c32133
* iOS Version and Device: iOS 10.3.2 on an iPhone 5
* Integration type and version: CocoaPods 1.2.1

### Issue description

PayPal SDK: Request has failed with error: closed_user - System error (closed_user). Please try again later. (401) | PayPal Debug-ID: 5d7acef9d4ac, 5d7acef9d4ac [sandbox, PayPal iOS SDK 2.17.0] | Details: (
    {
        "error_description" = "Closed user credentials";
    }

**Comment by xiaoleih41** [comment]
The PayPal sandbox account is closed. Please go to developer.paypal.com and use an active sandbox account or create a new one.
