### ISSUE TITLE
App crash when click on "Pay with card"

### ISSUE THREAD

**Issue by kathiriyaketan57** [paypal/PayPal-iOS-SDK#531]
I  am using PayPal iOS SDK Version: PayPal iOS SDK 2.17.0 and testing app in simulator.

I got following error .............

PayPal-iOS-SDK-Sample-App[1747:63377] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present a nil modal view controller on target <PayPalPaymentViewController: 0x7ffcdb893600
Environment: sandbox
languageOrLocale: en

**Comment by xiaoleih41** [comment]
There may be some integration steps error. Can you reproduce the error by running our [sample code](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/single_payment.md)?

**Comment by kathiriyaketan57** [comment]
still same problem

**Comment by kathiriyaketan57** [comment]
ok got solution by myself

**Comment by xiaoleih41** [comment]
Closing this thread as the issue has been solved.

**Comment by vaibhav-varshaaweblabs** [comment]
@kathiriyaketan57 What's the solution? I'm also facing the same problem
