### ISSUE TITLE
Unable to use Pay with card

### ISSUE THREAD

**Issue by khush004** [paypal/PayPal-iOS-SDK#532]
hello , i have implemented this demo but i was unable to see pay with card is there something missing ?

**Comment by bluk** [comment]
Credit card payments are deprecated in this SDK. It is strongly advised that you use the [Braintree, a PayPal Service](https://www.braintreepayments.com/) SDK if possible. Braintree has more capabilities for credit card processing while also accepting PayPal and other payment methods. You can find their [iOS SDK open source here](http://github.braintreeps.com/braintree/braintree-ios).

If you cannot use Braintree, you can look at version [2.15.1 of this SDK](https://github.com/paypal/PayPal-iOS-SDK/blob/2.15.1/SampleApp/PayPal-iOS-SDK-Sample-App/ZZMainViewController.m#L44) and make sure that you enable the accept credit cards.
