### ISSUE TITLE
[Question] choose if payment must be canceled / continued after the client enter credentials

### ISSUE THREAD

**Issue by Nexmind** [paypal/PayPal-iOS-SDK#533]
* SDK/Library version:  2.16.1
* Environment: Sandbox

Hello, 

I would like to know if there are a way to execute some code just before the payment (after the user enter credentials and accept the payment) and tell if the payment must be done or not. 

For example: 
Someone order something, enter his credentials and click on pay button, we request our server to create the order, and if the order is correctly created we continue the payment. In not we cancel the payment.

**Comment by bluk** [comment]
There is not a way to execute code before the payment (but after login) in this SDK. You can try to create a payment with Authorization intent (set your `PayPalPayment.intent = PayPalPaymentIntentAuthorize`), and when the payment completes, go ahead and create the order. When it is time to actually complete the transaction on your server, you would then [capture the payment](https://developer.paypal.com/docs/integration/direct/payments/authorize-and-capture-payments/#capture-the-payment).

You may get more flexibility in the [Braintree iOS SDK](https://github.com/braintree/braintree_ios) where you can tokenize a payment method and then actually complete the sale later as well. Braintree is a PayPal service which accepts credit cards, PayPal, and other payment methods.
