### ISSUE TITLE
PAYMENT_CREATION_ERROR

### ISSUE THREAD

**Issue by ikarmakhan** [paypal/PayPal-iOS-SDK#534]
Hello,

I have integrated PayPal iOS SDK to my app and it was working fine (both sandbox and live) and I have also made 2 transactions to verify the Live environment is setup properly. From past 2 days, I have started getting this error. After searching all forums and trying everything, (Currency is GBP, account I am using to sign-in is not sandbox and etc.), I am still unable to resolve the issue. 

PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: 64ec2d9f2dd2a, 64ec2d9f2dd2a [live, PayPal iOS SDK 2.17.0]

Please guide me how to resolve this issue. Thanks :-)

**Comment by xiaoleih41** [comment]
This doesn't look like a technical issue. It may have something to do with the sender and/or receiver's account status. Please contact customer service number on your account to see if you can get anymore information.
