### ISSUE TITLE
Internal server error in sandbox: If payment amount is exact $150 or $200

### ISSUE THREAD

**Issue by ksingh65** [paypal/PayPal-iOS-SDK#535]
https://github.com/paypal/PayPal-iOS-SDK/issues/472

We are receiving same error as mentioned above, while making a payment of $150 or $200, exact. Is it going to happen in production please let us know.

**Comment by xiaoleih41** [comment]
Do you have a `DebugId` that you can share? I don't think it will happen in production as if it's an issue you should be sandbox issue only.

**Comment by anandyn02** [comment]
here is the PayPal Debug-ID: ae9ad420e2ef0, ae9ad420e2ef0 [sandbox, PayPal iOS SDK 2.16.1]  at we have received.

**Comment by xiaoleih41** [comment]
@anandyn02 Do you have payment review turned on? You may turn it off to make sure the payment go through.

**Comment by xiaoleih41** [comment]
Close this issue as the issue might have been solved.
