### ISSUE TITLE
Payment via credit card raises "The merchant does not accept payments of this type"

### ISSUE THREAD

**Issue by hashans** [paypal/PayPal-iOS-SDK#537]
### General information

* SDK/Library version: 2.16.1
* Environment: Production
* `PayPal-Debug-ID` values: 86da07839733c, 86da07839733c
* iOS Version and Device: iOS 10.3.3 on an iPhone 6s
* Integration type and version: CocoaPods 1.2.1

### Issue description

When i try to make a payment via credit card it says, "The merchant does not accept payments of this type" . 

In the logs it shows, UNAUTHORIZED_PAYMENT.

But payments via PayPal login works fine.

How do i resolve this? What needs to be done?

**Comment by pp-randy** [comment]
Can you ensure you have Direct Credit Cards enabled for Live
https://developer.paypal.com/developer/accountStatus

**Comment by hashans** [comment]
Thanks a lot. It did work. I have another question @pp-randy . Is there a possibility to send invoices to people who pay via credit cards? May be by passing email address.

**Comment by pp-randy** [comment]
Yes, you can send invoices and in some cases they can use the Guest Checkout process and in other cases they could use a PayPal account and select a credit card as the funding source.

Let me know if you have further questions.

**Comment by hashans** [comment]
Thank you very much for the response @pp-randy . So how do i send invoices to users who are using Guest Checkout? Is there an option to pass user's email address in the SDK? 

Right now when using the Guest Checkout, you just enter the credit card details and have to just press "Charge Card" and that's it.

**Comment by pp-randy** [comment]
You can't send invoices from this iOS SDK, you would need to integrate a server side on.  Sorry for an confusion on that.

**Comment by MathaniPhone** [comment]
As @pp-randy  Mentioned I have Checked the below : 
Direct Credit Cards enabled for Live
Even though getting the Popup on iOS..
Any help would be appreciated. Thanks.

**Comment by MathaniPhone** [comment]
Alos, #hashans
What are the changes you made after @pp-randy suggested ?
