### ISSUE TITLE
Memory retain cycle on PayPalMobile.initializeWithClientIdsForEnvironments

### ISSUE THREAD

**Issue by neokree** [paypal/PayPal-iOS-SDK#538]
### General information

* Project Language: Swift
* SDK/Library version: 2.17.0
* Environment: Sandbox and production
* iOS Version and Device: iOS 10.2.1, iPhone 5C
* Integration type and version: Manual

### Issue description

I integrated the SDK in my app, but there is a retain cycle on the `PayPalMobile.initializeWithClientIdsForEnvironments` method. 

<a href="https://ibb.co/nuisX5"><img src="https://preview.ibb.co/kqFT5Q/Schermata_2017_07_28_alle_12_22_13.png" alt="Schermata_2017_07_28_alle_12_22_13" border="0"></a>

I inspected it with the `Debug Memory Graph` tool.

**Comment by bluk** [comment]
Thanks for reporting the issue. It is being investigated.

**Comment by bluk** [comment]
This should be fixed in release [2.18.0](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.18.0).
