### ISSUE TITLE
PAYEE_ACCOUNT_INVALID though everything is set up correctly 

### ISSUE THREAD

**Issue by romaHerman** [paypal/PayPal-iOS-SDK#540]
Hi, 

I have PayPal business pro account enabled and I'm receiving following error when trying to authorize payment  with credit card 

> PayPal SDK: Request has failed with error: PAYEE_ACCOUNT_INVALID - Vendor account does not have a confirmed email. (400) | PayPal Debug-ID: a6d59469b5b5d, a6d59469b5b5d [sandbox, PayPal iOS SDK 2.17.0]

```
` PayPalMobile.preconnect(withEnvironment: PayPalEnvironmentSandbox)  `
            
`let payment = PayPalPayment(amount: 1, currencyCode: "USD", shortDescription: "TestGood", intent: .authorize)`
`if (payment.processable) {    
       let paymentViewController = PayPalPaymentViewController(payment: payment, configuration:    
       payPalConfig, delegate: self) present(paymentViewController!, animated: true, completion: nil) 
 }`
```

However when instead of credit card I choose "pay with PayPal account" everything works as expected

**Comment by pp-randy** [comment]
The payee needs to be eligible to receive credit card payments. 
https://developer.paypal.com/docs/api/payments/#definition-payee
![image](https://user-images.githubusercontent.com/6819909/29275659-741c2492-80d1-11e7-938f-44758c9f2b89.png)

**Comment by romaHerman** [comment]
Hi Randy 
thanks for your reply 

i think i'm missing some info because there are a lot of different links about similar features 

how i can check wether payee is eligible and how i can enable if it's not 

thanks

**Comment by xiaoleih41** [comment]
@romaHerman  The **payee** email address should be associated with a PayPal business pro account. I don't think there's a way for others to check if an account has been approved for pro. However, you can try [log in with PayPal](https://developer.paypal.com/docs/integration/direct/identity/log-in-with-paypal/) to have the user log into his PayPal account and release the info on his **account type**(business or personal) and **verified status**(verified or unverified). The attributes of log in with PayPal are listed [here](https://developer.paypal.com/docs/integration/direct/identity/attributes/).

**Comment by romaHerman** [comment]
@xiaoleih41 it is associated with pro 
and I'm getting this error

**Comment by xiaoleih41** [comment]
I saw the account is disabled for pro for some reason, that was the reason you got the error.

**Comment by qaisammari** [comment]
According to the website - you can accept credit card payments without the customers to use their paypal accounts (this is available for the standard and pro)

https://www.paypal.com/us/webapps/mpp/compare-business-products

![image](https://user-images.githubusercontent.com/30314830/29399399-b855bec2-8331-11e7-88ed-97b4089e8021.png)

**Comment by xiaoleih41** [comment]
You are using credit card API which requires the payee account has website payment pro enabled while yours is disabled.

**Comment by qaisammari** [comment]
is there a way to use credit card API that does not require users to login to their PayPal account ? website is very confusing!

**Comment by pp-randy** [comment]
For Direct Credit Card payments we encourage using our Braintree products https://www.braintreepayments.com/. 

For PayPal Credit Cards you need Website Payments Pro as indicated by @xiaoleih41; otherwise, it would be Guest Checkout in a PayPal flow which might not be available to all buyers.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been provided.
