### ISSUE TITLE
Paypal SDK : We are sorry. - System Error.Please try Again later.

### ISSUE THREAD

**Issue by JaswinderImmanent** [paypal/PayPal-iOS-SDK#543]
### General information

* SDK/Library version: 2.17.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: f4cbba1115ef5
* iOS Version and Device:  on an iPhone 6s  and on emulator(iphone 7plus) in xcode2

### Issue description
I am trying to integrate com.paypal.cordova.mobilesdk Plugin in my ionic cordova App.I am getting this error : System Error.Please try again later.
This error is random.I am getting this error while inserting card information manually.

Below is the error -

PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. 

(500) | PayPal Debug-ID: f4cbba1115ef5, f4cbba1115ef5 [sandbox, PayPal iOS SDK 2.17.0]

If sometimes,there is no error then the response is like:
paypal_response={\n    \"client\": {\n        \"environment\": \"sandbox\",\n        \"product_name\": \"PayPal iOS SDK\",\n        \"paypal_sdk_version\": \"2.17.0\",\n        \"platform\": \"iOS\"\n    },\n    \"response_type\": \"payment\",\n    \"response\": {\n        \"id\": \"PAY-9UPTHBVF57P1579152NLYTGGGGTGFCA\",\n        \"state\": \"created\",\n        \"create_time\": \"2017-08-30T07:00:24Z\",\n        \"intent\": \"sale\"\n    }\n}"

In response the state is state: "created" not approved

Please help me to solve this issue.

Thanks in advance!

**Comment by xiaoleih41** [comment]
Please make sure it's not an existing PayPal sandbox card number as it could have been overused. Please try a newly generated random card number. Also, if you just started this project, I would strongly suggest you to look into Braintree SDK from braintreepayments.com. PayPal is deprecating credit card feature on REST API. We are in the process of removing all credit card components out of the REST SDK.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been provided.
