### ISSUE TITLE
[Help] Integrate flow send money

### ISSUE THREAD

**Issue by tranchuong** [paypal/PayPal-iOS-SDK#544]
### General information

* SDK/Library version: 2.17.0
* Environment: Sandbox
* iOS Version and Device:  iPhone 6s
* Integration type and version: CocoaPods 1.3.1

### Issue description
I have a question.
Can I integrate flow send money from user A to user B with PayPal-iOS-SDK?

Please help me to clear at this point

**Comment by xiaoleih41** [comment]
I don't quite understand your question. Can you provide more detail with an example?

**Comment by tranchuong** [comment]
It's mean, I stuck at step [generate access token](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_mobile.md#obtain-customer-consent) when I integrate flow payout

Finally, I find an issue from backend, not from iOS SDK
I create new an issue at [PayPal-node-SDK](https://github.com/paypal/PayPal-node-SDK/issues/300)
