### ISSUE TITLE
Remove Card Camera Scanning

### ISSUE THREAD

**Issue by turboz747** [paypal/PayPal-iOS-SDK#545]
Please kindly remove card scanning as default.
I think "enter manually" is the best default option for most people for user experience.
Camera scan is out-of-date and not accurate. 
Thank you.

For most cases, the scan doesn't work. So, I want to disable it. Secondly, most users already memorize their card number because E-commerce is so popular.
I know there's an "enter manually" option, but it's a bad User experience for using card scan.
We don't want it to show to users.
Finally, card.io is huge, we don't want it. Please provide the workaround to remove it.
Thank you very much!!!
Most people don't complain it because they turn to Braintree or Stripe. But, some companies like us can't use their service. Paypal mobile SDK is the only solution for us to provide the native user experience.
Please provide the workaround solution.
For Android, we have workaround solution, and we can remove the card.io.
But it's not achievable for iOS.

### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* iOS Version and Device: 
* Integration type and version:

**Comment by xiaoleih41** [comment]
As PayPal has put direct credit processing through REST API to limited edition at this time, there won't be any modification to this part of SDK at this time. A customer  should have the option to press "enter manually" to input their credit card numbers.
