### ISSUE TITLE
Need to pass the Credit Card info to iOS Sdk directly

### ISSUE THREAD

**Issue by aparthdhorda** [paypal/PayPal-iOS-SDK#546]
I am developing the application and using PayPal iOS SDK Version 2.17.0,  the requirement of the client is to pass the saved credit card info to SDK and there user just needs to press the single pay button.

The credit card information is already filled into the SDK without login with the account, when user wants to checkout as Guest.

Is there any way to do this way.

Any help will be appreciated

**Comment by xiaoleih41** [comment]
I would strongly recommend you to use our Braintree SDK from braintreepayments.com instead. The github link is at https://github.com/braintree/braintree_ios. It has vault feature which allows you to save credit card info for future payments and it supports not only direct credit card payment processing but also PayPal payments.  PayPal SDK is deprecating the direct credit card processing. I would not recommend you to use this SDK.

**Comment by xiaoleih41** [comment]
Close this issue as REST direct card processing has been deprecated. Suggestion for alternative method are given.
