### ISSUE TITLE
Crash: PPRiskDeviceData.m line 356 -[PPRiskDeviceData getVPNSetting] 

### ISSUE THREAD

**Issue by jontelang** [paypal/PayPal-iOS-SDK#547]
### General information

* SDK/Library version: 2.14.3
* Environment: Production JAILBROKEN devices
* `PayPal-Debug-ID` values: _Not sure where to find this, didn't see anything that would fit_
* iOS Version and Device: iPhone 5c, 5s, SE, 6s+, 7 - iOS 10.0.1, 10.1.1, 10.3.0, 10.3.1, 10.3.3
* Integration type and version: CocoaPods 1.2.0

### Issue description

Unfortunately we have little to no logs as we initialise the PayPal SDK very quickly and it seems to crash instantly. We do use a slightly older version of the SDK, which we will be upating. However the changelogs did not mention the crash so I figured I would create the ticket anyway.

Worth mentioning again if it wasn't obvious from the info above, this seems to affect Jailbroken devices only. Unfortunately the crash happens before we are able to add any identifying IDs to the crashlogs, so I'm unable to contact them directly to ask if they did anything specific that could cause this issue.

### Stack trace from Crashlytics/Fabric

[com.hotelquickly.app_issue_248_crash_2ff75b6e763c421abe5766c33dfd48ea_ba3c0b56a7f611e7a63356847afe9799_0_v2.txt](https://github.com/paypal/PayPal-iOS-SDK/files/1351402/com.hotelquickly.app_issue_248_crash_2ff75b6e763c421abe5766c33dfd48ea_ba3c0b56a7f611e7a63356847afe9799_0_v2.txt)

[com.hotelquickly.app_issue_248_crash_871c63cfb7ff4040bc9a23a870dc3771_9060fecca7be11e7a63f56847afe9799_0_v2.txt](https://github.com/paypal/PayPal-iOS-SDK/files/1351403/com.hotelquickly.app_issue_248_crash_871c63cfb7ff4040bc9a23a870dc3771_9060fecca7be11e7a63f56847afe9799_0_v2.txt)

[com.hotelquickly.app_issue_248_crash_dbed1462b75c450987bdf2152d8177f6_b2df424aa7be11e7b1d756847afe9799_0_v2.txt](https://github.com/paypal/PayPal-iOS-SDK/files/1351406/com.hotelquickly.app_issue_248_crash_dbed1462b75c450987bdf2152d8177f6_b2df424aa7be11e7b1d756847afe9799_0_v2.txt)

**Comment by bluk** [comment]
Thanks for the report. I've notified the relevant team to see if a fix can be applied.

**Comment by jontelang** [comment]
I'd like to add some more information. We now have around 60 crashes and they are all flagged as jailbroken. However, that's a very very high amount of supposedly jailbroken devices and I am not sure that they are. We don't have that many DAU that would warrant such a high number of jailbroken devices. 

The flagging _might_ (not for sure) be wrong here, so please consider that this might be an issue for normal devices as well.

**Comment by bluk** [comment]
This issue may have been fixed by [2.18.0](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.18.0). Can you please try this version and see if the issue occurs?

**Comment by jontelang** [comment]
I'll update, however the crashes have stopped (either due to these people stopped using the app as a result, or it was something temporary). We had 250 crashes from 72 users crashing between Oct 1 and Oct 7. So I'm not sure if I can confirm/deny that the update is the definitive fix, but I'll update it anyway. Thanks.

**Comment by jontelang** [comment]
After updating to 2.18.0, all devices crash on initializing the environment, stating the following:

`2017-10-24 11:59:32.716 HotelQuickly[1240:381979] -[PPRiskConfiguration mgIdKey]: unrecognized selector sent to instance 0x1701fc60
2017-10-24 11:59:37.340 HotelQuickly[1240:381979] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PPRiskConfiguration mgIdKey]: unrecognized selector sent to instance 0x1701fc60'
*** First throw call stack:
(0x20f69b0b 0x20726dff 0x20f6f455 0x20f6d0ab 0x20e97298 0x359155 0x3587e5 0x357495 0x3564ff 0x355d8d 0x22e57a9 0x355d2f 0x3287af 0x3278c9 0x22e4b93 0x22e57a9 0x327893 0x327a85 0xfe219 0xfd37d 0x255bda6f 0x257e7287 0x257eb241 0x257ff811 0x257e8767 0x22637bf7 0x22637aa7 0x22637da5 0x20f2b9e7 0x20f2b5d7 0x20f2993f 0x20e781c9 0x20e77fbd 0x255b6f37 0x255b1435 0x1f5f43 0x20b24873)
libc++abi.dylib: terminating with uncaught exception of type NSException`

So far this happens on

Jailbroken
========
iPhone 5s 9.0.2
iPhone 10.2

Not jailbroken
===========
iPhone 5 (32bit) 9.3.4
iPhone 5s 10.2
iPhone 5s  8.4.1

**Comment by bluk** [comment]
Closing this issue since it may be related to the usage of Braintree and PayPal in the same app as discovered in #553 . If this issue occurs again, please leave a comment.
