### ISSUE TITLE
Ios 11 login screen opening animation bug

### ISSUE THREAD

**Issue by hilord** [paypal/PayPal-iOS-SDK#548]
### General information

* SDK/Library version: 2.17.0
* Environment: Sandbox
* iOS Version and Device: IOS 11.0.1 and iphone 5s

### Issue description
On all ios devices with ios 11.0.1 (and higher) there is visual bug after pressing paypal login. It looks like the screen or keyboard opening animation is played 2 times.

![img_9737](https://user-images.githubusercontent.com/1778063/31309150-fbcbd362-ab9a-11e7-9703-5841275286d2.png)

**Comment by rzulkoski** [comment]
+1

**Comment by bluk** [comment]
Thanks for the report. This should be fixed in the next release (which should be this week).

**Comment by bluk** [comment]
This should be fixed in release [2.18.0](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.18.0). If not, please leave a comment and we can reopen or open a new issue.
