### ISSUE TITLE
Feature Request: Add Carthage Support

### ISSUE THREAD

**Issue by rzulkoski** [paypal/PayPal-iOS-SDK#549]
Please consider adding Carthage support to make it easier to integrate the SDK.

**Comment by bluk** [comment]
You can try using the instructions [here](https://github.com/paypal/PayPal-iOS-SDK/tree/master/PayPalMobileSDKFramework#carthage) for an "unsupported" way to get the project working with Carthage.

I would strongly advise looking at the [Braintree iOS SDK](https://github.com/braintree/braintree_ios) for better distribution options. The SDK is open source. If you are only doing a single payment checkout, you can use [Express Checkout with the Braintree iOS SDK](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/client-side/ios/v4/).

If you need more payment method options (e.g. you wish to [save/vault the PayPal payment method](https://developers.braintreepayments.com/guides/paypal/overview/ios/v4) like future payments), I would try to open a [Braintree account](https://www.braintreepayments.com/) directly. Braintree is a PayPal service and supports many payment methods including direct credit card (with more support than this SDK), PayPal, Apple Pay, etc.
