### ISSUE TITLE
IOS integrated paypal-sdk

### ISSUE THREAD

**Issue by x2201783** [paypal/PayPal-iOS-SDK#552]
IOS integrated paypal-sdk, initializeWithClientIdsForEnvironments:
PayPalConfiguration, preconnectWithEnvironment, are written in - (IBAction) pay{}, OK? I'm working on aggregate payments, and I want to make it easier for integrators to complete integration, and it's best to do it in one way, without writing a few methods, such as
DidFinishLaunchingWithOptions, initWithCoder, viewWillAppear, let the integrators to achieve, too much trouble.

**Comment by bluk** [comment]
@x2201783 It depends on your integration. For instance, for an optimal experience, you should always pre-connect early.

Note that this SDK is deprecated. You should try using the [Express Checkout with Braintree SDKs](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/) which can lead to fewer methods required for implementation.

**Comment by x2201783** [comment]
hi, bluk!
              I want to know for sure, initializeWithClientIdsForEnvironments:
PayPalConfiguration, preconnectWithEnvironment, do these objects initialize in - (IBAction) pay{}, will there be a problem? If there is a problem, can you explain it?

**Comment by bluk** [comment]
Some of the methods may need additional time to setup so if you do everything after an action is clicked, it could result in a very stalled action and may look like the app is frozen.

Again, I would emphasize that this SDK is deprecated, so if you intend for your library to be supported, you should use the Express Checkout with Braintree SDKs.
