### ISSUE TITLE
I cannot use this SDK for iOS app anymore?

### ISSUE THREAD

**Issue by hanming223** [paypal/PayPal-iOS-SDK#554]
I saw that your SDK is deprecated and is no longer available for new integration.
I have integrated this SDK to my app and it is in Sandbox mode.  But it works well.
It won't make any problems when I publish app and put it into live mode.
Looking forward to your reply soon.

Thank you.

**Comment by xiaoleih41** [comment]
You can use it. If you have integrated the credit card part, you won't be able to get production feature on that as you won't be able to apply for that feature in live. Other than that, the Paypal side function should still work.

**Comment by hanming223** [comment]
For credit card part, I should use Braintree?

**Comment by xiaoleih41** [comment]
Yes please, you can use Braintree for both credit card and PayPal.
