### ISSUE TITLE
System Error PAYER_ACTION_REQUIRED  Please try again later. (400)

### ISSUE THREAD

**Issue by vittorioscocca** [paypal/PayPal-iOS-SDK#555]
### General information

* SDK/Library version: iOS Sdk 2.17.0 
* Environment: Sandbox
* `PayPal-Debug-ID` values: PayPal Debug-ID: cccbcf64c9e0, cccbcf64c9e0 [sandbox, PayPal iOS SDK 2.17.0] 
* iOS Version and Device: All ios version and all devices
* Integration type and version: CocoaPods 1.0

### Issue description

Sandbox error while making payment:

"Request has failed with error: PAYER_ACTION_REQUIRED - System error (PAYER_ACTION_REQUIRED). Please try again later. (400) | PayPal Debug-ID: cccbcf64c9e0, cccbcf64c9e0 [sandbox, PayPal iOS SDK 2.17.0]. "

**Comment by xiaoleih41** [comment]
I saw successful payments made to the account. Was the issue resolved?

**Comment by pp-randy** [comment]
Closing this issue out as you are already working with an integration team.

**Comment by vittorioscocca** [comment]
yes, it seems that the problem is no longer there

thank you
