### ISSUE TITLE
Login View Controller seems to be pushed twice

### ISSUE THREAD

**Issue by motapuma** [paypal/PayPal-iOS-SDK#556]
### General information

* SDK/Library version:  2.17.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* iOS Version and Device: iPhone 5s 11.0
* Integration type and version: Cocoapods 1.2.1

### Issue description

In the Demo Example,and even in my app, when using a "Single Payment", when the ViewController to login appears, it seems to appear twice.
![twicepushviewcontroller](https://user-images.githubusercontent.com/4665501/32635429-fad7296c-c575-11e7-939b-be2133466d86.gif)

**Comment by bluk** [comment]
Does this also occur with version 2.18.0?

**Comment by motapuma** [comment]
It does not occur with version 2.18.0.... sorry for opening the issue!
