### ISSUE TITLE
There was a problem setting up this payment. Please visit the paypal website to check your account

### ISSUE THREAD

**Issue by lili-shangshu** [paypal/PayPal-iOS-SDK#557]
### General information

* SDK/Library version: 2.17.0
* Environment: Production
* `PayPal-Debug-ID` values: ccde8d9e96178（422）
* iOS Version and Device:  iOS 10.3 on an iPhone 6s 

### Issue description

I'm using Paypal cordova plugin (latest version 3.1.23) in an mobile app and we can't test payments in Live mode. Once logged with a real buyer Paypal account (which have credit cart and bank account associated), we have a popup displaying the following error :

 PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: ccde8d9e96178, ccde8d9e96178 [live, PayPal iOS SDK 2.17.0]
When in sandbox mode with a sandbox account it is working fine.

**Comment by pp-randy** [comment]
Can you please reach out to PayPal Technical Support for assistance since this is impacting your production integration?  You can submit an issue here: https://www.paypal-techsupport.com/app/ask.
