### ISSUE TITLE
Landscape UINavigationBar problem to pay by card

### ISSUE THREAD

**Issue by julien290** [paypal/PayPal-iOS-SDK#558]
After the user input the credit card informations, there is no way to make the payment, is there something to do ?

<img width="781" alt="pp x" src="https://user-images.githubusercontent.com/4374562/32866051-b834ee92-ca1a-11e7-8a2d-d59f87f551f5.png">

- Model : iPhone X
- iOS : 11

Thanks in advance.

**Comment by xiaoleih41** [comment]
This SDK has been deprecated. Please use braintreeSDK at braintreepayments.com

**Comment by xiaoleih41** [comment]
Close due to inactivity.
