### ISSUE TITLE
PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: a59fc41eae8b, a59fc41eae8b [sandbox, PayPal iOS SDK 2.15.1]

### ISSUE THREAD

**Issue by VARADA1992** [paypal/PayPal-iOS-SDK#564]
I cannot login using paypal sandbox credentials.
Tried lots of sandbox personal account credentials to login. But same message is getting.

There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: a59fc41eae8b, a59fc41eae8b [sandbox, PayPal iOS SDK 2.15.1]

**Comment by xiaoleih41** [comment]
I can't find the log associated with this debugId. Do you have a more recent one?

**Comment by xiaoleih41** [comment]
Close due to inactivity. Please resubmit when you have additional info.
