### ISSUE TITLE
libPaymentsSDK.a' is not permitted 

### ISSUE THREAD

**Issue by THAANURK** [paypal/PayPal-iOS-SDK#565]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* iOS Version and Device: 
* Integration type and version:

**Comment by pp-randy** [comment]
Related to https://github.com/paypal/PayPal-iOS-SDK/issues/233

**Comment by pp-randy** [comment]
@THAANURK is this a new integration?  The PayPal mobile SDKs have been deprecated in favor of our Braintree offerings.  

From the Readme
> **Important**: PayPal Mobile SDKs are now Deprecated and only existing integrations are supported. For all new integrations, use [Braintree Direct](https://www.braintreepayments.com/products/braintree-direct) in [supported countries](https://www.braintreepayments.com/country-selection). In other countries, use [Express Checkout](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/) and choose the Braintree SDK integration option.

**Comment by xiaoleih41** [comment]
Close the issue as the answer has been given.
