### ISSUE TITLE
Able to process test credit cards in Production

### ISSUE THREAD

**Issue by itaispector** [paypal/PayPal-iOS-SDK#566]
### General information

* SDK/Library version: 2.18.0
* Environment: Production
* `PayPal-Debug-ID` values: none
* iOS Version and Device: iOS 11.2 iPhone 6
* Integration type and version: CocoaPods 

### Issue description
While QAing my app in Release mode, I've randomly tried to enter a test credit card number, such as:
`4242 4242 4242 4242 12/18 123`
And processing was completed.
We tried other test cards such as:
`5555 5555 5555 4444 12/18 123`
And it was successful as well.

I would love to get some inputs about this ASAP

Thanks

**Comment by pp-randy** [comment]
@itaispector can you submit this issue to PayPal Technical Support https://www.paypal-techsupport.com/app/ask/?  Then provide the ticket number so I can have someone follow up.

**Comment by itaispector** [comment]
@pp-randy Thanks for your reply. here's the ticker number: `#180109-000111`

**Comment by pp-randy** [comment]
Do you have the Payment Ids, I will see if I can also locate any logging for these?

**Comment by itaispector** [comment]
@pp-randy this one for example:
`PAY-0N076367YT197051WLJKJZCQ`

**Comment by itaispector** [comment]
@pp-randy I don't have one. I will update support ticket asap.
Appreciate your responsiveness as well.

**Comment by itaispector** [comment]
@pp-randy I got response from PayPal support from a guy named Robert:

> We were able to locate one of these transactions. I have escalated this to our engineers to look into. No transaction was actually created, but our API incorrectly returned a 200 OK message to your application. We apologize for this inconvenience and ask your patience as we look into this issue.

**Comment by pp-randy** [comment]
@itaispector thank you for the help.  I will let PayPal Technical Support followup with you further for this issue.  

Let me know if you need anything else.
