### ISSUE TITLE
PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR

### ISSUE THREAD

**Issue by JayGajjar** [paypal/PayPal-iOS-SDK#567]
### General information

* SDK/Library version:PayPal iOS SDK 2.18.0
* Environment: Sandbox 
* `PayPal-Debug-ID` values: 322d2d9e5d544, 322d2d9e5d544
* iOS Version and Device: iOS 11.2 iPhone6s Plus
* Integration type and version: CocoaPods latest

### Issue description

PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: 322d2d9e5d544, 322d2d9e5d544 [sandbox, PayPal iOS SDK 2.18.0]

**Comment by xiaoleih41** [comment]
It looks like the transaction limit has exceeded. Depending on the regional regulation, each country has certain amount of per transaction receiving limit. Please check with your regional customer service on the specifics.  You can try a smaller amount for the test to see if you can get it through.

**Comment by JayGajjar** [comment]
PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: 8d109798dff1f, 8d109798dff1f [sandbox, PayPal iOS SDK 2.18.0]


Same thing appears when it tried with 2 pound. 
Why its creating trouble in sandbox mode ? 
Is there any way i can increase this limits in Sandbox env ?

**Comment by pp-randy** [comment]
This looks like an issue with the currency.   I will admit I am not sure what currencies are supported for India accounts.  

Does your receiver account have GBP as a currency?  https://www.sandbox.paypal.com/us/cgi-bin/webscr?cmd=_profile-currencies

Does USD work?

**Comment by JayGajjar** [comment]
Should i use british account for british pound ?

**Comment by pp-randy** [comment]
I think you should try to use the accounts you intend to use on live, especially the merchant account. 

What is your expected country for the live merchant account?

**Comment by JayGajjar** [comment]
planning for London.

**Comment by pp-randy** [comment]
Then yes, test with UK accounts and let us know if you continue to get this error.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been given.
