### ISSUE TITLE
Question: Does deprecation of DCC means not allowing new accounts to support DCC on apps?

### ISSUE THREAD

**Issue by glennposadas** [paypal/PayPal-iOS-SDK#568]
I have an urgent issue at the company I am working for, the company has a new PayPal account and therefore the Sandbox Client Id and the Live Client Id need to be changed in code. Anyways, the new PayPal account does not let me pay in sandbox mode using sandbox/dummy credit card (e.g. 4242 4242...).

I've read the deprecation of this SDK. Does this mean that PayPal won't accept payment in new accounts?

I've read multiple times that the PayPal account must be upgraded to PRO version to receive payments. Note that the company is based in U.S. and I can't remember if the old working PayPal account was upgraded to PRO before it started accepting payments.

Thank you!

**Comment by pp-randy** [comment]
Direct Credit Card payments with the PayPal REST API is no longer supported for new accounts; however,  you should have the company to contact a PayPal Sales team and see if they can still use it.  https://www.paypal.com/us/webapps/mpp/accept-payments-online.  

If you are not trying to capture credit cards directly and using the paypal payment method then this SDK is ok to use but you still might want to consider the recommended Braintree SDK. 

For sandbox test credit cards: https://www.paypal-community.com/t5/Payments/Test-Credit-Card-numbers-for-use-on-PayPal-sandbox/td-p/1124657

**Comment by pp-randy** [comment]
Closing the issue as I think I covered everything; however, let me know if you have further questions.

**Comment by glennposadas** [comment]
Hey @pp-randy  thank you for the quick reply.

I am not sure if the payment through this SDK's Modal screen and inputting manually the credit card info is DCC lol.

AND here comes the weird part. (did this twice :-o) I was using the old paypal client Ids in my code and I FORGOT to set the preconnect environment to Sandbox. 

```PayPalMobile.preconnect(withEnvironment: PayPalEnvironmentProduction)```

So I was unaware when I paid with a dummy credit card (4242 4242 4242...) and PayPal returned me a success. How was that possible?

Anyways, so the new paypal account works now, I just indeed forgot to set the code above to Sandbox that's why it does not accept the 424242 credit card info, but damn, it was accepted in the old account in production.

Then lastly, though not confirmed why with my boss, I now can't login the old paypal account of the company after this incident. 

*going to try this 4242 credit card from the app from the app store*

**Comment by pp-randy** [comment]
> I am not sure if the payment through this SDK's Modal screen and inputting manually the credit card info is DCC lol.

Yes, that is DCC.

> So I was unaware when I paid with a dummy credit card (4242 4242 4242...) and PayPal returned me a success. How was that possible?

Its an open bug:
https://github.com/paypal/PayPal-Android-SDK/issues/457
https://github.com/paypal/PayPal-iOS-SDK/issues/566
The Payment returns but no transaction is created.

**Comment by glennposadas** [comment]
Awesome. Thank you so much. Now everything was solved and cleared.
