### ISSUE TITLE
PayPal iOS SDK acceptCreditCards = YES Crash

### ISSUE THREAD

**Issue by qinxianjun** [paypal/PayPal-iOS-SDK#570]
_payPalConfig = [[PayPalConfiguration alloc] init];
Set _payPalConfig.acceptCreditCards = YES;
Then,the Demo of PayPal-iOS-SDK Crashed.
So I want to know if SDK support Credit Cards?

**Comment by xiaoleih41** [comment]
We have deprecated this SDK and also credit card payment option for the REST API. If it's a new integration, please look into Braintree SDK instead. Please check the README.MD for detail.

**Comment by qinxianjun** [comment]
OK,Thanks!
