### ISSUE TITLE
Canadian Company - Direct credit card transaction fails, but paypal account transactions succeed

### ISSUE THREAD

**Issue by brendanmwoods** [paypal/PayPal-iOS-SDK#571]
### General information

* SDK/Library version: 2.18.0
* Environment: Production
* iOS Version and Device: ios 11 , iphone 10

### Issue description

When the paypal SDK presents the payment options, if the user attempts to pay with a credit card (manual or photo recognition) , the process fails. If the user logs in to an existing paypal account, the payment succeeds. 

Is this a limitation of being a Canadian company, a deprecated SDK, or a bad implementation on our end?

This is the error that is seen:

![img_0388](https://user-images.githubusercontent.com/7787929/35596482-eb8dc81e-05ce-11e8-9882-357433ca0b21.PNG)

**Comment by bluk** [comment]
This SDK is deprecated as you noted, and new direct credit card integrations are not supported. For all new credit card integrations, use [Braintree Direct](https://www.braintreepayments.com/products/braintree-direct) in [supported countries](https://www.braintreepayments.com/country-selection). I would also highly recommend that you use them for the PayPal integration as well.

**Comment by brendanmwoods** [comment]
Thanks for the response. This is an existing implementation that apparently was functional at the beginning of last year.

**Comment by bluk** [comment]
Please contact [PayPal Technical Support](https://developer.paypal.com/support/) with any logs that you have (including any `PayPal-Debug-Id` in the logs).
