### ISSUE TITLE
PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: a02b03ac608db, a02b03ac608db [sandbox, PayPal iOS SDK 2.14.3]

### ISSUE THREAD

**Issue by a3yogendra** [paypal/PayPal-iOS-SDK#573]
### General information

* SDK/Library version: 2.14.3
* Environment: sandbox
* `PayPal-Debug-ID` values: a02b03ac608db
* iOS Version and Device: iOS 10.3.2 on an iPhone 6 plus
* Integration type and version:

**Comment by yogendrabagoriya** [comment]
Facing same issue with latest 2.18.1 SDK also.

**Comment by yogendrabagoriya** [comment]
@bluk Please have a look here.

**Comment by yogendrabagoriya** [comment]
@bluk 
PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: 78fafdad918de, 78fafdad918de [sandbox, PayPal iOS SDK 2.18.1]

**Comment by bluk** [comment]
It seems to a problem with your buyer accounts. You may want to try using a different buyer account. You can contact [PayPal Technical Support](https://developer.paypal.com/support/) for more assistance.

If this is an India based merchant/buyer account, this SDK does not support that flow at this time. You should use [Express Checkout with Braintree SDK](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/) for single payment checkout flows. Express Checkout with Braintree SDK is also the recommended solution (this SDK is deprecated)

**Comment by sauchye** [comment]
Hi @bluk

**Comment by sauchye** [comment]
@bluk  Hi  Sorry to disturb you ， i feedback PayPal Technical Support  not response ， please see 180521-000001, thank you !
Hi, I'm using your PayPal iOS SDK,but test show me that's:

PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: f00e2675bd481, f00e2675bd481 [live, PayPal iOS SDK 2.18.1]

I register China PayPal  developer account, other test account also China account,
currency : USD

live show that, sandbox test success, Would you mind help me ,thank you!

**Comment by sauchye** [comment]
@xiaoleih41  May i need register a US  developer account ?  Now  developer  buyer both are  China account. and i test $0.01 in live but sandbox is ok.  I can try.  thank you!

**Comment by sauchye** [comment]
I tried this registered U.S. zone account. but i was unable to register for U.S. zone account due to some information I could not provide. Could you give me U.S. PayPal account for test, thank you! @xiaoleih41
