### ISSUE TITLE
PayPalPaymentViewController Crash upon server communication failure

### ISSUE THREAD

**Issue by johnrogers** [paypal/PayPal-iOS-SDK#60]
I am attempting to test using the Sandbox. For some reason, using the credentials found on the Developer website, the app is failing to connect with the servers when I try to make a test payment. Works find in No Network "Mock" mode.

Aside from that issue, though, after clicking "Okay" to the alert view which says "There was a problem communicating with the PayPal servers. Please try again.", the app crashes. Here's a screenshot of the alert view I tapped:

![screen shot 2013-11-26 at 2 10 00 pm](https://f.cloud.github.com/assets/998649/1619125/3f285c0e-5648-11e3-957a-36d0fe7075a6.png)

After tapping 'Okay', I get the following errors:

```
*** Assertion failure in -[UITableView _endCellAnimationsWithContext:], /SourceCache/UIKit/UIKit-2903.23/UITableView.m:1314
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of sections.  The number of sections contained in the table view after the update (3) must be equal to the number of sections contained in the table view before the update (3), plus or minus the number of sections inserted or deleted (0 inserted, 1 deleted).'
```

Obviously just the table view row count not being updated properly, but an annoying little bug nonetheless.

**Comment by KartikSinghBhadoriya** [comment]
@dgoldman-ebay
 hey In Latest iOS Sdk It Run in "mock" fine Bun When I change Mode In "Sandbox" than i got same issue as @Jyoshnakp  commented on Jul 8, 2014 "there was a problem communicating with paypal servers"..

![simulator screen shot 27-may-2016 1 15 48 pm](https://cloud.githubusercontent.com/assets/8698836/15603152/d61a0d26-2416-11e6-8ab1-f5a3730b716f.png)
