### ISSUE TITLE
CocoaPod upgrade from 1.4.1 to 1.4.4 cause duplicate symbol error

### ISSUE THREAD

**Issue by brenwell** [paypal/PayPal-iOS-SDK#73]
I am not sure exactly why but updating from 1.4.1 to 1.4.4 with
`pod update`
causes 140+ duplicate symbol errors on build such as

```
duplicate symbol _OBJC_CLASS_$_PPLinkableTextField
```

Any Ideas why

**Comment by subhashsanghani** [comment]
i Also got same error  While Archiving Project 

I am not sure exactly why but updating from 1.4.1 to 1.4.4 with
pod update
causes 140+ duplicate symbol errors on build such as

duplicate symbol _OBJC_CLASS_$_PPLinkableTextField
Any Ideas why

where can i fing  -all_load linker flag i search in Build Setting i can't find it please help me

**Comment by dgoldman-ebay** [comment]
See #269
