### ISSUE TITLE
duplicate symbol errors

### ISSUE THREAD

**Issue by ajaybhardwaj** [paypal/PayPal-iOS-SDK#76]
Hi Guys,

I have strongly followed the instructions for the PayPal integration but unfortunately i am getting error. Please see the attached screenshot.

![screen shot 2013-12-26 at 11 23 14 am](https://f.cloud.github.com/assets/4745531/1809379/05d6a778-6dde-11e3-97ff-f6e093b6f95a.png)

I am using Xcode ver.5.0.2. When i am unchecking the libPayPalMobile.a from targets this issue used to get resolved but other file reference error use to generate. Please see the attached for the same.

![screen shot 2013-12-26 at 11 33 40 am](https://f.cloud.github.com/assets/4745531/1809384/a4ee67d8-6dde-11e3-8111-8d950de78ad7.png)

Please let me know where i am going wrong & also i have gone through the other threads & tried all the possible solutions but no luck.

Thanks & Regards,
AJ

**Comment by subhashsanghani** [comment]
When i archiving an Application i got same error. Also there is no flag like -all_load 

Please help me where am i wrong.

**Comment by dgoldman-ebay** [comment]
See #269
