### ISSUE TITLE
Setting IPN (InvoiceID and Custom) from iOS Paypal library

### ISSUE THREAD

**Issue by sreelash** [paypal/PayPal-iOS-SDK#77]
I replaced the old MECL Paypal library with the new library downloaded from Github. It seems everything works fine, but I couldn't implement the IPN with this library. In the old lib, the payment model has the properties InvoiceID and Custom, which i couldn't find with the new lib. Is it possible to handle this feature with the new lib? Otherwise how can I make it works? Hoping a favourable reply ASAP. I have only one more day time to release the app.

**Comment by quocbao1087** [comment]
Same question, how can I do that now?
I have a magento website with integrate Paypal IPN by default. 
Now I use new Paypal iOS sdk, how can I set notify url as before.
