### ISSUE TITLE
"Invisible" Done Button

### ISSUE THREAD

**Issue by kumario** [paypal/PayPal-iOS-SDK#82]
Hey @ppalavilli and co. hope you all are doing well and happy new year to ya.  Thanks for your assistance last fall.  The SDK is working great and taking a lot of payments to feed kids.

Recently, we've had two iPhone users report that the Done button is missing after they've entered in CC details.  In the screenshot you can see it's invisible (it still works if you tap that area) as well as "Cancel".  In the other screenshot, you can see that center header text is black instead of white.

We were able to replicate this on our end, but do not believe it affects all users. 

Is this something on our end we should address or something on your end?

![img_2824](https://f.cloud.github.com/assets/1817675/1879986/f81a95d4-7951-11e3-918b-cc2f9b8ff65d.png)

![photo jan 09 11 56 10 am](https://f.cloud.github.com/assets/1817675/1879924/0fdf9b98-7951-11e3-9776-108fb44d4933.png)

**Comment by edwardyue** [comment]
Hihi, i also got the same problem and I still can't resolve the issue.

I tried below but the button is still missing....could you help?


    PayPalPaymentViewController *paymentViewController = [[PayPalPaymentViewController alloc] initWithPayment:payment
                                                                                                configuration:self.payPalConfig
                                                                                                     delegate:self];
    
    [[UIBarButtonItem appearance] setTintColor:nil];
    [[UINavigationBar appearance] setTintColor:nil];
    self.navigationController.navigationBar.tintColor = nil;
    
    [self presentViewController:paymentViewController animated:YES completion:nil];

**Comment by georgmay** [comment]
Same issue here.
